// packages/wiz-ui-next/src/components/base/text/text.vue
<template>
  <component
    :is="as"
    :class="[
      textStyle,
      textFontWeightStyle[bold ? 'bold' : 'default'],
      textAlignStyle[textAlign],
      (maxLines || breakAll) && textWordBreakStyle,
      lineHeight ? lineHeightStyle[lineHeight] : textDefaultLineHeightStyle,
      fontSizeStyle[fontSize],
      colorStyle[color],
      whiteSpaceStyle[whiteSpace],
      lineThrough && textLineThroughStyle,
    ]"
    :for="htmlFor"
    :style="overflowStyles"
  >
    <span :class="textDummyStyle" v-if="dummyValue">{{ dummyValue }}</span>
    <slot v-else />
  </component>
</template>

<script setup lang="ts">
import {
  ComponentName,
  ColorKeys,
  FontSizeKeys,
  WhiteSpaceKeys,
} from "@wizleap-inc/wiz-ui-constants";
import {
  textStyle,
  textDummyStyle,
  textDefaultLineHeightStyle,
  textFontWeightStyle,
  textWordBreakStyle,
  textAlignStyle,
  textLineThroughStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/text.css";
import {
  lineHeightStyle,
  fontSizeStyle,
  colorStyle,
  whiteSpaceStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import { computed, PropType } from "vue";

defineOptions({
  name: ComponentName.Text,
});

const props = defineProps({
  as: {
    type: String as PropType<"p" | "span" | "label">,
    required: false,
    default: "p",
  },
  htmlFor: {
    type: String,
    required: false,
  },
  color: {
    type: String as PropType<ColorKeys>,
    required: false,
    default: "gray.900",
  },
  fontSize: {
    type: String as PropType<FontSizeKeys>,
    required: false,
    default: "md",
  },
  lineHeight: {
    type: String as PropType<FontSizeKeys>,
    required: false,
  },
  bold: {
    type: Boolean,
    required: false,
  },
  maxLines: {
    type: Number,
    required: false,
  },
  whiteSpace: {
    type: String as PropType<WhiteSpaceKeys>,
    required: false,
    default: "normal",
  },
  dummyValue: {
    type: String,
    required: false,
  },
  breakAll: {
    type: Boolean,
    required: false,
  },
  textAlign: {
    type: String as PropType<"start" | "end" | "left" | "right" | "center">,
    required: false,
    default: "start",
  },
  lineThrough: {
    type: Boolean,
    required: false,
    default: false,
  },
});

const overflowStyles = computed(() => {
  if (!props.maxLines) return {};
  return {
    overflow: "hidden",
    display: "-webkit-box",
    webkitBoxOrient: "vertical",
    WebkitLineClamp: props.maxLines,
  };
});
</script>

// packages/wiz-ui-react/src/components/base/text/components/text.tsx
import {
  ColorKeys,
  ComponentName,
  FontSizeKeys,
  WhiteSpaceKeys,
} from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/text.css";
import {
  lineHeightStyle,
  fontSizeStyle,
  colorStyle,
  whiteSpaceStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import { ReactNode, memo } from "react";

type Props = {
  as?: "p" | "span" | "label";
  htmlFor?: string;
  color?: ColorKeys;
  fontSize?: FontSizeKeys;
  lineHeight?: FontSizeKeys;
  bold?: boolean;
  maxLines?: number;
  whiteSpace?: WhiteSpaceKeys;
  dummyValue?: string;
  breakAll?: boolean;
  textAlign?: "start" | "end" | "left" | "right" | "center";
  lineThrough?: boolean;
  children?: ReactNode;
};

const _Text = ({
  as = "p",
  htmlFor,
  color = "gray.900",
  fontSize = "md",
  lineHeight,
  bold,
  maxLines,
  whiteSpace = "normal",
  dummyValue,
  breakAll,
  textAlign = "start",
  lineThrough = false,
  ...props
}: Props) => {
  const style = {
    ...(maxLines && {
      overflow: "hidden",
      display: "-webkit-box",
      webkitBoxOrient: "vertical",
      WebkitLineClamp: maxLines,
    }),
  };
  const className = clsx(
    styles.textStyle,
    styles.textFontWeightStyle[bold ? "bold" : "default"],
    styles.textAlignStyle[textAlign],
    (maxLines || breakAll) && styles.textWordBreakStyle,
    lineHeight
      ? lineHeightStyle[lineHeight]
      : styles.textDefaultLineHeightStyle,
    fontSizeStyle[fontSize],
    colorStyle[color],
    whiteSpaceStyle[whiteSpace],
    lineThrough && styles.textLineThroughStyle
  );
  const Children = () => (
    <>
      {dummyValue ? (
        <span className={styles.textDummyStyle}>{dummyValue}</span>
      ) : (
        props.children
      )}
    </>
  );
  switch (as) {
    case "p": {
      return (
        <p className={className} style={style}>
          <Children />
        </p>
      );
    }
    case "label": {
      return (
        <label htmlFor={htmlFor} className={className} style={style}>
          <Children />
        </label>
      );
    }
    case "span": {
      return (
        <span className={className} style={style}>
          <Children />
        </span>
      );
    }
  }
};

_Text.displayName = ComponentName.Text;

export const WizText = memo(_Text);
