// packages/wiz-ui/src/components/custom/schedule/components/card.vue
<template>
  <div
    :class="[styles.card[variant]]"
    :style="{ gridRow, gridColumn }"
    v-show="show"
  >
    {{ displayText }}
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/customs/schedule.css";
import { PropType, computed } from "vue";

import { ScheduleCardVariant } from "../types";

const props = defineProps({
  variant: {
    type: String as PropType<ScheduleCardVariant>,
    default: "primary",
    required: false,
  },
  text: {
    type: String,
    required: true,
  },
  gridRow: {
    type: String,
    required: true,
  },
  gridColumn: {
    type: String,
    required: true,
  },
  show: {
    type: Boolean,
    required: false,
    default: true,
  },
});

defineOptions({
  name: ComponentName.ScheduleCard,
});

const displayText = computed(() => {
  const [start, end] = props.gridRow
    .split("/")
    .map((x) => x.trim())
    .map(Number);
  return end - start > 2 ? props.text : "";
});
</script>

// packages/wiz-ui-react/src/components/custom/schedule/components/card.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/customs/schedule.css";
import { clsx } from "clsx";

import { ScheduleCardVariant } from "../types";

interface Props {
  id: string;
  variant?: ScheduleCardVariant;
  text: string;
  gridRow: string;
  gridColumn: string;
  show?: boolean;
  onScheduleClick?: (id: string) => void;
}

export const WizScheduleCard = ({
  id,
  variant = "primary",
  text,
  gridRow,
  gridColumn,
  show = true,
  onScheduleClick,
}: Props) => {
  const displayText = () => {
    const [start, end] = gridRow
      .split("/")
      .map((x) => x.trim())
      .map(Number);
    return end - start > 2 ? text : "";
  };

  if (!onScheduleClick) {
    return (
      <div
        className={styles.card[variant]}
        style={{ gridRow, gridColumn }}
        hidden={!show}
      >
        {displayText()}
      </div>
    );
  }

  return (
    <button
      type="button"
      className={clsx(styles.card[variant], styles.buttonCard)}
      style={{ gridRow, gridColumn }}
      hidden={!show}
      onClick={() => onScheduleClick(id)}
    >
      {displayText()}
    </button>
  );
};

WizScheduleCard.displayName = ComponentName.ScheduleCard;
