// packages/wiz-ui-next/src/components/base/information-panel/information-panel.vue
<template>
  <div
    :class="[informationPanelStyle, border && informationPanelBorderStyle]"
    :style="{ width }"
    v-show="visible"
  >
    <WizVStack gap="xs">
      <div
        v-for="message in messages"
        :key="message.text"
        :class="[informationPanelFontStyle[message.type]]"
      >
        {{ message.text }}
      </div>
    </WizVStack>
    <div :class="[informationPanelIconStyle]">
      <WizVStack align="center">
        <WizIconButton variant="transparent" :icon="WizIClose" @click="close" />
      </WizVStack>
    </div>
  </div>
</template>
<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  informationPanelStyle,
  informationPanelBorderStyle,
  informationPanelFontStyle,
  informationPanelIconStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/information-panel.css";
import { PropType, computed } from "vue";

import { WizIconButton, WizIClose } from "@/components";

import { WizVStack } from "../stack";

type messageType = {
  text: string;
  type: "default" | "error";
};

defineOptions({
  name: ComponentName.InformationPanel,
});

const props = defineProps({
  modelValue: {
    type: Boolean,
    required: true,
  },
  messages: {
    type: Array as PropType<messageType[]>,
    required: true,
  },
  width: {
    type: String,
    required: false,
  },
  border: {
    type: Boolean,
    required: false,
    default: false,
  },
});

interface Emit {
  (e: "update:modelValue", value: boolean): void;
}

const emit = defineEmits<Emit>();

const visible = computed({
  get: () => props.modelValue,
  set: (value: boolean) => emit("update:modelValue", value),
});

const close = () => {
  visible.value = false;
};
</script>

// packages/wiz-ui-react/src/components/base/information-panel/components/information-panel.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/information-panel.css";
import clsx from "clsx";
import { FC } from "react";

import { WizIClose, WizIconButton, WizVStack } from "@/components";

type Message = {
  text: string;
  type: "default" | "error";
};

type Props = {
  messages: Message[];
  width?: string;
  border?: boolean;
  onClose: () => void;
};

const InformationPanel: FC<Props> = ({
  messages,
  width,
  border = false,
  onClose,
}) => {
  return (
    <div
      className={clsx(
        styles.informationPanelStyle,
        border && styles.informationPanelBorderStyle
      )}
      style={{ width }}
    >
      <WizVStack gap="xs">
        {messages.map((message, i) => (
          <div
            key={i}
            className={styles.informationPanelFontStyle[message.type]}
          >
            {message.text}
          </div>
        ))}
      </WizVStack>
      <div className={styles.informationPanelIconStyle}>
        <WizVStack align="center">
          <WizIconButton
            variant="transparent"
            icon={WizIClose}
            onClick={onClose}
          />
        </WizVStack>
      </div>
    </div>
  );
};

InformationPanel.displayName = ComponentName.InformationPanel;

export const WizInformationPanel = InformationPanel;
