// packages/wiz-ui-react/src/components/base/progress-bar/components/progress-point.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/progress-bar.css";
import clsx from "clsx";
import { FC } from "react";

import type { ProgressStatus } from "../types";

type Props = {
  status: ProgressStatus;
  value?: number;
};

const ProgressPoint: FC<Props> = ({ status, value }) => {
  return (
    <span
      className={clsx([
        [
          styles.progressPointStyle,
          status !== "none" && styles.progressPointVariantStyle[status],
        ],
      ])}
    >
      <span
        className={clsx([
          styles.progressPointValueStyle,
          styles.progressPointValueColorStyle[
            status === "active" ? "active" : "inactive"
          ],
        ])}
      >
        {value}
      </span>
    </span>
  );
};

ProgressPoint.displayName = ComponentName.ProgressPoint;

export const WizProgressPoint = ProgressPoint;

// packages/wiz-ui-next/src/components/base/progress-bar/progress-point.vue
<template>
  <span
    :class="[
      styles.progressPointStyle,
      status !== 'none' && styles.progressPointVariantStyle[status],
    ]"
  >
    <span
      :class="[
        styles.progressPointValueStyle,
        styles.progressPointValueColorStyle[
          status === 'active' ? 'active' : 'inactive'
        ],
      ]"
    >
      {{ value }}
    </span>
  </span>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/progress-bar.css";
import { PropType } from "vue";

import type { ProgressStatus } from "./types";

defineOptions({
  name: ComponentName.ProgressPoint,
});

defineProps({
  status: {
    type: String as PropType<ProgressStatus>,
    required: true,
  },
  value: {
    type: Number,
    required: false,
  },
});
</script>
