// packages/wiz-ui-react/src/components/base/inputs/toggle-switch/components/toggle-switch.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/toggle-switch-input.css";
import clsx from "clsx";

type Props = {
  value: boolean;
  ariaLabel: string;
  setValue: (value: boolean) => void;
};

const ToggleSwitch = ({ value, ariaLabel, ...props }: Props) => {
  const switchState = value ? "checked" : "default";

  return (
    <label className={styles.toggleSwitchStyle}>
      <input
        className={styles.toggleSwitchInputStyle}
        type="checkbox"
        aria-label={ariaLabel}
        onChange={(e) => props.setValue(e.target.checked)}
      />
      <span
        className={clsx(
          styles.toggleSwitchSliderStyle,
          styles.toggleSwitchColorStyle[switchState],
          value && styles.toggleSwitchSliderCheckedStyle
        )}
      />
    </label>
  );
};

ToggleSwitch.displayName = ComponentName.ToggleSwitch;

export const WizToggleSwitch = ToggleSwitch;

// packages/wiz-ui/src/components/base/inputs/toggle-switch/toggle-switch.vue
<template>
  <label :class="toggleSwitchStyle">
    <input
      :class="toggleSwitchInputStyle"
      type="checkbox"
      :aria-label="ariaLabel"
      v-model="switchValue"
    />
    <span
      :class="[
        toggleSwitchSliderStyle,
        toggleSwitchColorStyle[switchState],
        switchValue && toggleSwitchSliderCheckedStyle,
      ]"
    ></span>
  </label>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  toggleSwitchStyle,
  toggleSwitchInputStyle,
  toggleSwitchSliderStyle,
  toggleSwitchColorStyle,
  toggleSwitchSliderCheckedStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/toggle-switch-input.css";
import { computed } from "vue";

defineOptions({
  name: ComponentName.ToggleSwitch,
});

const props = defineProps({
  value: {
    type: Boolean,
    required: true,
  },
  ariaLabel: {
    type: String,
    required: true,
  },
});

interface Emit {
  (e: "input", value: boolean): void;
}

const emit = defineEmits<Emit>();

const switchValue = computed({
  get: () => props.value,
  set: (value) => emit("input", value),
});

const switchState = computed(() => {
  return switchValue.value ? "checked" : "default";
});
</script>
