// packages/wiz-ui-react/src/components/base/dialogs/dialog/components/dialog.tsx
import { ComponentName, THEME } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/dialog.css";
import clsx from "clsx";
import { FC, ReactNode, useEffect, useMemo, useRef } from "react";
import { createPortal } from "react-dom";

import { WizCard, WizIClose, WizIconButton } from "@/components";
import { BaseProps } from "@/types";
type Props = BaseProps & {
  isOpen: boolean;
  maxWidth?: string;
  title?: ReactNode;
  footer?: ReactNode;
  children?: ReactNode;
  align?: "start" | "center" | "end";
  hideClose?: boolean;
  onClose?: () => void;
};

const Dialog: FC<Props> = ({
  className,
  style,
  isOpen,
  maxWidth = "600px",
  title,
  footer,
  children,
  align,
  hideClose,
  onClose,
}) => {
  const portalRoot = useRef<HTMLDivElement>(
    document.createElement("div")
  ).current;

  useEffect(() => {
    if (!portalRoot) {
      return;
    }
    document.body.appendChild(portalRoot);
    return () => {
      document.body.removeChild(portalRoot);
    };
  }, [portalRoot]);

  useEffect(() => {
    if (!isOpen) {
      return;
    }
    // スクロールバーが表示されている場合
    if (document.body.scrollHeight > window.innerHeight) {
      // スクロール位置を記憶して body をスクロール不可に設定
      const { scrollY } = window;
      document.body.style.top = `-${scrollY}px`;
      document.body.classList.add(styles.dialogBlockScrollStyle);

      return () => {
        // スタイルとスクロール位置を戻す
        document.body.classList.remove(styles.dialogBlockScrollStyle);
        document.body.style.top = "";
        window.scrollTo(0, scrollY);
      };
    }
  }, [isOpen]);

  const closeButton = useMemo(
    () => (
      <WizIconButton
        icon={WizIClose}
        variant="transparent"
        onClick={() => onClose?.()}
      />
    ),
    [onClose]
  );

  return createPortal(
    <div
      className={clsx(
        className,
        styles.dialogStyle,
        isOpen && styles.dialogVisibleStyle
      )}
      style={{ ...style, zIndex: THEME.zIndex.dialog }}
    >
      <div
        className={styles.dialogMaskStyle}
        onClick={(e) => {
          if (e.target === e.currentTarget) {
            onClose?.();
          }
        }}
      >
        <WizCard
          p="xl"
          maxWidth={maxWidth}
          align={align}
          mainHeaderArea={title}
          subHeaderArea={!hideClose && closeButton}
          footerArea={footer}
          role="dialog"
          aria-modal={true}
        >
          {children}
        </WizCard>
      </div>
    </div>,
    portalRoot
  );
};

Dialog.displayName = ComponentName.Dialog;

export const WizDialog = Dialog;

// packages/wiz-ui/src/components/base/dialog/dialog.vue
<template>
  <MountingPortal mountTo="body" name="dialog" append>
    <div
      :class="[dialogStyle, visible && dialogVisibleStyle]"
      :style="{ zIndex: currentZIndex }"
    >
      <div :class="dialogMaskStyle" @click.self="close">
        <WizCard :maxWidth="maxWidth" p="xl" :title="title" :align="align">
          <template #mainHeaderArea>
            <slot v-if="!title" name="title" />
          </template>
          <template v-if="!hideClose" #subHeaderArea>
            <WizIconButton
              :icon="WizIClose"
              @click="close"
              variant="transparent"
            />
          </template>
          <slot />
          <template #footer>
            <slot name="footer" />
          </template>
        </WizCard>
      </div>
    </div>
  </MountingPortal>
</template>

<script setup lang="ts">
import { THEME, ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  dialogStyle,
  dialogVisibleStyle,
  dialogMaskStyle,
  dialogBlockScrollStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/dialog.css";
import { MountingPortal } from "portal-vue";
import { computed, PropType, watch } from "vue";

import { WizIconButton } from "@/components/base/buttons";
import { WizCard } from "@/components/base/card";
import { WizIClose } from "@/components/icons";
import { useZIndex } from "@/hooks";

defineOptions({
  name: ComponentName.Dialog,
});

const props = defineProps({
  value: {
    type: Boolean,
    required: true,
  },
  title: {
    type: String,
    required: false,
  },
  maxWidth: {
    type: String,
    required: false,
    default: "600px",
  },
  align: {
    type: String as PropType<"start" | "center" | "end">,
    required: false,
  },
  hideClose: {
    type: Boolean,
    required: false,
    default: false,
  },
});

interface Emit {
  (e: "input", value: boolean): void;
}

const emit = defineEmits<Emit>();

const visible = computed({
  get: () => props.value,
  set: (value) => emit("input", value),
});

const close = () => (visible.value = false);

const { currentZIndex } = useZIndex(THEME.zIndex.dialog);

let scrollY = 0;

watch(
  () => visible.value,
  (value) => {
    if (value) {
      // スクロールバーが表示されている場合
      if (document.body.scrollHeight > window.innerHeight) {
        scrollY = window.scrollY;
        document.body.style.top = `-${scrollY}px`;
        document.body.classList.add(dialogBlockScrollStyle);
      }
    } else {
      document.body.classList.remove(dialogBlockScrollStyle);
      document.body.style.top = "";
      window.scrollTo(0, scrollY);
    }
  }
);
</script>
