// packages/wiz-ui-react/src/components/base/tag/components/tag.tsx
import {
  ComponentName,
  FontSizeKeys,
  FontWeightKeys,
  THEME,
} from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/tag.css";
import {
  fontSizeStyle,
  fontWeightStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import { ComponentProps, ForwardedRef, forwardRef } from "react";

import { TIcon, WizIcon } from "@/components";
type Props = {
  label: string;
  icon?: TIcon;
  variant?:
    | "info"
    | "red"
    | "redFill"
    | "green"
    | "yellow"
    | "blue"
    | "mono"
    | "gray"
    | "darkGray"
    | "greenFill"
    | "white";
  fontSize?: FontSizeKeys;
  fontWeight?: FontWeightKeys;
  round?: boolean;
  width?: string;
} & ComponentProps<"div">;

const Tag = forwardRef(
  (
    {
      className,
      style,
      label,
      icon,
      variant = "info",
      fontSize = "md",
      fontWeight = "normal",
      round = false,
      width,
      ...props
    }: Props,
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    return (
      <div
        ref={ref}
        className={clsx(
          className,
          styles.tagStyle,
          styles.tagColorStyle[variant],
          fontSizeStyle[fontSize],
          fontWeightStyle[fontWeight]
        )}
        style={{
          ...style,
          width: width || "max-content",
          borderRadius: round ? THEME.spacing.xl2 : THEME.spacing.xs2,
        }}
        {...props}
      >
        {icon && (
          <WizIcon
            icon={icon}
            color={styles.tagIconColorStyle[variant]}
            size={styles.tagIconSize[fontSize]}
          />
        )}
        {label}
      </div>
    );
  }
);

Tag.displayName = ComponentName.Tag;

export const WizTag = Tag;

// packages/wiz-ui-next/src/components/base/tag/tag.vue
<template>
  <span
    :class="[
      tagStyle,
      tagColorStyle[variant],
      fontSizeStyle[fontSize],
      fontWeightStyle[fontWeight],
    ]"
    :style="{
      width: width || 'max-content',
      borderRadius: round ? THEME.spacing.xl2 : THEME.spacing.xs2,
    }"
  >
    <WizIcon
      v-if="icon"
      :icon="icon"
      :color="tagIconColorStyle[variant]"
      :size="tagIconSize[fontSize]"
    />
    {{ label }}
  </span>
</template>

<script setup lang="ts">
import {
  ComponentName,
  FontSizeKeys,
  FontWeightKeys,
  THEME,
} from "@wizleap-inc/wiz-ui-constants";
import {
  tagColorStyle,
  tagIconColorStyle,
  tagStyle,
  tagIconSize,
} from "@wizleap-inc/wiz-ui-styles/bases/tag.css";
import {
  fontSizeStyle,
  fontWeightStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import { PropType } from "vue";

import { WizIcon } from "@/components/base";
import type { TIcon } from "@/components/icons";

defineOptions({
  name: ComponentName.Tag,
});

defineProps({
  label: {
    type: String,
    required: true,
  },
  icon: {
    type: Object as PropType<TIcon>,
    required: false,
  },
  variant: {
    type: String as PropType<
      | "info"
      | "red"
      | "redFill"
      | "green"
      | "yellow"
      | "yellowFill"
      | "blue"
      | "mono"
      | "gray"
      | "darkGray"
      | "greenFill"
      | "white"
    >,
    required: false,
    default: "info",
  },
  fontSize: {
    type: String as PropType<FontSizeKeys>,
    required: false,
    default: "md",
  },
  fontWeight: {
    type: String as PropType<FontWeightKeys>,
    required: false,
    default: "normal",
  },
  round: {
    type: Boolean,
    required: false,
    default: false,
  },
  width: {
    type: String,
    required: false,
  },
});
</script>
