// packages/wiz-ui-react/src/components/base/header/components/header.tsx
import {
  ComponentName,
  SpacingKeys,
  THEME,
} from "@wizleap-inc/wiz-ui-constants";
import {
  headerStyle,
  headerStickyStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/header.css";
import clsx from "clsx";
import { FC, ReactNode } from "react";

import { WizHStack, WizIMenu } from "@/components";

import { WizIconButton } from "../../buttons/icon";

interface Props {
  gapLeft?: SpacingKeys;
  gapRight?: SpacingKeys;
  sticky?: boolean;
  leftContent?: ReactNode;
  rightContent?: ReactNode;
  onToggle: () => void;
}

const Header: FC<Props> = ({
  gapLeft,
  gapRight,
  sticky,
  leftContent,
  rightContent,
  onToggle,
}) => {
  return (
    <div
      className={clsx(headerStyle, sticky && headerStickyStyle)}
      style={{ zIndex: THEME.zIndex.floating }}
    >
      <WizHStack align="center" justify="between" height="100%">
        <WizHStack align="center" gap={gapLeft} pl="lg">
          <WizIconButton
            icon={WizIMenu}
            size="lg"
            variant="transparent"
            onClick={onToggle}
          />
          {leftContent}
        </WizHStack>
        <WizHStack align="center" gap={gapRight} pr="lg">
          {rightContent}
        </WizHStack>
      </WizHStack>
    </div>
  );
};

Header.displayName = ComponentName.Header;

export const WizHeader = Header;

// packages/wiz-ui/src/components/base/header/header.vue
<template>
  <div
    :class="[styles.headerStyle, sticky && styles.headerStickyStyle]"
    :style="{ zIndex: currentZIndex }"
  >
    <WizHStack align="center" justify="between" height="100%">
      <WizHStack align="center" :gap="gapLeft" pl="lg">
        <WizIconButton
          :icon="WizIMenu"
          size="lg"
          variant="transparent"
          @click="toggleMenuOpen"
        />
        <slot name="left" />
      </WizHStack>
      <WizHStack align="center" :gap="gapRight" pr="lg">
        <slot name="right" />
      </WizHStack>
    </WizHStack>
  </div>
</template>

<script setup lang="ts">
import {
  ComponentName,
  SpacingKeys,
  THEME,
} from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/header.css";
import { PropType } from "vue";

import { WizHStack, WizIconButton, WizIMenu } from "@/components";
import { useZIndex } from "@/hooks";
import { globalInject, globalKey } from "@/hooks/use-global-provider";

defineOptions({
  name: ComponentName.Header,
});

defineProps({
  gapLeft: {
    type: String as PropType<SpacingKeys>,
    required: false,
  },
  gapRight: {
    type: String as PropType<SpacingKeys>,
    required: false,
  },
  sticky: {
    type: Boolean,
    required: false,
  },
});

const { isMenuOpen, setIsMenuOpen } = globalInject(globalKey);
const toggleMenuOpen = () => setIsMenuOpen(!isMenuOpen.value);
const { currentZIndex } = useZIndex(THEME.zIndex.floating);
</script>
