// packages/wiz-ui-react/src/components/custom/timeline/components/timeline-item.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/customs/timeline.css";
import clsx from "clsx";
import { FC, ReactNode, useContext, useMemo } from "react";

import { WizIcon, WizTag } from "../../../base";
import { WizICalendar } from "../../../icons";

import { TimelineContext } from "./use-timeline";

type TimelineVariant = "success" | "failure";

interface TimelineItemProps {
  variant?: TimelineVariant;
  title: string;
  tag?: string;
  annotation?: string;
  children?: ReactNode;
  footer?: ReactNode;
}

const TimelineItem: FC<TimelineItemProps> = ({
  variant = "success",
  title,
  tag,
  annotation,
  children,
  footer,
}) => {
  const ctx = useContext(TimelineContext);
  if (!ctx) {
    throw new Error(
      "TimelineItemはTimelineの子コンポーネントとして使用してください。"
    );
  }

  const { bp } = ctx;
  const size = useMemo(() => (bp === "sm" ? "sm" : "lg"), [bp]);
  const iconSize = useMemo(() => (bp === "sm" ? "md" : "xl2"), [bp]);
  const isTitleEscape = useMemo(() => bp === "sm" && tag, [bp, tag]);

  return (
    <div
      className={clsx(
        styles.container,
        styles.timelineItemVariant[size],
        styles.TIMELINE_ITEM_IDENTIFIER_CLASS
      )}
    >
      <div className={clsx(styles.icon, styles.iconVariant[variant])}>
        <WizIcon size={iconSize} icon={WizICalendar} color="white.800" />
      </div>
      <div className={styles.card}>
        <div className={styles.contents}>
          <div className={styles.header}>
            <div className={styles.headerRow}>
              <span className={styles.titleContainer}>
                {tag && (
                  <WizTag
                    fontSize="xs"
                    label={tag}
                    fontWeight="bold"
                    variant={variant === "success" ? "green" : "red"}
                  />
                )}
                {!isTitleEscape && (
                  <span className={styles.title}>{title}</span>
                )}
              </span>
              <span className={styles.annotation}>{annotation}</span>
            </div>
            {isTitleEscape && <span className={styles.title}>{title}</span>}
          </div>
          {children && <div className={styles.body}>{children}</div>}
        </div>
        {footer}
      </div>
    </div>
  );
};

TimelineItem.displayName = ComponentName.TimelineItem;

export const WizTimelineItem = TimelineItem;

// packages/wiz-ui/src/components/custom/timeline/timeline-item.vue
<template>
  <div
    :class="[
      styles.container,
      styles.timelineItemVariant[size],
      styles.TIMELINE_ITEM_IDENTIFIER_CLASS,
    ]"
  >
    <div :class="[styles.icon, styles.iconVariant[variant]]">
      <WizIcon :size="iconSize" :icon="WizICalendar" color="white.800" />
    </div>
    <div :class="styles.card">
      <div :class="styles.contents">
        <div :class="styles.header">
          <div :class="styles.headerRow">
            <span :class="styles.titleContainer">
              <WizTag
                v-if="tag"
                fontSize="xs"
                :label="tag"
                fontWeight="bold"
                :variant="variant === 'success' ? 'green' : 'red'"
              />
              <span v-if="!isTitleEscape" :class="styles.title">
                {{ title }}
              </span>
            </span>
            <span :class="styles.annotation">
              {{ annotation }}
            </span>
          </div>
          <span v-if="isTitleEscape" :class="styles.title">
            {{ title }}
          </span>
        </div>
        <div :class="styles.body" v-if="slot.default">
          <slot />
        </div>
      </div>
      <slot name="footer" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/customs/timeline.css";
import { PropType, computed, useSlots, inject } from "vue";

import { WizIcon, WizTag } from "@/components/base";
import { WizICalendar } from "@/components/icons";

import { TIMELINE_KEY } from "./use-timeline";

defineOptions({
  name: ComponentName.TimelineItem,
});

type TimelineVariant = "success" | "failure";

const props = defineProps({
  variant: {
    type: String as PropType<TimelineVariant>,
    required: false,
    default: "success",
  },
  title: {
    type: String,
    required: true,
  },
  tag: {
    type: String,
    required: false,
  },
  annotation: {
    type: String,
    required: false,
  },
});

const slot = useSlots();

const injected = inject(TIMELINE_KEY);

if (injected === undefined) {
  throw new Error(
    "TimelineItemはTimelineの子コンポーネントとして使用してください。"
  );
}

const size = computed(() => (injected.bp.value === "sm" ? "sm" : "lg"));
const iconSize = computed(() => (injected.bp.value === "sm" ? "md" : "xl2"));
const isTitleEscape = computed(() => injected.bp.value === "sm" && props.tag);
</script>
