// packages/wiz-ui-react/src/components/custom/timeline/components/timeline.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/customs/timeline.css";

import { WizVStack } from "@/components/base";

import { TimelineContext } from "./use-timeline";

import type { FC, ReactNode } from "react";

interface TimelineProps {
  device?: "mobile" | "pc";
  children?: ReactNode;
}

const Timeline: FC<TimelineProps> = ({ device = "pc", children }) => {
  return (
    <TimelineContext.Provider value={{ device }}>
      <WizVStack gap={styles.TIMELINES_GAP}>{children}</WizVStack>
    </TimelineContext.Provider>
  );
};

Timeline.displayName = ComponentName.Timeline;

export const WizTimeline = Timeline;

// packages/wiz-ui/src/components/custom/timeline/timeline.vue
<template>
  <WizVStack :gap="styles.TIMELINES_GAP">
    <slot />
  </WizVStack>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/customs/timeline.css";
import { PropType, provide, toRef } from "vue";

import { WizVStack } from "@/components/base";

import { TIMELINE_KEY } from "./use-timeline";

defineOptions({
  name: ComponentName.Timeline,
});

const props = defineProps({
  device: {
    type: String as PropType<"mobile" | "pc">,
    required: true,
  },
});

const device = toRef(props, "device");

provide(TIMELINE_KEY, { device });
</script>
