// packages/wiz-ui-react/src/components/custom/chat/components/chat-card.tsx
import { ComponentName, THEME } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/customs/chat-card.css";
import { formatDateToMonthDayWeek } from "@wizleap-inc/wiz-ui-utils";
import {
  ComponentProps,
  FC,
  Fragment,
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from "react";

import {
  WizBox,
  WizCard,
  WizDivider,
  WizHStack,
  WizIExpandLess,
  WizIExpandMore,
  WizIcon,
  WizSelectBox,
  WizTag,
  WizText,
  WizVStack,
} from "@/components";

import { DisplayMessage, Message } from "./types";

import { WizChatItem, WizChatForm } from ".";

const TOGGLE_ANIMATION_DURATION = 300;

type Props = {
  textValue: string;
  username: string;
  placeholder?: string;
  messages: Message[];
  isOpen?: boolean;
  haveNewMessage?: boolean;
  formRows?: number;
  typingUsername?: string;
  status?: number | null;
  statusOptions?: ComponentProps<typeof WizSelectBox>["options"];
  statusPlaceholder?: string;
  onChangeStatus?: (status: number | null) => void;
  onChangeTextValue: (value: string) => void;
  onSubmit: () => void;
  onToggleOpen: () => void;
};

const ChatCard: FC<Props> = ({
  textValue,
  username,
  placeholder,
  messages,
  isOpen = false,
  haveNewMessage,
  formRows,
  typingUsername,
  status,
  statusOptions,
  statusPlaceholder,
  onChangeStatus,
  onChangeTextValue,
  onSubmit,
  onToggleOpen,
}) => {
  const wrapperBoxRef = useRef<HTMLDivElement>(null);
  const listBoxRef = useRef<HTMLDivElement>(null);
  const [wrapperHeight, setWrapperHeight] = useState(0);

  const displayMessages = useMemo(() => {
    const displayMessages: DisplayMessage[] = [];
    messages.forEach((message) => {
      const date = new Date(message.time);
      const displayMessage = displayMessages.find(
        (displayMessage) =>
          displayMessage.date.getFullYear() === date.getFullYear() &&
          displayMessage.date.getMonth() === date.getMonth() &&
          displayMessage.date.getDate() === date.getDate()
      );
      if (displayMessage) {
        displayMessage.contents.push(message);
      } else {
        displayMessages.push({
          date,
          contents: [message],
        });
      }
    });
    return displayMessages;
  }, [messages]);

  const [isToggleAnimating, setIsToggleAnimating] = useState(false);
  const handleClickToggleButton = useCallback(() => {
    setIsToggleAnimating(true);
    setTimeout(() => setIsToggleAnimating(false), TOGGLE_ANIMATION_DURATION);
    onToggleOpen();
  }, [onToggleOpen]);

  useLayoutEffect(() => {
    const wrapperBox = wrapperBoxRef.current;
    if (!wrapperBox) {
      return;
    }
    // ちらつき防止の為最初に一回計算する
    setWrapperHeight(wrapperBox.clientHeight);
    const wrapperObserver = new ResizeObserver(() => {
      setWrapperHeight(wrapperBox.clientHeight);
    });
    wrapperObserver.observe(wrapperBox);
    return () => {
      wrapperObserver.disconnect();
    };
  }, []);

  useEffect(() => {
    // リスト下部までスクロール
    const listBox = listBoxRef.current;
    if (listBox && isOpen) {
      listBox.scrollTo(0, listBox.scrollHeight);
    }
  }, [isOpen, messages]);

  return (
    <WizBox
      ref={wrapperBoxRef}
      position="fixed"
      right="1.5rem"
      bottom={
        isOpen
          ? "0"
          : `calc(${THEME.fontSize.xl2} + ${THEME.spacing.md} * 2 - ${wrapperHeight}px)`
      }
      transition={
        isToggleAnimating
          ? `bottom ${TOGGLE_ANIMATION_DURATION}ms ease-in-out`
          : undefined
      }
      width="20rem"
      zIndex="floating"
    >
      <WizCard
        shadow
        align="stretch"
        mainHeaderArea={
          <WizHStack align="center" gap="xs2">
            <WizText color="gray.700" as="span" bold>
              {username}
            </WizText>
            {haveNewMessage && (
              <WizBox
                width={THEME.fontSize.md}
                height={THEME.fontSize.md}
                bgColor="red.800"
                round="max"
              />
            )}
          </WizHStack>
        }
        subHeaderArea={
          <WizIcon
            size="xl2"
            color="gray.500"
            icon={isOpen ? WizIExpandMore : WizIExpandLess}
          />
        }
        footerArea={
          <WizVStack width="100%" justify="end" gap="xs">
            <WizChatForm
              value={textValue}
              onChange={onChangeTextValue}
              onSubmit={onSubmit}
              placeholder={placeholder}
              formRows={formRows}
            />
            {status !== undefined && statusOptions !== undefined && (
              <WizHStack wrap={false}>
                <WizSelectBox
                  options={statusOptions}
                  value={status}
                  onChange={(selectedValue) => onChangeStatus?.(selectedValue)}
                  placeholder={statusPlaceholder}
                  expand
                />
                <div
                  style={{
                    width: THEME.spacing.xl4,
                    flexShrink: 0,
                  }}
                />
              </WizHStack>
            )}
            {typingUsername && (
              <WizText color="gray.600" as="p" fontSize="xs2">
                <WizText as="span" bold fontSize="xs2" color="gray.700">
                  {typingUsername}
                </WizText>
                さんが入力しています...
              </WizText>
            )}
          </WizVStack>
        }
      >
        <WizDivider />
        <WizBox overflowY="scroll" ref={listBoxRef}>
          <WizVStack gap="xs" py="xs" height="320px" wrap={false}>
            {displayMessages.map(({ date, contents }, i) => {
              const messagesKey = `${date.toDateString()}-${i}`;
              return (
                <Fragment key={messagesKey}>
                  <WizHStack justify="center">
                    <WizTag
                      label={formatDateToMonthDayWeek(date)}
                      variant="mono"
                      fontSize="xs2"
                    />
                  </WizHStack>
                  {contents.map((content, j) => (
                    <WizChatItem
                      key={`${messagesKey}-${i}-${j}`}
                      content={content}
                      maxChatItemWidth="192px"
                    />
                  ))}
                </Fragment>
              );
            })}
          </WizVStack>
        </WizBox>
      </WizCard>
      <button
        className={styles.chatCardOpenButtonStyle}
        onClick={handleClickToggleButton}
      />
    </WizBox>
  );
};

ChatCard.displayName = ComponentName.ChatCard;

export const WizChatCard = ChatCard;

// packages/wiz-ui-next/src/components/custom/chat/card/chat-card.vue
<template>
  <WizBox
    position="fixed"
    :bottom="
      isOpen
        ? '0'
        : `calc(${THEME.fontSize.xl2} + ${THEME.spacing.md} * 2 - ${floatChatCardHeight}px)`
    "
    right="1.5rem"
    width="20rem"
    :transition="`bottom ${canAnimate ? '0.3s' : '0s'} ease-in-out`"
    ref="floatChatCardRef"
    zIndex="floating"
  >
    <WizCard shadow align="stretch">
      <template #mainHeaderArea>
        <WizHStack align="center" gap="xs2">
          <WizText color="gray.700" as="span" bold>
            {{ username }}
          </WizText>
          <WizBox
            v-if="haveNewMessage"
            :width="THEME.fontSize.md"
            :height="THEME.fontSize.md"
            bgColor="red.800"
            round="max"
          />
        </WizHStack>
      </template>
      <template #subHeaderArea>
        <WizIcon
          size="xl2"
          color="gray.500"
          :icon="isOpen ? WizIExpandMore : WizIExpandLess"
        />
      </template>
      <WizDivider />
      <WizBox overflowY="scroll" ref="chatListRef">
        <WizVStack gap="xs" py="xs" height="320px">
          <template
            v-for="messages in displayMessages"
            :key="messages.date.toDateString()"
          >
            <WizHStack justify="center">
              <WizTag
                :label="formatDateToMonthDayWeek(messages.date)"
                variant="mono"
                fontSize="xs2"
              />
            </WizHStack>
            <WizChatItem
              v-for="(item, i) in messages.contents"
              :key="messages.date.toDateString() + i"
              :content="item"
              maxChatItemWidth="192px"
            />
          </template>
        </WizVStack>
      </WizBox>
      <template #footer>
        <WizVStack width="100%" justify="end" gap="xs">
          <WizChatForm
            v-model="textValue"
            @submit="onSubmit"
            :placeholder="placeholder"
            :formRows="formRows"
          />
          <WizHStack v-if="status !== undefined && statusOptions !== undefined">
            <WizSelectBox
              :options="statusOptions"
              v-model="statusValue"
              :placeholder="statusPlaceholder"
              expand
            />
            <div
              :style="{
                width: THEME.spacing.xl4,
                flexShrink: 0,
              }"
            />
          </WizHStack>
          <WizText v-if="typingUsername" color="gray.600" as="p" fontSize="xs2">
            <WizText as="span" bold fontSize="xs2" color="gray.700">
              {{ typingUsername }}
            </WizText>
            さんが入力しています...
          </WizText>
        </WizVStack>
      </template>
    </WizCard>
    <button
      type="button"
      :class="chatCardOpenButtonStyle"
      @click="toggleDisplay"
      :aria-label="ARIA_LABELS.CHAT_CARD.EXPAND"
    />
  </WizBox>
</template>

<script setup lang="ts" generic="T">
import {
  ARIA_LABELS,
  ComponentName,
  THEME,
} from "@wizleap-inc/wiz-ui-constants";
import { chatCardOpenButtonStyle } from "@wizleap-inc/wiz-ui-styles/customs/chat-card.css";
import { formatDateToMonthDayWeek } from "@wizleap-inc/wiz-ui-utils";
import { computed, nextTick, onMounted, ref, watch } from "vue";

import {
  WizBox,
  WizCard,
  WizChatForm,
  WizChatItem,
  WizDivider,
  WizHStack,
  WizIExpandLess,
  WizIExpandMore,
  WizIcon,
  WizSelectBox,
  WizTag,
  WizText,
  WizVStack,
} from "@/components";
import { SelectBoxOption } from "@/components/base/inputs/selectbox/types";

import { DisplayMessage, Message } from "..";

defineOptions({
  name: ComponentName.ChatCard,
});

type Props<T> = {
  modelValue: string;
  username: string;
  placeholder?: string;
  messages: Message[];
  isOpen?: boolean;
  haveNewMessage?: boolean;
  formRows?: number;
  typingUsername?: string;
  status?: T;
  statusOptions?: SelectBoxOption<T>[];
  statusPlaceholder?: string;
};

const props = withDefaults(defineProps<Props<T>>(), {
  placeholder: "",
  isOpen: false,
});
const emits = defineEmits<{
  "update:modelValue": [value: string];
  submit: [];
  toggleDisplay: [];
  "update:status": [value: T];
}>();

const canAnimate = ref(false);

const floatChatCardHeight = ref(0);
const floatChatCardRef = ref<InstanceType<typeof WizBox>>();
const chatListRef = ref<InstanceType<typeof WizVStack>>();

const updateFloatChatCardHeight = () => {
  if (floatChatCardRef.value) {
    floatChatCardHeight.value = floatChatCardRef.value.$el.clientHeight;
  }
};

onMounted(() => {
  updateFloatChatCardHeight();
  if (chatListRef.value) {
    chatListRef.value.$el.scrollTo(0, chatListRef.value.$el.scrollHeight);
  }
});

const displayMessages = computed(() => {
  const messages = props.messages;
  const displayMessages: DisplayMessage[] = [];
  messages.forEach((message) => {
    const date = new Date(message.time);
    const displayMessage = displayMessages.find(
      (displayMessage) =>
        displayMessage.date.getFullYear() === date.getFullYear() &&
        displayMessage.date.getMonth() === date.getMonth() &&
        displayMessage.date.getDate() === date.getDate()
    );
    if (displayMessage) {
      displayMessage.contents.push(message);
    } else {
      displayMessages.push({
        date,
        contents: [message],
      });
    }
  });
  return displayMessages;
});

watch(props.messages, () => {
  nextTick(() => {
    if (chatListRef.value) {
      chatListRef.value.$el.scrollTo(0, chatListRef.value.$el.scrollHeight);
    }
  });
});
watch(props, () => {
  nextTick(updateFloatChatCardHeight);
});

const textValue = computed({
  get: () => props.modelValue,
  set: (value) => emits("update:modelValue", value),
});

const statusValue = computed({
  get: () => props.status,
  set: (value) => value && emits("update:status", value),
});

const onSubmit = () => emits("submit");

const toggleDisplay = () => {
  canAnimate.value = true;
  emits("toggleDisplay");
  nextTick(() => (canAnimate.value = false));
};
</script>
