// packages/wiz-ui-react/src/components/base/navigation/components/item.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  navigationItemStyle,
  navigationItemActiveStyle,
  navigationItemIconStyle,
  navigationItemIconActiveStyle,
  navigationItemTextStyle,
  navigationItemTextActiveStyle,
  navigationItemDisabledStyle,
  navigationItemIconDisabledStyle,
  navigationPopupContainerStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/navigation.css";
import clsx from "clsx";
import { FC, useCallback, useRef } from "react";

import { TIcon, WizPopup, WizPopupButtonGroup, WizTooltip } from "@/components";

import { ButtonGroupItem } from "../../popup-button-group/types";

interface Props {
  icon: TIcon;
  label: string;
  active: boolean;
  href: string;
  disabled?: boolean;
  tooltipText?: string;
  lockingPopup?: boolean;
  buttons?: ButtonGroupItem[];
  isOpen?: boolean;
  onSetOpen: (isOpen: boolean) => void;
  onSetLockingPopup: (lock: boolean) => void;
}

const Item: FC<Props> = ({
  icon: Icon,
  label,
  active,
  href,
  disabled = false,
  tooltipText = null,
  lockingPopup = true,
  buttons,
  isOpen = false,
  onSetOpen,
  onSetLockingPopup,
}) => {
  const navItemRef = useRef<HTMLDivElement>(null);

  const existPopup = buttons && buttons.length > 0;

  const handleClick = () => {
    onSetOpen(true);
    if (existPopup) onSetLockingPopup(true);
  };

  const handleMouseEnter = () => {
    if (!lockingPopup) onSetOpen(true);
  };

  const handleMouseLeave = () => {
    if (!lockingPopup) onSetOpen(false);
  };

  const handleClosePopup = useCallback(() => {
    onSetOpen(false);
    onSetLockingPopup(false);
  }, [onSetOpen, onSetLockingPopup]);

  const handleMouseEnterToPopup = () => {
    if (!lockingPopup) onSetOpen(true);
  };

  const handleMouseLeaveFromPopup = useCallback(() => {
    if (!lockingPopup) onSetOpen(false);
  }, [lockingPopup, onSetOpen]);

  const Body: FC = () => (
    <>
      <div
        ref={navItemRef}
        onClick={handleClick}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        style={{ display: "inline-block" }}
      >
        <a
          href={disabled ? undefined : href}
          target={disabled ? undefined : "_blank"}
          rel={disabled ? undefined : "noreferrer"}
          className={clsx(
            navigationItemStyle,
            disabled
              ? navigationItemDisabledStyle
              : active && navigationItemActiveStyle
          )}
        >
          <div
            className={clsx(
              navigationItemIconStyle,
              disabled
                ? navigationItemIconDisabledStyle
                : active && navigationItemIconActiveStyle
            )}
            style={{ display: "flex", alignItems: "center" }}
          >
            <Icon />
          </div>
          <div
            className={clsx(
              navigationItemTextStyle,
              !disabled && active && navigationItemTextActiveStyle
            )}
          >
            {label}
          </div>
        </a>
      </div>
      {existPopup && (
        <div>
          <WizPopup
            anchorElement={navItemRef}
            isOpen={isOpen}
            onClose={handleClosePopup}
            onMouseLeave={handleMouseLeaveFromPopup}
            direction="rightTop"
            layer="popover"
            isDirectionFixed
          >
            <div
              onMouseEnter={handleMouseEnterToPopup}
              className={navigationPopupContainerStyle}
            >
              <WizPopupButtonGroup
                options={buttons}
                p="xs"
                borderRadius="xs2"
                disabled={disabled}
              />
            </div>
          </WizPopup>
        </div>
      )}
    </>
  );

  if (!tooltipText) return <Body />;

  return (
    <WizTooltip content={tooltipText && <div>{tooltipText}</div>}>
      <Body />
    </WizTooltip>
  );
};

Item.displayName = ComponentName.NavigationItem;

export const WizNavigationItem = Item;

// packages/wiz-ui/src/components/base/navigation/item.vue
<template>
  <WizTooltip :expand="true">
    <WizPopupContainer :expand="true">
      <div
        ref="navItemRef"
        @click="navItemOnClick"
        @mouseenter="navItemMouseEnter"
        @mouseleave="navItemMouseLeave"
      >
        <component
          :is="disabled || isExternalLink ? 'a' : 'router-link'"
          :to="!disabled && !isExternalLink ? to : undefined"
          :href="!disabled && isExternalLink ? to : undefined"
          :target="!disabled && isExternalLink ? '_blank' : undefined"
          :class="[
            navigationItemStyle,
            disabled
              ? navigationItemDisabledStyle
              : active && navigationItemActiveStyle,
          ]"
        >
          <component
            :is="icon"
            :class="[
              navigationItemIconStyle,
              disabled
                ? navigationItemIconDisabledStyle
                : active && navigationItemIconActiveStyle,
            ]"
          />
          <div
            :class="[
              navigationItemTextStyle,
              !disabled && active && navigationItemTextActiveStyle,
            ]"
          >
            {{ label }}
          </div>
        </component>
      </div>
      <div v-if="existPopup">
        <WizPopup
          :isOpen="isOpen"
          @onClose="popupOnClose"
          @mouseLeave="popupMouseLeave"
          direction="rt"
          layer="popover"
          :isDirectionFixed="isDirectionFixed"
        >
          <div @mouseenter="popupMouseEnter">
            <WizPopupButtonGroup
              :options="buttons ?? []"
              :class="navigationPopupContainerStyle"
              p="xs"
              borderRadius="xs2"
              :disabled="disabled"
            />
          </div>
        </WizPopup>
      </div>
    </WizPopupContainer>
    <template #content v-if="tooltipText">
      {{ tooltipText }}
    </template>
  </WizTooltip>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  navigationItemStyle,
  navigationItemActiveStyle,
  navigationItemIconStyle,
  navigationItemIconActiveStyle,
  navigationItemTextStyle,
  navigationItemTextActiveStyle,
  navigationItemDisabledStyle,
  navigationItemIconDisabledStyle,
  navigationPopupContainerStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/navigation.css";
import { computed, PropType, ref } from "vue";
import { RouterLinkProps } from "vue-router/types/router";

import {
  WizPopupContainer,
  WizPopup,
  WizPopupButtonGroup,
  WizTooltip,
} from "@/components";
import type { TIcon } from "@/components/icons";

import { ButtonGroupItem } from "../popup-button-group/types";
defineOptions({
  name: ComponentName.NavigationItem,
});

const props = defineProps({
  icon: {
    type: Object as PropType<TIcon>,
    required: true,
  },
  label: {
    type: String,
    required: true,
  },
  active: {
    type: Boolean,
    required: true,
  },
  to: {
    type: [Object, String] as PropType<RouterLinkProps["to"]>,
    required: true,
  },
  disabled: {
    type: Boolean,
    required: false,
    default: false,
  },
  tooltipText: {
    type: String,
    required: false,
    default: null,
  },
  lockingPopup: {
    type: Boolean,
    required: false,
    default: true,
  },
  buttons: {
    type: Array as PropType<ButtonGroupItem[]>,
    required: false,
  },
  isOpen: {
    type: Boolean,
    required: false,
  },
  isDirectionFixed: {
    type: Boolean,
    required: false,
    default: false,
  },
});

const isExternalLink = computed(
  () => typeof props.to === "string" && props.to.startsWith("http")
);

interface Emit {
  (e: "setLock", isLocking: boolean): void;
  (e: "unlock"): void;
  (e: "toggle", value: boolean): void;
}
const emit = defineEmits<Emit>();

const navItemRef = ref<HTMLElement>();

const existPopup = computed(() => props.buttons && props.buttons?.length > 0);
const navItemOnClick = () => {
  emit("toggle", true);
  if (existPopup) emit("setLock", true);
};
const navItemMouseEnter = () => {
  if (!props.lockingPopup) emit("toggle", true);
};

const navItemMouseLeave = () => {
  if (!props.lockingPopup) emit("toggle", false);
};

const popupOnClose = () => {
  emit("toggle", false);
  emit("setLock", false);
};

const popupMouseEnter = () => {
  if (!props.lockingPopup) emit("toggle", true);
};

const popupMouseLeave = () => {
  if (!props.lockingPopup) emit("toggle", false);
};
</script>
