// packages/wiz-ui-react/src/components/base/pagination/components/pagination.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/pagination.css";
import clsx from "clsx";
import { memo } from "react";

import { WizIcon } from "@/components";
import { WizIChevronLeft, WizIChevronRight } from "@/components/icons";

type Props = {
  activeValue: number;
  length: number;
  setActiveValue: (value: number) => void;
};

const _Pagination = ({ activeValue, length, ...props }: Props) => {
  const onUpdatePage = (index: number) => {
    if (index < 1) return props.setActiveValue(1);
    if (index > length) return props.setActiveValue(length);
    props.setActiveValue(index);
  };
  const displayIndex = (() => {
    if (length < 5) return [...Array(length)].map((_, index) => index + 1);
    let from = activeValue - 2;
    if (activeValue < 3) from = 1;
    if (activeValue > length - 2) from = length - 4;
    return [...Array(5)].map((_, index) => from + index);
  })();
  return (
    <div
      className={clsx(
        styles.paginationStyle,
        activeValue <= 1 && styles.paginationGapStyle["left"],
        activeValue >= length && styles.paginationGapStyle["right"]
      )}
    >
      {activeValue > 1 && (
        <div
          onClick={() => onUpdatePage(activeValue - 1)}
          onKeyDown={(e) => {
            if (e.key === " ") onUpdatePage(activeValue - 1);
          }}
          className={clsx(
            styles.paginationButtonStyle,
            styles.paginationButtonVariantStyle["default"]
          )}
          tabIndex={displayIndex[0] - 1}
        >
          <WizIcon icon={WizIChevronLeft} size={"xl2"} />
        </div>
      )}
      {displayIndex.map((index) => (
        <div
          key={index}
          onClick={() => onUpdatePage(index)}
          onKeyDown={(e) => {
            if (e.key === " ") onUpdatePage(e.currentTarget.tabIndex);
          }}
          className={clsx(
            styles.paginationButtonStyle,
            styles.paginationButtonVariantStyle[
              activeValue === index ? "active" : "default"
            ]
          )}
          tabIndex={index}
        >
          {index}
        </div>
      ))}
      {activeValue < length && (
        <div
          onClick={() => onUpdatePage(activeValue + 1)}
          onKeyDown={(e) => {
            if (e.key === " ") onUpdatePage(activeValue + 1);
          }}
          className={clsx(
            styles.paginationButtonStyle,
            styles.paginationButtonVariantStyle["default"]
          )}
          tabIndex={displayIndex[displayIndex.length - 1] + 1}
        >
          <WizIcon icon={WizIChevronRight} size={"xl2"} />
        </div>
      )}
    </div>
  );
};

_Pagination.displayName = ComponentName.Pagination;

export const WizPagination = memo(_Pagination);

// packages/wiz-ui-next/src/components/base/pagination/pagination.vue
<template>
  <div
    :class="[
      paginationStyle,
      activeValue <= 1 && paginationGapStyle['left'],
      activeValue >= length && paginationGapStyle['right'],
    ]"
  >
    <div
      v-if="activeValue > 1"
      :class="[paginationButtonStyle, paginationButtonVariantStyle['default']]"
      @click="onUpdatePage(activeValue - 1)"
    >
      <component :is="WizIChevronLeft" :class="paginationIconStyle"></component>
    </div>
    <div
      v-for="index in displayIndex"
      :class="[
        paginationButtonStyle,
        paginationButtonVariantStyle[
          activeValue === index ? 'active' : 'default'
        ],
      ]"
      @click="onUpdatePage(index)"
    >
      {{ index }}
    </div>
    <div
      v-if="activeValue < length"
      :class="[paginationButtonStyle, paginationButtonVariantStyle['default']]"
      @click="onUpdatePage(activeValue + 1)"
    >
      <component
        :is="WizIChevronRight"
        :class="paginationIconStyle"
      ></component>
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  paginationButtonStyle,
  paginationButtonVariantStyle,
  paginationGapStyle,
  paginationIconStyle,
  paginationStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/pagination.css";
import { PropType, computed } from "vue";

import { WizIChevronLeft, WizIChevronRight } from "@/components/icons";

const props = defineProps({
  modelValue: {
    type: Number as PropType<number>,
    required: true,
  },
  length: {
    type: Number as PropType<number>,
    required: true,
  },
  /**
   * 表示ページ数を制御します。(`>=0`)
   * @default 2
   */
  sideLength: {
    type: Number as PropType<number>,
    required: false,
    default: 2,
  },
});

interface Emits {
  (event: "update:modelValue", value: number): void;
}

const emits = defineEmits<Emits>();

const activeValue = computed({
  get: () => props.modelValue,
  set: (value: number) => emits("update:modelValue", value),
});

const onUpdatePage = (index: number) => {
  if (index < 1) return (activeValue.value = 1);
  if (index > props.length) return (activeValue.value = props.length);
  activeValue.value = index;
};

const displayIndex = computed(() => {
  const sideItemLength = Math.max(0, props.sideLength);
  const maxItemLength = sideItemLength * 2 + 1;
  // 表示可能幅がページ数より大きい場合は全て表示
  if (props.length <= maxItemLength)
    return Array.from({ length: props.length }, (_, i) => i + 1);
  let from = activeValue.value - sideItemLength; // (ex.)  3 4 [5] 6 7
  if (activeValue.value <= sideItemLength) from = 1; // (ex.)  1 [2] 3 4 5
  if (activeValue.value > props.length - sideItemLength)
    from = props.length - 2 * sideItemLength; // (ex.)  6 7 8 [9] 10
  return Array.from({ length: maxItemLength }, (_, i) => from + i);
});
</script>
