// packages/wiz-ui-next/src/components/custom/voice-input/voice-input.vue
<template>
  <label
    :class="[
      voiceInputStyle,
      expand && voiceInputExpandStyle,
      disabled && voiceInputDisabledStyle,
      inputBorderStyle[state],
    ]"
    :style="{ maxWidth, minWidth }"
  >
    <textarea
      v-model="textValue"
      name="voice-input"
      :placeholder="computedPlaceholder"
      :disabled="disabled"
      :rows="rows"
      :style="{ resize }"
      :class="[voiceInputTextAreaStyle]"
      @focus="isFocused = true"
      @blur="isFocused = false"
    />
    <button
      type="button"
      :class="voiceInputButtonStyle"
      :disabled="disabled"
      :aria-label="isListening ? '音声入力を停止' : '音声入力を開始'"
      @click="onMicClick"
    >
      <WizIcon
        :icon="micDisabled || disabled ? WizIMicOffFilled : WizIMicFilled"
        :color="micColor"
        size="xl"
      />
    </button>
  </label>
</template>

<script setup lang="ts">
import { WizIcon, WizIMicFilled, WizIMicOffFilled } from "@/components";
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  voiceInputExpandStyle,
  voiceInputStyle,
  voiceInputTextAreaStyle,
  voiceInputDisabledStyle,
  voiceInputButtonStyle,
} from "@wizleap-inc/wiz-ui-styles/customs/voice-input.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { PropType, computed, inject, ref } from "vue";

import { formControlKey } from "@/hooks/use-form-control-provider";

defineOptions({
  name: ComponentName.VoiceInput,
});

const textValue = defineModel<string>({ required: true });

const props = defineProps({
  placeholder: {
    type: String,
    required: false,
  },
  disabled: {
    type: Boolean,
    required: false,
  },
  micDisabled: {
    type: Boolean,
    required: false,
    default: false,
  },
  expand: {
    type: Boolean,
    required: false,
  },
  rows: {
    type: Number,
    required: false,
    default: 3,
  },
  resize: {
    type: String as PropType<"none" | "vertical">,
    default: "none",
  },
  maxWidth: {
    type: String,
    required: false,
  },
  minWidth: {
    type: String,
    required: false,
  },
  isListening: {
    type: Boolean,
    required: false,
    default: false,
  },
});

interface Emit {
  (e: "micClick"): void;
}

const emit = defineEmits<Emit>();

// Form Control
const form = inject(formControlKey);
const isError = computed(() => (form ? form.isError.value : false));

// Focus state
const isFocused = ref(false);

const state = computed(() => {
  if (isError.value) return "error";
  if (props.isListening || isFocused.value) return "active";
  return "default";
});

const micColor = computed(() => {
  if (props.micDisabled || props.disabled) return "gray.500";
  if (props.isListening) return "green.800";

  return "gray.700";
});

const computedPlaceholder = computed(() => {
  if (props.placeholder) return props.placeholder;
  return props.disabled ? "入力できません" : "入力してください";
});

const onMicClick = () => {
  if (props.disabled) return;
  emit("micClick");
};
</script>

// packages/wiz-ui-react/src/components/custom/voice-input/components/voice-input.tsx
import { ComponentName, ColorKeys } from "@wizleap-inc/wiz-ui-constants";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import {
  voiceInputExpandStyle,
  voiceInputStyle,
  voiceInputTextAreaStyle,
  voiceInputDisabledStyle,
  voiceInputButtonStyle,
} from "@wizleap-inc/wiz-ui-styles/customs/voice-input.css";
import clsx from "clsx";
import React, {
  ComponentPropsWithoutRef,
  forwardRef,
  useContext,
  useMemo,
  useState,
} from "react";

import { WizIcon, WizIMicFilled, WizIMicOffFilled } from "@/components";
import { FormControlContext } from "@/components/custom/form/components/form-control-context";

type Props = Omit<
  ComponentPropsWithoutRef<"textarea">,
  "value" | "onChange" | "rows" | "resize"
> & {
  value: string;
  placeholder?: string;
  disabled?: boolean;
  micDisabled: boolean;
  expand?: boolean;
  rows?: number;
  resize?: "none" | "vertical";
  maxWidth?: string;
  minWidth?: string;
  isListening: boolean;
  onMicClick: () => void;
  onChange?: (value: string) => void;
};

const VoiceInput = forwardRef<HTMLTextAreaElement, Props>(
  (
    {
      value,
      placeholder,
      disabled = false,
      micDisabled,
      expand = false,
      rows = 3,
      resize = "none",
      maxWidth,
      minWidth,
      isListening,
      onMicClick,
      onChange,
      className,
      style,
      ...rest
    },
    ref
  ) => {
    const formControl = useContext(FormControlContext);
    const isError = formControl?.error || false;
    const [isFocused, setIsFocused] = useState(false);

    const state = useMemo(() => {
      if (isError) return "error";
      if (isListening || isFocused) return "active";
      return "default";
    }, [isError, isListening, isFocused]);

    const micColor: ColorKeys = useMemo(() => {
      if (micDisabled || disabled) return "gray.500";
      if (isListening) return "green.800";
      return "gray.700";
    }, [isListening, micDisabled, disabled]);

    const computedPlaceholder = useMemo(() => {
      if (placeholder) return placeholder;
      return disabled ? "入力できません" : "入力してください";
    }, [placeholder, disabled]);

    const handleMicClick = () => {
      if (disabled) return;
      onMicClick();
    };

    return (
      <label
        className={clsx(
          voiceInputStyle,
          expand && voiceInputExpandStyle,
          disabled && voiceInputDisabledStyle,
          inputBorderStyle[state],
          className
        )}
        style={{
          maxWidth,
          minWidth,
          ...style,
        }}
      >
        <textarea
          ref={ref}
          value={value}
          name="voice-input"
          placeholder={computedPlaceholder}
          disabled={disabled}
          rows={rows}
          className={voiceInputTextAreaStyle}
          style={{ resize }}
          onFocus={() => setIsFocused(true)}
          onBlur={() => setIsFocused(false)}
          onChange={(e) => onChange?.(e.target.value)}
          {...rest}
        />
        <button
          type="button"
          className={voiceInputButtonStyle}
          onClick={handleMicClick}
          disabled={disabled}
          aria-label={isListening ? "音声入力を停止" : "音声入力を開始"}
        >
          <WizIcon
            icon={micDisabled || disabled ? WizIMicOffFilled : WizIMicFilled}
            color={micColor}
            size="xl"
          />
        </button>
      </label>
    );
  }
);

VoiceInput.displayName = ComponentName.VoiceInput;

export default VoiceInput;
