// packages/wiz-ui-react/src/components/base/accordion/components/accordion.tsx
import { ColorKeys, ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/accordion.css";
import {
  backgroundStyle,
  colorStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import { FC, ReactNode } from "react";

import { WizHStack, WizIExpandMore, WizIcon } from "@/components";

import { useToggleAnimation } from "./use-toggle-animation";

type Props = {
  isOpen: boolean;
  openMessage?: string;
  closeMessage?: string;
  width?: string;
  bgColor?: ColorKeys;
  fontColor?: ColorKeys;
  children?: ReactNode;
  className?: string;
  onToggle: (isOpen: boolean) => void;
};

const Accordion: FC<Props> = ({
  isOpen,
  openMessage = "もっと見る",
  closeMessage = "閉じる",
  width = "20rem",
  bgColor,
  fontColor = "gray.600",
  children,
  className,
  onToggle,
}) => {
  const { isActuallyOpen, isAnimating, contentRef } =
    useToggleAnimation(isOpen);

  return (
    <details
      open={isActuallyOpen}
      style={{ width }}
      className={clsx(
        styles.accordionDetailsStyle,
        bgColor && backgroundStyle[bgColor],
        className
      )}
    >
      <summary
        className={styles.accordionSummaryStyle}
        onClick={(e) => {
          e.preventDefault();
          if (!isAnimating) {
            onToggle(!isOpen);
          }
        }}
      >
        <WizHStack
          align="center"
          justify="between"
          gap="xs2"
          className={clsx(
            styles.accordionMessageStyle,
            colorStyle[fontColor],
            bgColor && backgroundStyle[bgColor]
          )}
        >
          <div>{isOpen ? closeMessage : openMessage}</div>
          <WizIcon
            icon={WizIExpandMore}
            size="xl2"
            color={fontColor}
            className={clsx(
              styles.accordionExpandIconStyle,
              isOpen && styles.accordionRotateIconStyle
            )}
          />
        </WizHStack>
      </summary>
      <div ref={contentRef} className={styles.accordionContentStyle}>
        {children}
      </div>
    </details>
  );
};

Accordion.displayName = ComponentName.Accordion;

export const WizAccordion = Accordion;

// packages/wiz-ui/src/components/base/accordion/accordion.vue
<template>
  <details
    :class="[
      styles.accordionDetailsStyle,
      bgColor && commonStyles.backgroundStyle[bgColor],
    ]"
    :style="{ width }"
    :open="isOpen || isAnimating"
  >
    <summary :class="styles.accordionSummaryStyle" @click="onClick">
      <WizHStack
        align="center"
        justify="between"
        gap="xs2"
        :class="[
          styles.accordionMessageStyle,
          commonStyles.colorStyle[fontColor],
          bgColor && commonStyles.backgroundStyle[bgColor],
        ]"
      >
        <div>
          {{ isOpen ? closeMessage : openMessage }}
        </div>
        <WizIcon
          size="xl2"
          :icon="WizIExpandMore"
          :color="fontColor"
          :class="[
            styles.accordionExpandIconStyle,
            isOpen && styles.accordionRotateIconStyle,
          ]"
        />
      </WizHStack>
    </summary>
    <div ref="contentRef" :class="[styles.accordionContentStyle]">
      <slot />
    </div>
  </details>
</template>

<script setup lang="ts">
import { ColorKeys } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/accordion.css";
import * as commonStyles from "@wizleap-inc/wiz-ui-styles/commons";
import { ref, PropType } from "vue";

import { WizHStack, WizIcon } from "@/components";
import { WizIExpandMore } from "@/components/icons";

import {
  ANIMATION_CONFIGURATION,
  closingAnimationKeyframes,
  openingAnimationKeyframes,
} from "./animation-configuration";

const props = defineProps({
  isOpen: {
    type: Boolean,
    required: true,
  },
  openMessage: {
    type: String,
    required: false,
    default: "もっと見る",
  },
  closeMessage: {
    type: String,
    required: false,
    default: "閉じる",
  },
  width: {
    type: String,
    required: false,
    default: "20rem",
  },
  bgColor: {
    type: String as PropType<ColorKeys | undefined>,
    required: false,
  },
  fontColor: {
    type: String as PropType<ColorKeys>,
    required: false,
    default: "gray.600",
  },
});

interface Emit {
  (e: "toggle"): void;
}
const emit = defineEmits<Emit>();

const contentRef = ref<HTMLElement | undefined>();
const isAnimating = ref(false);

const onClick = (event: MouseEvent) => {
  event.preventDefault();
  if (contentRef.value === undefined) return;
  if (isAnimating.value) return;

  isAnimating.value = true;
  const content = contentRef.value;
  if (props.isOpen) {
    const closingAnimation = content.animate(
      closingAnimationKeyframes(content),
      ANIMATION_CONFIGURATION
    );
    closingAnimation.onfinish = () => {
      isAnimating.value = false;
    };
  } else {
    const openingAnimation = content.animate(
      openingAnimationKeyframes(content),
      ANIMATION_CONFIGURATION
    );
    openingAnimation.onfinish = () => {
      isAnimating.value = false;
    };
  }
  emit("toggle");
};
</script>
