// packages/wiz-ui-next/src/components/base/step-bar/step-bar.vue
<template>
  <div :class="styles.stepBarStyle">
    <div
      v-for="(content, i) in contents"
      :key="i"
      :class="styles.stepBarItemStyle[i === 0 ? 'first' : 'default']"
    >
      <WizVStack align="center" gap="no" height="100%">
        <WizStepPoint :status="content.status" />
        <span :class="styles.progressBarItemLabelStyle">
          <WizVStack align="center" gap="xs2">
            <WizText
              fontSize="sm"
              whiteSpace="nowrap"
              :bold="true"
              :color="content.status === 'done' ? 'green.800' : 'gray.800'"
            >
              {{ content.label }}
            </WizText>
            <WizText
              fontSize="xs"
              whiteSpace="nowrap"
              :color="content.status === 'done' ? 'green.800' : 'gray.800'"
            >
              {{ content.description }}
            </WizText>
          </WizVStack>
        </span>
      </WizVStack>
      <WizStepLine :active="content.progress" :isFirst="i === 0" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/step-bar.css";
import { PropType } from "vue";

import { WizText, WizVStack } from "@/components";

import { WizStepPoint, WizStepLine } from ".";

import type { StepItem } from "./types";

defineOptions({
  name: ComponentName.StepBar,
});

defineProps({
  contents: {
    type: Array as PropType<StepItem[]>,
    required: true,
  },
});
</script>

// packages/wiz-ui-react/src/components/base/step-bar/components/step-bar.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/step-bar.css";
import { FC } from "react";

import { WizText, WizVStack } from "@/components";

import { StepItem } from "./types";

import { WizStepLine, WizStepPoint } from "./";

type Props = {
  contents: StepItem[];
};

const StepBar: FC<Props> = ({ contents }: Props) => {
  return (
    <div className={styles.stepBarStyle}>
      {contents.map((item, index) => {
        const isFirst = index === 0;
        const color = item.status === "done" ? "green.800" : "gray.800";
        return (
          <div
            key={item.id}
            className={styles.stepBarItemStyle[isFirst ? "first" : "default"]}
          >
            <WizVStack align="center" gap="no" height="100%">
              <WizStepPoint status={item.status} />
              <span className={styles.progressBarItemLabelStyle}>
                <WizVStack align="center" gap="xs2">
                  <WizText fontSize="sm" whiteSpace="nowrap" bold color={color}>
                    {item.label}
                  </WizText>
                  <WizText fontSize="xs" whiteSpace="nowrap" color={color}>
                    {item.description}
                  </WizText>
                </WizVStack>
              </span>
            </WizVStack>
            <WizStepLine active={item.progress} isFirst={isFirst} />
          </div>
        );
      })}
    </div>
  );
};

StepBar.displayName = ComponentName.StepBar;

export const WizStepBar = StepBar;
