// packages/wiz-ui/src/components/base/textarea/text-area.vue
<template>
  <textarea
    v-model="textValue"
    :placeholder="placeholder"
    :name="name"
    :disabled="disabled"
    :rows="rows"
    :class="[
      textAreaStyle,
      textAreaVariantStyle[disabled ? 'disabled' : 'default'],
      expand && textAreaExpandStyle,
      inputBorderStyle[state],
    ]"
  />
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  textAreaStyle,
  textAreaVariantStyle,
  textAreaExpandStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/text-area.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { computed, inject, ref } from "vue";

import { formControlKey } from "@/hooks/use-form-control-provider";

defineOptions({
  name: ComponentName.TextArea,
});

interface Props {
  value: string;
  name: string;
  placeholder?: string;
  disabled?: boolean;
  expand?: boolean;
  rows?: number;
}

const props = withDefaults(defineProps<Props>(), {
  rows: 3,
});

interface Emit {
  (e: "input", value: string): void;
}

const emit = defineEmits<Emit>();

const textValue = computed({
  get: () => props.value,
  set: (value) => emit("input", value),
});

// Form Control
const form = inject(formControlKey);
const isError = computed(() => (form ? form.isError.value : false));
const hasFocus = ref(false);

const state = computed(() => {
  if (isError.value) return "error";
  if (hasFocus.value) return "active";
  return "default";
});
</script>

// packages/wiz-ui-react/src/components/base/textarea/components/text-area.tsx
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/text-area.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { memo, useMemo, useState } from "react";

import { useFormControl } from "@/hooks/use-form-control-provider";

export type Props = {
  id?: string;
  value?: string;
  placeholder?: string;
  disabled?: boolean;
  expand?: boolean;
  rows?: number;
  onChange: (value: string) => void;
};

const _TextArea = ({
  id,
  value,
  placeholder,
  disabled,
  expand,
  rows = 3,
  ...props
}: Props) => {
  const { isError } = useFormControl();
  const [hasFocus, setHasFocus] = useState(false);
  const state = useMemo(() => {
    if (isError) return "error";
    if (hasFocus) return "active";
    return "default";
  }, [isError, hasFocus]);

  return (
    <textarea
      value={value}
      placeholder={placeholder}
      id={id}
      disabled={disabled}
      rows={rows}
      className={`
        ${styles.textAreaStyle} ,
        ${styles.textAreaVariantStyle[disabled ? "disabled" : "default"]}
        ${expand && styles.textAreaExpandStyle}
        ${inputBorderStyle[state]} `}
      onFocus={() => setHasFocus(true)}
      onBlur={() => setHasFocus(false)}
      onChange={(e) => props.onChange(e.target.value)}
    />
  );
};

export const WizTextArea = memo(_TextArea);
