// packages/wiz-ui-react/src/components/base/menu/components/menu-item.tsx
import {
  ColorKeys,
  ComponentName,
  FontSizeKeys,
} from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/menu.css";
import { fontSizeStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import {
  ComponentProps,
  ForwardedRef,
  KeyboardEventHandler,
  MouseEventHandler,
  forwardRef,
  useState,
} from "react";

import {
  TIcon,
  WizHStack,
  WizIChevronRight,
  WizIcon,
  WizTag,
} from "@/components";
import { BaseProps } from "@/types";

import { TagVariant } from "../../tag/types";
type Props = BaseProps & {
  label: string;
  width?: string;
  active?: boolean;
  clickable?: boolean;
  expand?: boolean;
  fontSize?: FontSizeKeys;
  selected?: boolean;
  tagLabel?: string;
  tagIcon?: TIcon;
  tagVariant?: TagVariant;
} & ComponentProps<"div">;

const MenuItem = forwardRef(
  (
    {
      className,
      style,
      label,
      width = "10rem",
      active = false,
      clickable = true,
      expand,
      fontSize = "md",
      selected,
      tagLabel,
      tagIcon,
      tagVariant = "info",
      onMouseOver,
      onMouseLeave,
      onMouseDown,
      onMouseUp,
      onMouseOut,
      onClick,
      onKeyDown,
      ...props
    }: Props,
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const [isHover, setIsHover] = useState(false);

    const [isPressed, setIsPressed] = useState(false);

    const iconColor: ColorKeys =
      clickable && (active || isHover) ? "green.800" : "gray.500";

    function getVariant() {
      if (!clickable) return "disabled";
      if (selected) return "selected";
      if (active || isPressed) return "active";
      if (isHover) return "hover";
      return "default";
    }

    const handleMouseOver: MouseEventHandler<HTMLDivElement> = (e) => {
      setIsHover(true);
      onMouseOver?.(e);
    };

    const handleMouseLeave: MouseEventHandler<HTMLDivElement> = (e) => {
      setIsHover(false);
      onMouseLeave?.(e);
    };

    /** activate */
    const handleMouseDown: MouseEventHandler<HTMLDivElement> = (e) => {
      setIsPressed(true);
      onMouseDown?.(e);
    };

    /** inactivate */
    const handleMouseUp: MouseEventHandler<HTMLDivElement> = (e) => {
      setIsPressed(false);
      onMouseUp?.(e);
    };

    /** inactivate */
    const handleMouseOut: MouseEventHandler<HTMLDivElement> = (e) => {
      setIsPressed(false);
      onMouseOut?.(e);
    };

    const handleClick: MouseEventHandler<HTMLDivElement> = (e) => {
      if (clickable) onClick?.(e);
    };

    const handleKeyDown: KeyboardEventHandler<HTMLDivElement> = (e) => {
      onKeyDown?.(e);
      if (e.key === "Enter" || e.key === " ") {
        if (clickable) {
          if (e.target instanceof HTMLElement) {
            e.stopPropagation();
            e.target.click();
          }
        }
      }
    };

    const tagFontSize = fontSize === "xl5" || fontSize === "xl6" ? "md" : "xs";

    return (
      <div
        ref={ref}
        className={clsx(
          className,
          styles.menuItemStyle,
          styles.menuItemVariantStyle[getVariant()],
          expand && styles.menuItemExpand
        )}
        style={{ ...style, width }}
        {...props}
        onMouseOver={handleMouseOver}
        onMouseLeave={handleMouseLeave}
        onMouseDown={handleMouseDown}
        onMouseUp={handleMouseUp}
        onMouseOut={handleMouseOut}
        onClick={handleClick}
        role={clickable ? "button" : undefined}
        tabIndex={clickable ? 0 : undefined}
        onKeyDown={handleKeyDown}
      >
        <WizHStack align="center" justify="between">
          <div className={fontSizeStyle[fontSize]}>{label}</div>
          <WizHStack align="center" gap="xs">
            {tagLabel && (
              <div className={styles.menuItemTagStyle}>
                <WizTag
                  label={tagLabel}
                  icon={tagIcon}
                  variant={tagVariant}
                  fontSize={tagFontSize}
                  fontWeight="bold"
                />
              </div>
            )}
            <WizIcon size="xl2" icon={WizIChevronRight} color={iconColor} />
          </WizHStack>
        </WizHStack>
      </div>
    );
  }
);

MenuItem.displayName = ComponentName.MenuItem;

export const WizMenuItem = MenuItem;

// packages/wiz-ui-next/src/components/base/menu/menu-item.vue
<template>
  <div
    :class="[
      menuItemStyle,
      menuItemVariantStyle[componentStatus],
      expand && menuItemExpand,
      transparent && menuItemTransparentVariantStyle[componentStatus],
    ]"
    :style="{ width: width }"
    @mouseover="onMouseOver"
    @mouseleave="onMouseLeave"
    @mousedown="activate"
    @mouseup="inactivate"
    @mouseout="inactivate"
    @click="onClick"
  >
    <WizHStack align="center" justify="between">
      <WizHStack align="center" gap="xs">
        <WizIcon v-if="icon" size="xl2" :icon="icon" :color="iconColor" />
        <div :class="fontSizeStyle[fontSize]">
          {{ label }}
        </div>
      </WizHStack>

      <WizHStack align="center" gap="xs">
        <div v-if="tagLabel" :class="menuItemTagStyle">
          <WizTag
            :label="tagLabel"
            :icon="tagIcon"
            :variant="tagVariant"
            :fontSize="tagFontSize"
            fontWeight="bold"
          />
        </div>
        <WizIcon size="xl2" :icon="WizIChevronRight" :color="tagIconColor" />
      </WizHStack>
    </WizHStack>
  </div>
</template>

<script setup lang="ts">
import { FontSizeKeys } from "@wizleap-inc/wiz-ui-constants";
import {
  menuItemExpand,
  menuItemStyle,
  menuItemTagStyle,
  menuItemTransparentVariantStyle,
  menuItemVariantStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/menu.css";
import { fontSizeStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { PropType, computed, ref } from "vue";

import { TIcon, WizIChevronRight } from "@/components/icons";

import { WizHStack, WizIcon, WizTag } from "../";
import { TagVariant } from "../tag/types";

interface Emit {
  (event: "click"): void;
}

const props = defineProps({
  label: {
    type: String,
    required: true,
  },
  width: {
    type: String,
    required: false,
    default: "10rem",
  },
  active: {
    type: Boolean,
    required: false,
    default: false,
  },
  clickable: {
    type: Boolean,
    required: false,
    default: true,
  },
  expand: {
    type: Boolean,
    required: false,
  },
  fontSize: {
    type: String as PropType<FontSizeKeys>,
    required: false,
    default: "md",
  },
  selected: {
    type: Boolean,
    required: false,
    default: false,
  },
  icon: {
    type: Object as PropType<TIcon>,
    required: false,
  },
  transparent: {
    type: Boolean,
    required: false,
    default: false,
  },
  tagLabel: {
    type: String,
    required: false,
    default: "",
  },
  tagIcon: {
    type: Object as PropType<TIcon>,
    required: false,
  },
  tagVariant: {
    type: String as PropType<TagVariant>,
    required: false,
    default: "info",
  },
});

const emit = defineEmits<Emit>();

const isHover = ref(false);
const isPressed = ref(false);

const onMouseOver = () => {
  isHover.value = true;
};
const onMouseLeave = () => (isHover.value = false);
const onClick = () => props.clickable && emit("click");

const activate = () => (isPressed.value = true);
const inactivate = () => (isPressed.value = false);

const width = computed(() => props.width);

const componentStatus = computed(() => {
  if (!props.clickable) return "disabled";
  if (props.selected) return "selected";
  if (props.active || isPressed.value) return "active";
  if (isHover.value) return "hover";
  return "default";
});

const tagFontSize = computed(() => {
  if (props.fontSize === "xl5" || props.fontSize === "xl6") return "md";
  return "xs";
});

const iconColor = computed(() => {
  if (!props.clickable) return "gray.500";
  if (props.active || isHover.value) return "green.800";
  return "gray.800";
});

const tagIconColor = computed(() => {
  if (!props.clickable) return "gray.500";
  if (props.active || isHover.value) return "green.800";
  return "gray.500";
});
</script>
