// packages/wiz-ui/src/components/base/full-modal-view/full-modal-view.vue
<template>
  <MountingPortal mountTo="body" append>
    <div
      :class="[
        zIndexStyle['base'],
        !isActuallyOpen && styles.hiddenStyle,
        backgroundStyle['white.800'],
        styles.containerStyle,
      ]"
      :style="{
        left: `${contentLeft}px`,
        height: `${modalHeight}px`,
      }"
      ref="modalRef"
    >
      <WizVStack>
        <div :class="styles.headerStyle">
          <WizHStack
            justify="between"
            :height="getSpacingCss('xl3')"
            align="center"
          >
            <WizText bold> {{ title }} </WizText>
            <WizHStack gap="md">
              <slot name="header" />
              <WizIconButton
                :icon="WizIClose"
                variant="transparent"
                @click="closeModal"
                :ariaLabel="ARIA_LABELS.FULL_MODAL_VIEW.CLOSE"
              />
            </WizHStack>
          </WizHStack>
        </div>
        <WizDivider color="gray.300" />
        <div :class="styles.contentStyle">
          <slot />
        </div>
      </WizVStack>
    </div>
  </MountingPortal>
</template>

<script setup lang="ts">
import {
  ARIA_LABELS,
  ComponentName,
  getSpacingCss,
} from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/full-modal-view.css";
import {
  backgroundStyle,
  zIndexStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import { ref, watch } from "vue";

import {
  WizDivider,
  WizHStack,
  WizIClose,
  WizIconButton,
  WizText,
  WizVStack,
} from "@/components";

defineOptions({
  name: ComponentName.FullModalView,
});

const props = defineProps({
  title: {
    type: String,
    required: false,
  },
  isOpen: {
    type: Boolean,
    required: true,
  },
});

interface Emit {
  (e: "close"): void;
}
const emit = defineEmits<Emit>();
const isActuallyOpen = ref(props.isOpen);
const closeModal = () => {
  emit("close");
};
const modalRef = ref<HTMLElement | undefined>(undefined);
const contentLeft = document.documentElement.clientLeft;
const modalHeight = document.documentElement.scrollHeight;

// Animation + 開閉ロジック
watch(
  () => props.isOpen,
  (isOpen) => {
    if (isOpen === isActuallyOpen.value) {
      return;
    }
    if (isOpen) {
      isActuallyOpen.value = true;
      modalRef.value?.animate(
        [
          {
            top: `${window.innerHeight}px`,
          },
          {
            top: `${0}px`,
          },
        ],
        {
          duration: 200,
          easing: "ease-in-out",
        }
      );
    } else {
      const animation = modalRef.value?.animate(
        [
          {
            top: `${0}px`,
          },
          {
            top: `${window.innerHeight}px`,
          },
        ],
        {
          duration: 200,
          easing: "ease-in-out",
        }
      );
      if (animation)
        animation.onfinish = () => {
          isActuallyOpen.value = false;
        };
    }
  }
);
</script>

// packages/wiz-ui-react/src/components/base/full-modal-view/components/full-modal-view.tsx
import {
  ARIA_LABELS,
  ComponentName,
  getSpacingCss,
} from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/full-modal-view.css";
import clsx from "clsx";
import { FC, ReactNode, useEffect, useRef, useState } from "react";

import {
  WizDivider,
  WizHStack,
  WizIClose,
  WizIconButton,
  WizPortal,
  WizText,
  WizVStack,
} from "@/components";

type Props = {
  isOpen: boolean;
  title: string;
  header?: ReactNode;
  children: ReactNode;
  onClose?: () => void;
};

const FullModalView: FC<Props> = ({
  isOpen,
  title,
  header,
  children,
  onClose,
}: Props) => {
  const modalRef = useRef<HTMLDivElement | null>(null);
  const [isActuallyOpen, setIsActuallyOpen] = useState(isOpen);

  useEffect(() => {
    if (isOpen) {
      // Move-in animation
      setIsActuallyOpen(true);
      modalRef.current?.animate(
        [
          {
            transform: "translateY(100vh)",
          },
          {
            transform: "translateY(0)",
          },
        ],
        {
          duration: 300,
          easing: "ease",
          fill: "forwards",
        }
      );
    } else {
      // Move-out animation
      const animation = modalRef.current?.animate(
        [
          {
            transform: "translateY(0)",
          },
          {
            transform: "translateY(100vh)",
          },
        ],
        {
          duration: 300,
          easing: "ease",
          fill: "forwards",
        }
      );
      if (animation) {
        animation.onfinish = () => {
          // Ensure the container is hidden after the animation is complete
          setIsActuallyOpen(false);
        };
      }
    }
  }, [isOpen]);

  return (
    <WizPortal container={document.body}>
      <div
        ref={modalRef}
        className={clsx([
          styles.containerStyle,
          !isActuallyOpen && styles.hiddenStyle,
        ])}
      >
        <WizVStack>
          <div className={styles.headerStyle}>
            <WizHStack
              justify="between"
              align="center"
              height={getSpacingCss("xl3")}
            >
              <WizText bold>{title}</WizText>
              <WizHStack gap="md">
                {header}
                <WizIconButton
                  onClick={() => onClose?.()}
                  icon={WizIClose}
                  variant="transparent"
                  aria-label={ARIA_LABELS.FULL_MODAL_VIEW.CLOSE}
                />
              </WizHStack>
            </WizHStack>
          </div>
          <WizDivider color="gray.300" />
          <div className={styles.contentStyle}>{children}</div>
        </WizVStack>
      </div>
    </WizPortal>
  );
};

FullModalView.displayName = ComponentName.FullModalView;

export const WizFullModalView = FullModalView;
