// packages/wiz-ui-next/src/components/base/dropdown/dropdown.vue
<template>
  <WizPopupContainer>
    <slot />
    <WizPopup
      :isOpen="modelValue"
      @onClose="modelValue = false"
      :gap="gap"
      :isDirectionFixed="isDirectionFixed"
    >
      <div :class="[dropdownStyle, skeleton && dropdownSkeletonStyle]">
        <WizVStack p="xs" gap="xs2">
          <slot name="options" />
        </WizVStack>
      </div>
    </WizPopup>
  </WizPopupContainer>
</template>

<script setup lang="ts">
import { ComponentName, SpacingKeys } from "@wizleap-inc/wiz-ui-constants";
import {
  dropdownStyle,
  dropdownSkeletonStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/dropdown.css";
import { computed, PropType } from "vue";

import { WizPopup, WizPopupContainer, WizVStack } from "@/components";

defineOptions({
  name: ComponentName.Dropdown,
});

const props = defineProps({
  modelValue: {
    type: Boolean,
    required: true,
  },
  skeleton: {
    type: Boolean,
    required: false,
  },
  gap: {
    type: String as PropType<SpacingKeys>,
    required: false,
  },
  isDirectionFixed: {
    type: Boolean,
    required: false,
    default: false,
  },
});

interface Emit {
  (event: "update:modelValue", value: boolean): void;
}

const emit = defineEmits<Emit>();

const modelValue = computed({
  get: () => props.modelValue,
  set: (value: boolean) => emit("update:modelValue", value),
});
</script>

// packages/wiz-ui-react/src/components/base/dropdown/components/dropdown.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/dropdown.css";
import clsx from "clsx";
import { ComponentProps, FC, ReactNode, useRef } from "react";

import { WizPopup, WizVStack } from "@/components";

type Props = {
  isOpen: boolean;
  children: ReactNode;
  options: ReactNode;
  skeleton?: boolean;
  gap?: ComponentProps<typeof WizPopup>["gap"];
  isDirectionFixed?: boolean;
  onClose: () => void;
};

const Dropdown: FC<Props> = ({
  isOpen,
  children,
  options,
  skeleton,
  gap,
  isDirectionFixed,
  onClose,
}) => {
  const anchorRef = useRef<HTMLDivElement>(null);

  return (
    <>
      <div
        ref={anchorRef}
        style={{ width: "fit-content", height: "fit-content" }}
      >
        {children}
      </div>
      <WizPopup
        isOpen={isOpen}
        onClose={onClose}
        anchorElement={anchorRef}
        gap={gap}
        isDirectionFixed={isDirectionFixed}
      >
        <div
          className={clsx(
            styles.dropdownStyle,
            skeleton && styles.dropdownSkeletonStyle
          )}
        >
          <WizVStack p="xs" gap="xs2">
            {options}
          </WizVStack>
        </div>
      </WizPopup>
    </>
  );
};

Dropdown.displayName = ComponentName.Dropdown;

export const WizDropdown = Dropdown;
