// packages/wiz-ui-next/src/components/base/textarea/text-area.vue
<template>
  <textarea
    v-model="textValue"
    :placeholder="placeholder"
    :id="id"
    :disabled="disabled"
    :rows="rows"
    :class="[
      textAreaStyle,
      textAreaVariantStyle[disabled ? 'disabled' : 'default'],
      expand && textAreaExpandStyle,
      inputBorderStyle[state],
    ]"
    :style="{ resize, maxWidth, minWidth, maxHeight, minHeight }"
  />
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  textAreaExpandStyle,
  textAreaStyle,
  textAreaVariantStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/text-area.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { PropType, computed, inject } from "vue";

import { formControlKey } from "@/hooks/use-form-control-provider";

defineOptions({
  name: ComponentName.TextArea,
});

const props = defineProps({
  id: {
    type: String,
    required: false,
  },
  modelValue: {
    type: String,
    required: true,
  },
  placeholder: {
    type: String,
    required: false,
  },
  disabled: {
    type: Boolean,
    required: false,
  },
  expand: {
    type: Boolean,
    required: false,
  },
  rows: {
    type: Number,
    required: false,
    default: 3,
  },
  resize: {
    type: String as PropType<"none" | "both" | "horizontal" | "vertical">,
    default: "none",
  },
  maxWidth: {
    type: String,
    required: false,
  },
  minWidth: {
    type: String,
    required: false,
  },
  maxHeight: {
    type: String,
    required: false,
  },
  minHeight: {
    type: String,
    required: false,
  },
});

interface Emit {
  (e: "update:modelValue", value: string): void;
}

const emit = defineEmits<Emit>();

const textValue = computed({
  get: () => props.modelValue,
  set: (value) => emit("update:modelValue", value),
});

// Form Control
const form = inject(formControlKey);
const isError = computed(() => (form ? form.isError.value : false));

const state = computed(() => {
  if (isError.value) return "error";
  return "default";
});
</script>

// packages/wiz-ui-react/src/components/base/text-area/components/text-area.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/text-area.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import { forwardRef, useContext } from "react";

import { FormControlContext } from "@/components/custom/form/components/form-control-context";
import { BaseProps } from "@/types";
function getInputBorderStyleKey(isError?: boolean) {
  if (isError) return "error";
  return "default";
}

type Props = BaseProps & {
  id?: string;
  value: string;
  placeholder?: string;
  disabled?: boolean;
  expand?: boolean;
  rows?: number;
  error?: boolean;
  resize?: "none" | "both" | "horizontal" | "vertical";
  maxWidth?: string;
  minWidth?: string;
  maxHeight?: string;
  minHeight?: string;
  onChange: (value: string) => void;
};

const TextArea = forwardRef<HTMLTextAreaElement, Props>(
  (
    {
      className,
      style,
      id,
      value,
      placeholder,
      disabled,
      expand,
      rows = 3,
      error,
      resize = "none",
      maxWidth,
      minWidth,
      maxHeight,
      minHeight,
      onChange,
    },
    ref
  ) => {
    const formControl = useContext(FormControlContext);

    const isError = error || formControl.error;

    return (
      <textarea
        ref={ref}
        id={id}
        value={value}
        placeholder={placeholder}
        disabled={disabled}
        rows={rows}
        style={{
          ...style,
          resize,
          maxWidth,
          minWidth,
          maxHeight,
          minHeight,
        }}
        className={clsx(
          className,
          styles.textAreaStyle,
          styles.textAreaVariantStyle[disabled ? "disabled" : "default"],
          expand && styles.textAreaExpandStyle,
          inputBorderStyle[getInputBorderStyleKey(isError)]
        )}
        onChange={(e) => onChange(e.target.value)}
      />
    );
  }
);

TextArea.displayName = ComponentName.TextArea;

export const WizTextArea = TextArea;
