// packages/wiz-ui-react/src/components/custom/schedule/components/card.tsx
import * as styles from "@wizleap-inc/wiz-ui-styles/customs/schedule.css";

import { ScheduleCardVariant } from "../types";

interface Props {
  variant?: ScheduleCardVariant;
  text: string;
  gridRow: string;
  gridColumn: string;
  show?: boolean;
}

export const WizScheduleCard = ({
  variant = "primary",
  text,
  gridRow,
  gridColumn,
  show = true,
}: Props) => {
  const showText = () => {
    const [start, end] = gridRow
      .split("/")
      .map((x) => x.trim())
      .map(Number);
    return end - start > 2;
  };

  return (
    <div
      className={styles.card[variant]}
      style={{ gridRow, gridColumn }}
      hidden={!show}
    >
      {showText() ? text : ""}
    </div>
  );
};

// packages/wiz-ui-next/src/components/custom/schedule/components/card.vue
<template>
  <div
    :class="[styles.card[variant]]"
    :style="{ gridRow, gridColumn }"
    v-show="show"
  >
    {{ showText ? text : "" }}
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/customs/schedule.css";
import { PropType, computed } from "vue";

import { ScheduleCardVariant } from "../types";

const props = defineProps({
  variant: {
    type: String as PropType<ScheduleCardVariant>,
    default: "primary",
    required: false,
  },
  text: {
    type: String,
    required: true,
  },
  gridRow: {
    type: String,
    required: true,
  },
  gridColumn: {
    type: String,
    required: true,
  },
  show: {
    type: Boolean,
    required: false,
    default: true,
  },
});

defineOptions({
  name: ComponentName.ScheduleCard,
});

const showText = computed(() => {
  const [start, end] = props.gridRow
    .split("/")
    .map((x) => x.trim())
    .map(Number);
  return end - start > 2;
});
</script>
