// packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue
<template>
  <WizVStack
    gap="xs2"
    :class="[
      popupButtonGroupStyle,
      disabled && popupButtonGroupDisabledCursorStyle,
      depth === 0 && borderRadiusStyle[borderRadius],
    ]"
    :style="{ minWidth: computedWidth }"
    :p="depth === 0 ? p : 'no'"
  >
    <div v-for="item in items">
      <hr
        v-if="item.kind === 'divider'"
        :class="popupButtonGroupDividerStyle"
      />
      <div v-else-if="item.item.kind === 'group'">
        <span
          :class="[
            popupButtonGroupTitleBaseStyle,
            disabled
              ? popupButtonGroupTitleVariantStyle['disabled']
              : popupButtonGroupTitleVariantStyle['enabled'],
          ]"
          :style="{
            paddingLeft: `calc(${THEME.spacing.xs2} + ${depth} * ${THEME.spacing.lg})`,
          }"
        >
          {{ item.item.title }}</span
        >
        <WizPopupButtonGroup
          :options="item.item.items"
          :groupDivider="item.item.groupDivider"
          :buttonDivider="item.item.buttonDivider"
          :disabled="disabled"
          :depth="depth + 1"
        />
      </div>
      <div v-else-if="item.item.kind === 'button'">
        <div
          :class="[
            popupButtonGroupButtonBaseStyle,
            disabled || item.item.option.disabled
              ? popupButtonGroupButtonVariantStyle['disabled']
              : popupButtonGroupButtonVariantStyle['enabled'],
            item.item.option.disabled && popupButtonGroupDisabledCursorStyle,
          ]"
          :style="{
            paddingLeft: `calc(${THEME.spacing.xs2} + ${depth} * ${THEME.spacing.lg})`,
          }"
          @click="popupButtonMouseDown(item.item)"
          @mousedown="onHoldClick(item.item)"
          @mouseover="popupButtonMouseOver(item.item)"
          @mouseout="popupButtonMouseOut(item.item)"
          @keypress.enter="popupButtonKeyPressEnter(item.item)"
          :tabIndex="0"
          :key="`${item.item.option.label}-${item.item.option.value}`"
        >
          <span :class="popupButtonGroupInnerContainerStyle">
            <span>{{ item.item.option.label }}</span>
            <WizIcon
              v-if="item.item.option.icon"
              :icon="item.item.option.icon"
              :color="
                item.item.option.value === isClicking
                  ? 'white.800'
                  : disabled || item.item.option.disabled
                  ? 'gray.400'
                  : item.item.option.value === isHover
                  ? 'green.800'
                  : item.item.option.iconDefaultColor ?? 'gray.500'
              "
              size="md"
            />
          </span>
          <span v-if="item.item.option.exLabel">{{
            item.item.option.exLabel
          }}</span>
        </div>
      </div>
    </div>
  </WizVStack>
</template>

<script setup lang="ts">
import {
  ComponentName,
  SpacingKeys,
  THEME,
} from "@wizleap-inc/wiz-ui-constants";
import {
  popupButtonGroupStyle,
  popupButtonGroupDisabledCursorStyle,
  popupButtonGroupButtonBaseStyle,
  popupButtonGroupTitleBaseStyle,
  popupButtonGroupDividerStyle,
  popupButtonGroupInnerContainerStyle,
  popupButtonGroupTitleVariantStyle,
  popupButtonGroupButtonVariantStyle,
  borderRadiusStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/popup-button-group.css";
import { computed, PropType, ref } from "vue";

import { WizIcon, WizVStack } from "@/components";

import { ButtonGroupItem } from "./types";

defineOptions({
  name: ComponentName.PopupButtonGroup,
});

const props = defineProps({
  options: {
    type: Array as PropType<ButtonGroupItem[]>,
    required: true,
  },
  width: {
    type: String,
    required: false,
    default: "10rem",
  },
  p: {
    type: String as PropType<SpacingKeys>,
    required: false,
    default: "no",
  },
  borderRadius: {
    type: String as PropType<SpacingKeys>,
    required: false,
    default: "no",
  },
  disabled: {
    type: Boolean,
    required: false,
    default: false,
  },
  expand: {
    type: Boolean,
    required: false,
  },
  groupDivider: {
    type: Boolean,
    required: false,
    default: false,
  },
  buttonDivider: {
    type: Boolean,
    required: false,
    default: false,
  },
  depth: {
    type: Number,
    required: false,
    default: 0,
  },
});

type ItemElement =
  | { kind: "divider" }
  | { kind: "item"; item: Exclude<ButtonGroupItem, { kind: "divider" }> };

const items = computed(() => {
  const divider: ItemElement = { kind: "divider" };
  const items = props.options
    .map((opt, i) => {
      if (opt.kind === "divider") {
        return [divider];
      }
      const optionItem: ItemElement = {
        kind: "item",
        item: opt,
      };
      if (i + 1 === props.options.length) return [optionItem];
      switch (props.options[i].kind) {
        case "group": {
          return props.groupDivider ? [optionItem, divider] : [optionItem];
        }
        case "button": {
          return props.buttonDivider && props.options[i + 1].kind === "button"
            ? [optionItem, divider]
            : [optionItem];
        }
        case "divider": {
          return [];
        }
      }
    })
    .flat();
  return items;
});

const isClicking = ref<number | null>(null);
const isHover = ref<number | null>(null);

const onHoldClick = (item: ButtonGroupItem) => {
  if (props.disabled) return;
  if (item.kind === "button" && !item.option.disabled) {
    isClicking.value = item.option.value;
    const mouseup = () => {
      isClicking.value = null;
      document.removeEventListener("mouseup", mouseup);
    };
    document.addEventListener("mouseup", mouseup);
  }
};

const popupButtonMouseDown = (item: ButtonGroupItem) => {
  if (props.disabled) return;
  if (item.kind === "button" && !item.option.disabled) {
    item.option.onClick();
  }
};

const popupButtonMouseOver = (item: ButtonGroupItem) => {
  if (props.disabled) return;
  if (item.kind === "button" && !item.option.disabled) {
    isHover.value = item.option.value;
  }
};

const popupButtonMouseOut = (item: ButtonGroupItem) => {
  if (props.disabled) return;
  if (item.kind === "button" && !item.option.disabled) {
    isHover.value = null;
  }
};

const popupButtonKeyPressEnter = (item: ButtonGroupItem) => {
  if (props.disabled) return;
  if (item.kind === "button" && !item.option.disabled) {
    item.option.onClick();
  }
};

const computedWidth = computed(() => (props.expand ? "100%" : props.width));
</script>

// packages/wiz-ui-react/src/components/base/popup-button-group/components/popup-button-group.tsx
import { ComponentName, SpacingKeys } from "@wizleap-inc/wiz-ui-constants";
import {
  borderRadiusStyle,
  popupButtonGroupDisabledCursorStyle,
  popupButtonGroupStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/popup-button-group.css";
import clsx from "clsx";
import { FC, useMemo, ComponentPropsWithoutRef } from "react";

import { WizVStack } from "@/components";

import { ButtonGroupItem, ItemElement } from "../types";

import { ButtonItem } from "./button-item";
import { DividerItem } from "./divider-item";
import { GroupItem } from "./group-item";

type Props = ComponentPropsWithoutRef<"div"> & {
  options: ButtonGroupItem[];
  width?: string;
  p?: SpacingKeys;
  borderRadius?: SpacingKeys;
  disabled?: boolean;
  expand?: boolean;
  groupDivider?: boolean;
  buttonDivider?: boolean;
  depth?: number;
};

const PopupButtonGroup: FC<Props> = ({
  className,
  style,
  options,
  width = "10rem",
  p = "no",
  borderRadius = "no",
  disabled = false,
  expand = false,
  groupDivider = false,
  buttonDivider = false,
  depth = 0,
  ...props
}) => {
  const items = useMemo(() => {
    const divider: ItemElement = { kind: "divider" };
    const items = options
      .map((opt, i) => {
        if (opt.kind === "divider") {
          return [divider];
        }
        const optionItem: ItemElement = {
          kind: "item",
          item: opt,
        };
        if (i + 1 === options.length) return [optionItem];
        switch (options[i].kind) {
          case "group": {
            return groupDivider ? [optionItem, divider] : [optionItem];
          }
          case "button": {
            return buttonDivider && options[i + 1].kind === "button"
              ? [optionItem, divider]
              : [optionItem];
          }
          case "divider": {
            return [];
          }
        }
      })
      .flat();
    return items;
  }, [buttonDivider, groupDivider, options]);

  return (
    <div
      {...props}
      className={clsx(
        className,
        popupButtonGroupStyle,
        disabled && popupButtonGroupDisabledCursorStyle,
        depth === 0 && borderRadiusStyle[borderRadius]
      )}
      style={{ ...style, minWidth: expand ? "100%" : width }}
    >
      <WizVStack gap="xs2" p={depth === 0 ? p : "no"}>
        {items.map((item, i) => {
          if (item.kind === "divider") {
            return <DividerItem key={`divider-${i}`} />;
          } else if (item.item.kind === "group") {
            return (
              <GroupItem
                key={`group-${i}-${item.item.title}`}
                item={item.item}
                disabled={disabled}
                depth={depth}
              />
            );
          } else if (item.item.kind === "button") {
            return (
              <ButtonItem
                key={`button-${i}-${item.item.option.value}`}
                item={item.item}
                disabled={disabled}
                depth={depth}
              />
            );
          }
        })}
      </WizVStack>
    </div>
  );
};

PopupButtonGroup.displayName = ComponentName.PopupButtonGroup;

export const WizPopupButtonGroup = PopupButtonGroup;
