// packages/wiz-ui-next/src/components/base/divider/divider.vue
<template>
  <hr
    :class="[
      dividerStyle[variant],
      dividerDirectionStyle[direction],
      borderColorStyle[color],
    ]"
  />
</template>

<script setup lang="ts">
import { ComponentName, ColorKeys } from "@wizleap-inc/wiz-ui-constants";
import {
  dividerStyle,
  dividerDirectionStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/divider.css";
import { borderColorStyle } from "@wizleap-inc/wiz-ui-styles/commons";

defineOptions({
  name: ComponentName.Divider,
});
interface Props {
  color?: ColorKeys;
  variant?: "solid" | "dashed" | "dotted";
  direction?: "horizontal" | "vertical";
}

withDefaults(defineProps<Props>(), {
  color: "gray.400",
  variant: "solid",
  direction: "horizontal",
});
</script>

// packages/wiz-ui-react/src/components/base/divider/components/divider.tsx
import { ColorKeys } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/divider.css";
import { borderColorStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { memo } from "react";

export type Props = {
  color?: ColorKeys;
  variant?: "solid" | "dashed" | "dotted";
  direction?: "horizontal" | "vertical";
};

const _Divider = ({
  color = "gray.400",
  variant = "solid",
  direction = "horizontal",
}: Props) => (
  <hr
    className={`
     ${styles.dividerStyle[variant]}
     ${styles.dividerDirectionStyle[direction]} 
     ${borderColorStyle[color]}
    `}
  />
);

export const WizDivider = memo(_Divider);
