// packages/wiz-ui/src/components/base/avatar/avatar.vue
<template>
  <div
    :class="[
      avatarStyle,
      sizeStyle[size],
      colorStyle[color],
      clickable && avatarClickableStyle,
    ]"
    @click="onClick"
  >
    <img
      :class="avatarImageStyle"
      v-if="isImgLoadSuccess"
      :src="src"
      :alt="alt"
      @error="onError"
    />
    <div v-else :class="[avatarFallbackStyle, backgroundStyle[bgColor]]">
      {{ fallback }}
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  ComponentName,
  ColorKeys,
  SpacingKeys,
} from "@wizleap-inc/wiz-ui-constants";
import {
  avatarStyle,
  avatarImageStyle,
  avatarFallbackStyle,
  avatarClickableStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/avatar.css";
import {
  backgroundStyle,
  sizeStyle,
  colorStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import { ref, PropType } from "vue";

defineOptions({
  name: ComponentName.Anchor,
});

interface Props {
  src: string;
  size: SpacingKeys;
  color: ColorKeys;
  bgColor: ColorKeys;
  alt: string;
  fallback: string;
  clickable: boolean;
}

const props = defineProps({
  src: {
    type: String,
    required: true,
  },
  size: {
    type: String as PropType<Props["size"]>,
    required: false,
    default: "xl3",
  },
  color: {
    type: String as PropType<Props["color"]>,
    required: false,
    default: "gray.900",
  },
  bgColor: {
    type: String as PropType<Props["bgColor"]>,
    required: false,
    default: "gray.400",
  },
  alt: {
    type: String,
    required: false,
  },
  fallback: {
    type: String,
    required: false,
  },
  clickable: {
    type: Boolean,
    required: false,
  },
});

interface Emits {
  (event: "click"): void;
}

const emits = defineEmits<Emits>();

const onClick = () => props.clickable && emits("click");

const isImgLoadSuccess = ref(true);

const onError = () => {
  isImgLoadSuccess.value = false;
};
</script>

// packages/wiz-ui-react/src/components/base/avatar/components/avatar.tsx
import {
  ColorKeys,
  ComponentName,
  SpacingKeys,
} from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/avatar.css";
import {
  backgroundStyle,
  colorStyle,
  sizeStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import { ComponentProps, ForwardedRef, forwardRef, useState } from "react";

import { BaseProps } from "@/types";
type Props = BaseProps & {
  src: string;
  size?: SpacingKeys;
  color?: ColorKeys;
  bgColor?: ColorKeys;
  alt?: string;
  fallback?: string;
  clickable?: boolean;
} & ComponentProps<"div">;

const Avatar = forwardRef(
  (
    {
      className,
      style,
      src,
      size = "xl3",
      color = "gray.900",
      bgColor = "gray.400",
      alt,
      fallback,
      clickable,
      onClick,
      ...props
    }: Props,
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const [isImgLoadSuccess, setIsLoadSuccess] = useState(true);

    return (
      <div
        ref={ref}
        className={clsx(
          className,
          styles.avatarStyle,
          sizeStyle[size],
          colorStyle[color],
          clickable && styles.avatarClickableStyle
        )}
        style={style}
        {...props}
        role={clickable ? "button" : undefined}
        tabIndex={clickable ? 0 : undefined}
        onClick={(e) => clickable && onClick?.(e)}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") {
            if (!clickable) return;
            if (e.target instanceof HTMLElement) {
              e.stopPropagation();
              e.target.click();
            }
          }
        }}
      >
        {isImgLoadSuccess ? (
          <img
            className={styles.avatarImageStyle}
            src={src}
            alt={alt}
            onError={() => setIsLoadSuccess(false)}
          />
        ) : (
          <div
            className={clsx(
              styles.avatarFallbackStyle,
              backgroundStyle[bgColor]
            )}
          >
            {fallback}
          </div>
        )}
      </div>
    );
  }
);

Avatar.displayName = ComponentName.Avatar;

export const WizAvatar = Avatar;
