// packages/wiz-ui/src/components/organisms/chat-card/chat-card.vue
<template>
  <WizBox
    position="fixed"
    :bottom="
      isOpen
        ? '0'
        : `calc(${THEME.fontSize.xl2} + ${THEME.spacing.md} * 2 - ${floatChatCardHeight}px)`
    "
    right="1.5rem"
    width="20rem"
    :transition="canAnimate ? 'bottom 0.3s ease-in-out' : undefined"
    ref="floatChatCardRef"
  >
    <WizCard shadow>
      <template #mainHeaderArea>
        <WizText color="gray.700" as="span" bold>
          {{ username }}
        </WizText>
        <div v-if="unreadCount" class="wiz-chat-card__unread-count">
          <WizText fontSize="xs" color="white.800" as="span" bold>
            {{ unreadCount }}
          </WizText>
        </div>
      </template>
      <template #subHeaderArea>
        <WizIcon
          size="xl2"
          color="gray.500"
          :icon="isOpen ? WizIExpandMore : WizIExpandLess"
        />
      </template>
      <WizDivider />
      <WizVStack gap="xs" height="320px" overflow="scroll" ref="chatListRef">
        <WizChatItem
          v-for="(item, i) in messages"
          :key="i"
          :content="item"
          :maxChatItemWidth="'192px'"
          :hideReadStatus="hideReadStatus"
          :hideTimestamp="hideTimestamp"
        />
      </WizVStack>
      <template #footer>
        <WizChatForm
          v-model="textValue"
          @submit="onSubmit"
          :placeholder="placeholder"
        />
      </template>
    </WizCard>
    <button class="wiz-chat-card__open-btn" @click="toggleDisplay" />
  </WizBox>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from "vue";

import {
  WizBox,
  WizDivider,
  WizIcon,
  WizText,
  WizVStack,
} from "@/components/atoms";
import { WizIExpandMore, WizIExpandLess } from "@/components/icons";
import { WizCard, WizChatForm, WizChatItem } from "@/components/molecules";
import { THEME } from "@/constants";
import { useZIndex } from "@/hooks";
import { Message } from "@/types/components/chat";

interface Props {
  value: string;
  username: string;
  placeholder?: string;
  messages: Message[];
  isOpen: boolean;
  unreadCount?: number;
  hideReadStatus?: boolean;
  hideTimestamp?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  isOpen: false,
  hideReadStatus: false,
  hideTimestamp: false,
});

interface Emit {
  (e: "input", value: string): void;
  (e: "submit"): void;
  (e: "toggleDisplay"): void;
}

const emits = defineEmits<Emit>();

const { nextZIndex } = useZIndex();

const canAnimate = ref(false);

const floatChatCardHeight = ref(0);
const floatChatCardRef = ref<InstanceType<typeof WizBox>>();
const chatListRef = ref<InstanceType<typeof WizVStack>>();

onMounted(() => {
  if (floatChatCardRef.value) {
    floatChatCardHeight.value = floatChatCardRef.value.$el.clientHeight;
  }
  setTimeout(() => {
    canAnimate.value = true;
  }, 0);
  if (chatListRef.value) {
    chatListRef.value.$el.scrollTo(0, chatListRef.value.$el.scrollHeight);
  }
});

watch(props.messages, () => {
  nextTick(() => {
    if (chatListRef.value) {
      chatListRef.value.$el.scrollTo(0, chatListRef.value.$el.scrollHeight);
    }
  });
});

const textValue = computed({
  get: () => props.value,
  set: (value) => emits("input", value),
});

const onSubmit = () => emits("submit");

const toggleDisplay = () => emits("toggleDisplay");

const zIndex = nextZIndex();
const titleHeight = THEME.spacing.xl;
const titlePadding = THEME.spacing.md;
const green800 = THEME.color.green[800];
const spacingMax = THEME.spacing.max;
const fontSizeXl = THEME.fontSize.xl;
</script>

<style lang="scss" scoped>
.wiz-chat-card {
  &__open-btn {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: calc(v-bind(titleHeight) + v-bind(titlePadding) * 2);
    border: none;
    cursor: pointer;
    background: transparent;
    z-index: v-bind(zIndex);
  }

  &__unread-count {
    display: flex;
    align-items: center;
    justify-content: center;
    width: v-bind(fontSizeXl);
    height: v-bind(fontSizeXl);
    border-radius: v-bind(spacingMax);
    background: v-bind(green800);
  }
}
</style>

// packages/wiz-ui-react/src/components/custom/chat/components/chat-card.tsx
import { ComponentName, THEME } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/customs/chat-card.css";
import { formatDateToMonthDayWeek } from "@wizleap-inc/wiz-ui-utils";
import {
  ComponentProps,
  FC,
  Fragment,
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from "react";

import {
  WizBox,
  WizCard,
  WizDivider,
  WizHStack,
  WizIExpandLess,
  WizIExpandMore,
  WizIcon,
  WizSelectBox,
  WizTag,
  WizText,
  WizVStack,
} from "@/components";

import { DisplayMessage, Message } from "./types";

import { WizChatItem, WizChatForm } from ".";

const TOGGLE_ANIMATION_DURATION = 300;

type Props = {
  textValue: string;
  username: string;
  placeholder?: string;
  messages: Message[];
  isOpen?: boolean;
  haveNewMessage?: boolean;
  formRows?: number;
  typingUsername?: string;
  status?: number | null;
  statusOptions?: ComponentProps<typeof WizSelectBox>["options"];
  statusPlaceholder?: string;
  onChangeStatus?: (status: number | null) => void;
  onChangeTextValue: (value: string) => void;
  onSubmit: () => void;
  onToggleOpen: () => void;
};

const ChatCard: FC<Props> = ({
  textValue,
  username,
  placeholder,
  messages,
  isOpen = false,
  haveNewMessage,
  formRows,
  typingUsername,
  status,
  statusOptions,
  statusPlaceholder,
  onChangeStatus,
  onChangeTextValue,
  onSubmit,
  onToggleOpen,
}) => {
  const wrapperBoxRef = useRef<HTMLDivElement>(null);
  const listBoxRef = useRef<HTMLDivElement>(null);
  const [wrapperHeight, setWrapperHeight] = useState(0);

  const displayMessages = useMemo(() => {
    const displayMessages: DisplayMessage[] = [];
    messages.forEach((message) => {
      const date = new Date(message.time);
      const displayMessage = displayMessages.find(
        (displayMessage) =>
          displayMessage.date.getFullYear() === date.getFullYear() &&
          displayMessage.date.getMonth() === date.getMonth() &&
          displayMessage.date.getDate() === date.getDate()
      );
      if (displayMessage) {
        displayMessage.contents.push(message);
      } else {
        displayMessages.push({
          date,
          contents: [message],
        });
      }
    });
    return displayMessages;
  }, [messages]);

  const [isToggleAnimating, setIsToggleAnimating] = useState(false);
  const handleClickToggleButton = useCallback(() => {
    setIsToggleAnimating(true);
    setTimeout(() => setIsToggleAnimating(false), TOGGLE_ANIMATION_DURATION);
    onToggleOpen();
  }, [onToggleOpen]);

  useLayoutEffect(() => {
    const wrapperBox = wrapperBoxRef.current;
    if (!wrapperBox) {
      return;
    }
    // ちらつき防止の為最初に一回計算する
    setWrapperHeight(wrapperBox.clientHeight);
    const wrapperObserver = new ResizeObserver(() => {
      setWrapperHeight(wrapperBox.clientHeight);
    });
    wrapperObserver.observe(wrapperBox);
    return () => {
      wrapperObserver.disconnect();
    };
  }, []);

  useEffect(() => {
    // リスト下部までスクロール
    const listBox = listBoxRef.current;
    if (listBox && isOpen) {
      listBox.scrollTo(0, listBox.scrollHeight);
    }
  }, [isOpen, messages]);

  return (
    <WizBox
      ref={wrapperBoxRef}
      position="fixed"
      right="1.5rem"
      bottom={
        isOpen
          ? "0"
          : `calc(${THEME.fontSize.xl2} + ${THEME.spacing.md} * 2 - ${wrapperHeight}px)`
      }
      transition={
        isToggleAnimating
          ? `bottom ${TOGGLE_ANIMATION_DURATION}ms ease-in-out`
          : undefined
      }
      width="20rem"
      zIndex="floating"
    >
      <WizCard
        shadow
        align="stretch"
        mainHeaderArea={
          <WizHStack align="center" gap="xs2">
            <WizText color="gray.700" as="span" bold>
              {username}
            </WizText>
            {haveNewMessage && (
              <WizBox
                width={THEME.fontSize.md}
                height={THEME.fontSize.md}
                bgColor="red.800"
                round="max"
              />
            )}
          </WizHStack>
        }
        subHeaderArea={
          <WizIcon
            size="xl2"
            color="gray.500"
            icon={isOpen ? WizIExpandMore : WizIExpandLess}
          />
        }
        footerArea={
          <WizVStack width="100%" justify="end" gap="xs">
            <WizChatForm
              value={textValue}
              onChange={onChangeTextValue}
              onSubmit={onSubmit}
              placeholder={placeholder}
              formRows={formRows}
            />
            {status !== undefined && statusOptions !== undefined && (
              <WizHStack wrap={false}>
                <WizSelectBox
                  options={statusOptions}
                  value={status}
                  onChange={(selectedValue) => onChangeStatus?.(selectedValue)}
                  placeholder={statusPlaceholder}
                  expand
                />
                <div
                  style={{
                    width: THEME.spacing.xl4,
                    flexShrink: 0,
                  }}
                />
              </WizHStack>
            )}
            {typingUsername && (
              <WizText color="gray.600" as="p" fontSize="xs2">
                <WizText as="span" bold fontSize="xs2" color="gray.700">
                  {typingUsername}
                </WizText>
                さんが入力しています...
              </WizText>
            )}
          </WizVStack>
        }
      >
        <WizDivider />
        <WizBox overflowY="scroll" ref={listBoxRef}>
          <WizVStack gap="xs" py="xs" height="320px" wrap={false}>
            {displayMessages.map(({ date, contents }, i) => {
              const messagesKey = `${date.toDateString()}-${i}`;
              return (
                <Fragment key={messagesKey}>
                  <WizHStack justify="center">
                    <WizTag
                      label={formatDateToMonthDayWeek(date)}
                      variant="mono"
                      fontSize="xs2"
                    />
                  </WizHStack>
                  {contents.map((content, j) => (
                    <WizChatItem
                      key={`${messagesKey}-${i}-${j}`}
                      content={content}
                      maxChatItemWidth="192px"
                    />
                  ))}
                </Fragment>
              );
            })}
          </WizVStack>
        </WizBox>
      </WizCard>
      <button
        className={styles.chatCardOpenButtonStyle}
        onClick={handleClickToggleButton}
      />
    </WizBox>
  );
};

ChatCard.displayName = ComponentName.ChatCard;

export const WizChatCard = ChatCard;
