// packages/wiz-ui-next/src/components/base/inputs/timepicker/time-picker.vue
<template>
  <WizPopupContainer>
    <div
      :class="[
        timePickerStyle,
        inputBorderStyle[state],
        disabled && timePickerDisabledStyle,
        timePickerCursorStyle[timePickerCursor],
      ]"
    >
      <div
        :class="[
          timePickerBoxStyle,
          timePickerBoxColorStyle[timePickerBoxColor],
        ]"
        :style="{ width }"
        @click="toggleTimepicker"
      >
        <WizHStack gap="sm" align="center" height="100%">
          <WizIcon size="xl2" color="gray.500" :icon="WizISchedule" />
          <span>{{ modelValue || placeholder }}</span>
        </WizHStack>
      </div>
      <WizPopup
        :isOpen="openTimepicker"
        @onClose="openTimepicker = false"
        layer="popover"
        gap="xs"
      >
        <div :class="timePickerSelectorStyle">
          <WizHStack overflow="none" gap="xs2">
            <WizVStack
              :class="timePickerScrollStyle"
              height="8rem"
              gap="xs2"
              align="center"
              overflow="auto"
              ><div
                :class="[
                  timePickerSelectorOptionStyle,
                  timePickerSelectorOptionTypeStyle,
                ]"
              >
                時
              </div>
              <div
                v-for="(option, key) in hourOptions"
                :key="'option' + key"
                :class="[
                  timePickerSelectorOptionStyle,
                  timePickerSelectorOptionItemStyle,
                  option === selectedHour &&
                    timePickerSelectorOptionItemSelectedStyle,
                  timePickerSelectorOptionItemColorStyle[
                    timePickerSelectorOptionItemColor(option === selectedHour)
                  ],
                ]"
                @click="onSelect(option, true)"
              >
                {{ option }}
              </div>
            </WizVStack>
            <WizVStack gap="xs2">
              <WizDivider direction="vertical" />
            </WizVStack>
            <WizVStack gap="xs2" align="center" justify="center">
              <div
                :class="[
                  timePickerSelectorOptionStyle,
                  timePickerSelectorOptionTypeStyle,
                ]"
              >
                分
              </div>
              <div
                v-for="(option, key) in minuteOptions"
                :key="'option' + key"
                :class="[
                  timePickerSelectorOptionStyle,
                  timePickerSelectorOptionItemStyle,
                  option === selectedMinute &&
                    timePickerSelectorOptionItemSelectedStyle,
                  timePickerSelectorOptionItemColorStyle[
                    timePickerSelectorOptionItemColor(option === selectedMinute)
                  ],
                ]"
                @click="onSelect(option)"
              >
                {{ option }}
              </div>
            </WizVStack>
          </WizHStack>
        </div>
      </WizPopup>
    </div>
  </WizPopupContainer>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  timePickerStyle,
  timePickerDisabledStyle,
  timePickerCursorStyle,
  timePickerBoxStyle,
  timePickerBoxColorStyle,
  timePickerScrollStyle,
  timePickerSelectorStyle,
  timePickerSelectorOptionStyle,
  timePickerSelectorOptionTypeStyle,
  timePickerSelectorOptionItemStyle,
  timePickerSelectorOptionItemSelectedStyle,
  timePickerSelectorOptionItemColorStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/time-picker-input.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { ref, computed, inject } from "vue";

import { WizIcon, WizDivider, WizHStack, WizVStack } from "@/components";
import { WizISchedule } from "@/components/icons";
import { formControlKey } from "@/hooks/use-form-control-provider";

import { WizPopup, WizPopupContainer } from "../../popup";

defineOptions({
  name: ComponentName.TimePicker,
});

const props = defineProps({
  modelValue: {
    type: String,
    required: true,
  },
  placeholder: {
    type: String,
    required: false,
    default: "時間を選択",
  },
  width: {
    type: String,
    required: false,
    default: "10rem",
  },
  disabled: {
    type: Boolean,
    required: false,
    default: false,
  },
});

const openTimepicker = ref(false);
const selectedHour = ref("");
const selectedMinute = ref("");

const hourOptions = [...Array(24).keys()].map((val) => String(val));
const minuteOptions = ["00", "15", "30", "45"];

const toggleTimepicker = () => {
  if (props.disabled) {
    return;
  }
  openTimepicker.value = !openTimepicker.value;
};

interface Emit {
  (e: "update:modelValue", value: string): void;
}
const emit = defineEmits<Emit>();

const onSelect = (inputValue: string, isHour = false) => {
  let defaultValue =
    props.modelValue.length > 0 ? props.modelValue.split(":") : ["0", "00"];

  // 時間の方でセットする場合
  if (isHour) {
    defaultValue[0] = inputValue;
    selectedHour.value = inputValue;
  } else {
    defaultValue[1] = inputValue;
    selectedMinute.value = inputValue;
  }
  emit("update:modelValue", defaultValue.join(":"));
};

const timePickerCursor = computed(() =>
  props.disabled ? "disabled" : "default"
);

const timePickerBoxColor = computed(() =>
  props.modelValue ? "selected" : "default"
);

const timePickerSelectorOptionItemColor = (isSelected: boolean) =>
  isSelected ? "selected" : "default";

const width = computed(() => props.width);

// Form Control
const form = inject(formControlKey);
const isError = computed(() => (form ? form.isError.value : false));

const state = computed(() => {
  if (isError.value) return "error";
  if (openTimepicker.value) return "active";
  return "default";
});
</script>

// packages/wiz-ui-react/src/components/base/inputs/time-picker/components/time-picker.tsx
import { ComponentName, THEME } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/time-picker-input.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import { useContext, useRef, useState } from "react";

import {
  WizDivider,
  WizHStack,
  WizIcon,
  WizPopup,
  WizVStack,
} from "@/components";
import { FormControlContext } from "@/components/custom/form/form-control-context";
import { WizISchedule } from "@/components/icons";

type Props = {
  time: string;
  placeholder?: string;
  width?: string;
  disabled?: boolean;
  isDirectionFixed?: boolean;
  onChange: (time: string) => void;
};

const hourOptions = [...Array(24).keys()].map((val) => String(val));
const minuteOptions = ["00", "15", "30", "45"];

const _TimePicker = ({
  time,
  placeholder = "時間を選択",
  width = "10rem",
  disabled = false,
  isDirectionFixed = false,
  onChange,
}: Props) => {
  const [openTimePicker, setOpenTimePicker] = useState(false);
  const [selectedHour, setSelectedHour] = useState("");
  const [selectedMinute, setSelectedMinute] = useState("");
  const anchor = useRef<HTMLDivElement | null>(null);

  const toggleTimePicker = () => {
    if (disabled) return;
    setOpenTimePicker(!openTimePicker);
  };

  const onSelect = (inputValue: string, isHour: boolean) => {
    const defaultValue = time.length > 0 ? time.split(":") : ["0", "00"];
    if (isHour) {
      defaultValue[0] = inputValue;
      setSelectedHour(inputValue);
    } else {
      defaultValue[1] = inputValue;
      setSelectedMinute(inputValue);
    }
    onChange(defaultValue.join(":"));
  };

  const timePickerCursor = disabled ? "disabled" : "default";
  const timePickerBoxColor = time ? "selected" : "default";
  const timePickerSelectorOptionItemColor = (isSelected: boolean) =>
    isSelected ? "selected" : "default";

  const formControl = useContext(FormControlContext);
  const state = (() => {
    if (formControl.error) return "error";
    if (openTimePicker) return "active";
    return "default";
  })();

  return (
    <>
      <div
        ref={anchor}
        className={clsx([
          styles.timePickerStyle,
          inputBorderStyle[state],
          disabled && styles.timePickerDisabledStyle,
          styles.timePickerCursorStyle[timePickerCursor],
        ])}
      >
        <div
          className={clsx(
            styles.timePickerBoxStyle,
            styles.timePickerBoxColorStyle[timePickerBoxColor]
          )}
          style={{ width }}
          onClick={toggleTimePicker}
        >
          <WizHStack gap="sm" align="center" height="100%">
            <WizIcon size="xl2" color="gray.500" icon={WizISchedule} />
            <span>{time || placeholder}</span>
          </WizHStack>
        </div>
      </div>

      <WizPopup
        isOpen={openTimePicker}
        anchorElement={anchor}
        shadow={true}
        isDirectionFixed={isDirectionFixed}
        direction="bottomLeft"
        gap="sm"
        onClose={() => setOpenTimePicker(false)}
      >
        <div
          style={{
            height: "100%",
            padding: THEME.spacing.xs,
            background: THEME.color.white["800"],
            borderRadius: THEME.spacing.xs2,
            boxSizing: "border-box",
          }}
        >
          <WizHStack overflow="none" gap="xs2">
            {/* hh  */}
            <div
              className={styles.timePickerScrollStyle}
              style={{
                display: "flex",
                flexDirection: "column",
                overflow: "auto",
                height: "8rem",
                alignItems: "center",
                gap: THEME.spacing.xs2,
              }}
            >
              <div
                className={clsx(
                  styles.timePickerSelectorOptionStyle,
                  styles.timePickerSelectorOptionTypeStyle
                )}
              >
                時
              </div>
              {hourOptions.map((option) => (
                <div
                  key={"hh" + option}
                  className={clsx([
                    styles.timePickerSelectorOptionStyle,
                    styles.timePickerSelectorOptionItemStyle,
                    option === selectedHour &&
                      styles.timePickerSelectorOptionItemSelectedStyle,
                    styles.timePickerSelectorOptionItemColorStyle[
                      timePickerSelectorOptionItemColor(option === selectedHour)
                    ],
                  ])}
                  onClick={() => onSelect(option, true)}
                >
                  {option}
                </div>
              ))}
            </div>

            {/* ｜ */}
            <WizVStack gap="xs2">
              <WizDivider direction="vertical" />
            </WizVStack>

            {/* mm */}
            <WizVStack gap="xs2" align="center" justify="center">
              <div
                className={clsx(
                  styles.timePickerSelectorOptionStyle,
                  styles.timePickerSelectorOptionTypeStyle
                )}
              >
                分
              </div>
              {minuteOptions.map((option) => (
                <div
                  key={"mm" + option}
                  className={clsx([
                    styles.timePickerSelectorOptionStyle,
                    styles.timePickerSelectorOptionItemStyle,
                    option === selectedMinute &&
                      styles.timePickerSelectorOptionItemSelectedStyle,
                    styles.timePickerSelectorOptionItemColorStyle[
                      timePickerSelectorOptionItemColor(
                        option === selectedMinute
                      )
                    ],
                  ])}
                  onClick={() => onSelect(option, false)}
                >
                  {option}
                </div>
              ))}
            </WizVStack>
          </WizHStack>
        </div>
      </WizPopup>
    </>
  );
};

_TimePicker.displayName = ComponentName.TimePicker;

export const WizTimePicker = _TimePicker;
