// packages/wiz-ui-react/src/components/custom/chat/components/chat-form.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import { FC } from "react";

import { WizHStack, WizISend, WizIconButton, WizTextArea } from "@/components";

type Props = {
  value: string;
  disabled?: boolean;
  placeholder?: string;
  formRows?: number;
  onChange: (value: string) => void;
  onSubmit: () => void;
};

const ChatForm: FC<Props> = ({
  value,
  disabled,
  placeholder,
  formRows,
  onChange,
  onSubmit,
}) => {
  return (
    <WizHStack align="center" gap="xs" nowrap>
      <WizTextArea
        value={value}
        placeholder={placeholder}
        disabled={disabled}
        rows={formRows}
        expand
        onChange={onChange}
      />
      <div>
        <WizIconButton icon={WizISend} disabled={disabled} onClick={onSubmit} />
      </div>
    </WizHStack>
  );
};

ChatForm.displayName = ComponentName.ChatForm;

export const WizChatForm = ChatForm;

// packages/wiz-ui/src/components/molecules/chat-form/chat-form.vue
<template>
  <WizHStack align="center" gap="xs">
    <WizTextArea
      v-model="textValue"
      :placeholder="placeholder"
      name="chat-form__textarea"
      :disabled="disabled"
      expand
    />
    <div>
      <WizIconButton :icon="WizISend" :disabled="disabled" @click="onSubmit" />
    </div>
  </WizHStack>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";

import { WizHStack, WizIconButton, WizTextArea } from "@/components/atoms";
import { WizISend } from "@/components/icons";

interface Props {
  disabled?: boolean;
  placeholder?: string;
  value: string;
}

const props = defineProps<Props>();

interface Emit {
  (e: "input", value: string): void;
  (e: "submit"): void;
}
const emits = defineEmits<Emit>();

const value = ref("");
const textValue = computed({
  get: () => props.value,
  set: (value) => emits("input", value),
});

const onSubmit = () => emits("submit");
</script>
