// packages/wiz-ui-react/src/components/base/inputs/password/components/password.tsx
import { ARIA_LABELS } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/password-input.css";
import clsx from "clsx";
import { memo, useState } from "react";
type Props = {
  id?: string;
  value: string;
  placeholder?: string;
  disabled?: boolean;
  expand?: boolean;
  width?: string;
  onChange?: (value: string) => void;
};

const _PasswordInput = ({
  id,
  value,
  placeholder,
  disabled,
  expand,
  width,
  ...props
}: Props) => {
  // const isError = useFormCOntrolProvider()
  const isError = useState(false);
  const [isPasswordVisible, setIsPasswordVisible] = useState(false);
  const computedExpand = expand ? "expand" : "default";

  return (
    <div
      className={clsx(
        styles.passwordStyle,
        styles.passwordExpandStyle[computedExpand]
      )}
    >
      <input // PrivateBaseInput
        placeholder={placeholder}
        id={id}
        type={isPasswordVisible ? "text" : "password"}
        value={value}
        disabled={disabled}
        width={width}
        onChange={(e) => {
          props.onChange?.(e.target.value);
        }}
        // error={isError}
        // space-type="right"
      />
      <button
        aria-label={ARIA_LABELS.PASSWORD_VISIBLE_TOGGLE}
        className={styles.passwordVisibleIconStyle}
        onClick={() => setIsPasswordVisible(!isPasswordVisible)}
      >
        {/* <WizIEye :class="isPasswordVisible && passwordVisibleIconActiveStyle" />  */}
      </button>
    </div>
  );
};
export const WizPasswordInput = memo(_PasswordInput);

// packages/wiz-ui-next/src/components/base/inputs/password/password.vue
<template>
  <div
    :class="[styles.passwordStyle, styles.passwordExpandStyle[computedExpand]]"
  >
    <PrivateBaseInput
      v-model="passwordValue"
      :placeholder="placeholder"
      :id="id"
      :disabled="disabled"
      :expand="expand"
      :width="width"
      :error="isError"
      :type="isPasswordVisible ? 'text' : 'password'"
      space-type="right"
    />
    <button
      :aria-label="ARIA_LABELS.PASSWORD_VISIBLE_TOGGLE"
      :class="styles.passwordVisibleIconStyle"
      @click="isPasswordVisible = !isPasswordVisible"
    >
      <WizIEye
        :class="isPasswordVisible && styles.passwordVisibleIconActiveStyle"
      />
    </button>
  </div>
</template>

<script setup lang="ts">
import { ARIA_LABELS, ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/password-input.css";
import { computed, ref, inject } from "vue";

import { WizIEye } from "@/components";
import { formControlKey } from "@/hooks/use-form-control-provider";

import { PrivateBaseInput } from "../base";

defineOptions({
  name: ComponentName.PasswordInput,
});

interface Emit {
  (e: "update:modelValue", value: string): void;
}

const props = defineProps({
  id: {
    type: String,
    required: false,
  },
  modelValue: {
    type: String,
    required: true,
  },
  placeholder: {
    type: String,
    required: false,
  },
  disabled: {
    type: Boolean,
    required: false,
  },
  expand: {
    type: Boolean,
    required: false,
  },
  width: {
    type: String,
    required: false,
  },
});

const emit = defineEmits<Emit>();

const isPasswordVisible = ref(false);

const passwordValue = computed({
  get: () => props.modelValue,
  set: (value) => emit("update:modelValue", value),
});

const computedExpand = computed(() => (props.expand ? "expand" : "default"));

// Form Control
const form = inject(formControlKey);
const isError = computed(() => (form ? form.isError.value : false));
</script>
