// packages/wiz-ui-next/src/components/base/message-box/message-box.vue
<template>
  <div
    :class="[
      messageBoxStyle,
      messageBoxWidthStyle[computedWidth],
      messageBoxVariantStyle[variant],
      short && messageBoxShortStyle,
    ]"
  >
    <component
      :is="icon"
      v-if="icon"
      :class="[messageBoxIconStyle, messageBoxIconFillStyle[variant]]"
    />
    <WizVStack gap="xs">
      <div :class="messageBoxTitleStyle">{{ title }}</div>
      <div v-if="hasDefaultSlot" :class="messageBoxBodyStyle">
        <slot />
      </div>
    </WizVStack>
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  messageBoxBodyStyle,
  messageBoxIconFillStyle,
  messageBoxIconStyle,
  messageBoxShortStyle,
  messageBoxStyle,
  messageBoxTitleStyle,
  messageBoxVariantStyle,
  messageBoxWidthStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/message-box.css";
import { computed, PropType, useSlots } from "vue";

import { WizVStack } from "@/components";
import type { TIcon } from "@/components/icons";

defineOptions({
  name: ComponentName.MessageBox,
});

const props = defineProps({
  title: {
    type: String,
    required: true,
  },
  variant: {
    type: String as PropType<"information" | "caution" | "warning">,
    required: false,
    default: "information",
  },
  icon: {
    type: Object as PropType<TIcon>,
    required: false,
  },
  expand: {
    type: Boolean,
    required: false,
    default: false,
  },
  short: {
    type: Boolean,
    required: false,
    default: false,
  },
});

const computedWidth = computed(() => {
  return props.expand ? "expand" : "default";
});

const slots = useSlots();
const hasDefaultSlot = !!slots.default;
</script>

// packages/wiz-ui-react/src/components/base/message-box/components/message-box.tsx
import { ColorKeys, ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/message-box.css";
import clsx from "clsx";
import { ForwardedRef, ReactNode, forwardRef } from "react";

import { TIcon, WizIcon, WizVStack } from "@/components";
import { BaseProps } from "@/types";

const iconFontColor: Record<string, ColorKeys> = {
  information: "green.800",
  caution: "yellow.800",
  warning: "red.800",
};

type Props = BaseProps & {
  title: string;
  variant?: "information" | "caution" | "warning";
  icon?: TIcon;
  expand?: boolean;
  short?: boolean;
  children?: ReactNode;
};

const MessageBox = forwardRef(
  (
    {
      className,
      style,
      title,
      variant = "information",
      icon,
      expand = false,
      short = false,
      children,
    }: Props,
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const width = expand ? "expand" : "default";
    return (
      <div
        ref={ref}
        className={clsx(
          className,
          styles.messageBoxStyle,
          styles.messageBoxWidthStyle[width],
          styles.messageBoxVariantStyle[variant],
          short && styles.messageBoxShortStyle
        )}
        style={style}
      >
        {icon && (
          <div className={styles.messageBoxIconStyle}>
            <WizIcon icon={icon} color={iconFontColor[variant]} />
          </div>
        )}
        <WizVStack gap="xs">
          <div className={styles.messageBoxTitleStyle}>{title}</div>
          {children && !short && (
            <div className={styles.messageBoxBodyStyle}>{children}</div>
          )}
        </WizVStack>
      </div>
    );
  }
);

MessageBox.displayName = ComponentName.MessageBox;

export const WizMessageBox = MessageBox;
