// packages/wiz-ui-react/src/components/base/step-bar/components/step-line.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/step-bar.css";
import clsx from "clsx";
import { FC } from "react";

type Props = {
  active?: boolean;
  isFirst: boolean;
  className?: string;
};

const StepLine: FC<Props> = ({ active, isFirst, className }: Props) => (
  <span
    className={clsx(
      styles.stepLineStyle,
      styles.stepLineBackgroundStyle[active ? "active" : "inactive"],
      styles.stepLineWidthStyle[isFirst ? "first" : "default"],
      className
    )}
  />
);

StepLine.displayName = ComponentName.StepLine;

export const WizStepLine = StepLine;

// packages/wiz-ui-next/src/components/base/step-bar/step-line.vue
<template>
  <span
    class="wiz-progress-line"
    :class="[
      styles.stepLineStyle,
      styles.stepLineBackgroundStyle[active ? 'active' : 'inactive'],
      styles.stepLineWidthStyle[isFirst ? 'first' : 'default'],
    ]"
  />
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/step-bar.css";

defineOptions({
  name: ComponentName.ProgressLine,
});

defineProps({
  active: {
    type: Boolean,
    required: false,
  },
  isFirst: {
    type: Boolean,
    required: true,
  },
});
</script>
