// packages/wiz-ui-react/src/components/base/step-bar/components/step-point.tsx
import { ColorKeys, ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/step-bar.css";
import { FC } from "react";

import { WizICircleCheck, WizIcon } from "@/components";

import { StepStatus } from "./types";

type Props = {
  status: StepStatus;
};

const status2color: Record<string, ColorKeys> = {
  done: "green.800",
  pending: "gray.500",
};

const StepPoint: FC<Props> = ({ status }: Props) => {
  return (
    <span className={styles.stepPointStyle}>
      <span className={styles.stepPointValueStyle}>
        <WizIcon
          icon={WizICircleCheck}
          size={"xl6"}
          color={status2color[status]}
        />
      </span>
    </span>
  );
};

StepPoint.displayName = ComponentName.StepPoint;

export const WizStepPoint = StepPoint;

// packages/wiz-ui-next/src/components/base/step-bar/step-point.vue
<template>
  <span :class="[stepPointStyle]">
    <span :class="stepPointValueStyle">
      <WizIcon
        :icon="WizICircleCheck"
        :size="'xl6'"
        :color="status === 'done' ? 'green.800' : 'gray.500'"
      />
    </span>
  </span>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  stepPointStyle,
  stepPointValueStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/step-bar.css";
import { PropType } from "vue";

import { WizIcon, WizICircleCheck } from "@/components";

import type { StepStatus } from "./types";

defineOptions({
  name: ComponentName.StepPoint,
});

defineProps({
  status: {
    type: String as PropType<StepStatus>,
    required: true,
  },
});
</script>
