// packages/wiz-ui-react/src/components/base/message-box/components/message-box.tsx
import { ColorKeys, ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/message-box.css";
import clsx from "clsx";
import { ForwardedRef, ReactNode, forwardRef } from "react";

import { TIcon, WizIcon, WizVStack } from "@/components";

const iconFontColor: Record<string, ColorKeys> = {
  information: "green.800",
  caution: "yellow.800",
  warning: "red.800",
};

type Props = {
  title: string;
  variant?: "information" | "caution" | "warning";
  icon?: TIcon;
  expand?: boolean;
  children?: ReactNode;
};

const MessageBox = forwardRef(
  (
    { title, variant = "information", icon, expand = false, children }: Props,
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const width = expand ? "expand" : "default";
    return (
      <div
        ref={ref}
        className={clsx(
          styles.messageBoxStyle,
          styles.messageBoxWidthStyle[width],
          styles.messageBoxVariantStyle[variant]
        )}
      >
        {icon && (
          <div className={styles.messageBoxIconStyle}>
            <WizIcon icon={icon} color={iconFontColor[variant]} />
          </div>
        )}
        <div>
          <WizVStack gap="xs">
            <div className={styles.messageBoxTitleStyle}>{title}</div>
            {children && <div>{children}</div>}
          </WizVStack>
        </div>
      </div>
    );
  }
);

MessageBox.displayName = ComponentName.MessageBox;

export const WizMessageBox = MessageBox;

// packages/wiz-ui/src/components/base/message-box/message-box.vue
<template>
  <div
    :class="[
      messageBoxStyle,
      messageBoxWidthStyle[computedWidth],
      messageBoxVariantStyle[variant],
    ]"
  >
    <component v-if="icon" :is="icon" :class="messageBoxIconStyle" />
    <div>
      <div :class="messageBoxTitleStyle">{{ title }}</div>
      <slot></slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  messageBoxStyle,
  messageBoxWidthStyle,
  messageBoxVariantStyle,
  messageBoxIconStyle,
  messageBoxTitleStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/message-box.css";
import { computed } from "vue";

import type { TIcon } from "@/components/icons";

defineOptions({
  name: ComponentName.MessageBox,
});
interface Props {
  variant?: "information" | "caution" | "warning";
  title: string;
  icon?: TIcon;
  expand?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  variant: "information",
  title: "",
  expand: false,
});

const computedWidth = computed(() => {
  return props.expand ? "expand" : "default";
});
</script>
