// packages/wiz-ui-react/src/components/base/inputs/upload/components/upload-display.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/upload-display.css";
import clsx from "clsx";
import { FC } from "react";

import {
  WizHStack,
  WizIAttachFile,
  WizICircleCheck,
  WizLineGraph,
  WizVStack,
} from "@/components";

type Props = {
  files: File[];
  uploadingFileCount: number;
  completedFileCount: number;
  progress: number;
  isUploaded: boolean;
  isUploading: boolean;
  multiple: boolean;
};

const UploadDisplay: FC<Props> = ({
  files,
  uploadingFileCount,
  completedFileCount,
  progress,
  isUploaded,
  isUploading,
  multiple,
}) => {
  const shouldShowFileList = multiple || (!multiple && !isUploading);

  const shouldFadeIn = (index: number) => {
    const uploadedFileCount = files.length - uploadingFileCount;
    if (
      (uploadingFileCount === 1 && index === files.length - 1) ||
      files.length === uploadingFileCount ||
      index >= uploadedFileCount
    ) {
      return true;
    }
    return false;
  };

  return (
    <WizVStack gap="sm">
      {isUploading && (
        <div
          className={clsx(
            styles.uploadDisplayStyle,
            isUploaded && styles.uploadDisplayFadeOutStyle
          )}
        >
          <span>
            {isUploaded
              ? "ファイルアップロード完了"
              : `ファイルアップロード中…（${completedFileCount}/${uploadingFileCount}）`}
          </span>
          <WizHStack align="center" gap="xs" nowrap>
            <WizLineGraph percentage={progress} />
            <div
              className={clsx(
                styles.circleCheckIconStyle,
                isUploaded
                  ? styles.circleCheckIconCompletedStyle
                  : styles.circleCheckIconDefaultStyle
              )}
              style={{
                fontSize: "1.5rem",
              }}
            >
              <WizICircleCheck />
            </div>
          </WizHStack>
        </div>
      )}
      {shouldShowFileList &&
        files.map((file, i) => (
          <div
            key={`${i}-${file.name}`}
            className={clsx(
              styles.uploadDisplayStyle,
              shouldFadeIn(i) && styles.uploadDisplayFadeInStyle
            )}
          >
            <WizHStack align="center" gap="xs2">
              <div
                className={styles.attachFileIconStyle}
                style={{ fontSize: "1.5rem" }}
              >
                <WizIAttachFile />
              </div>
              <span>{file.name}</span>
            </WizHStack>
          </div>
        ))}
    </WizVStack>
  );
};

UploadDisplay.displayName = ComponentName.UploadDisplay;

export const WizUploadDisplay = UploadDisplay;

// packages/wiz-ui/src/components/base/inputs/upload/upload-display.vue
<template>
  <WizVStack gap="sm">
    <div
      v-if="isUploading"
      :class="[
        styles.uploadDisplayStyle,
        isUploaded ? styles.uploadDisplayFadeOutStyle : '',
      ]"
    >
      <span>{{
        isUploaded
          ? "ファイルアップロード完了"
          : `ファイルアップロード中…（${completedFileCount}/${uploadingFileCount}）`
      }}</span>
      <WizHStack align="center" gap="xs">
        <WizLineGraph :percentage="progress" />
        <WizICircleCheck
          :class="[
            styles.circleCheckIconStyle,
            isUploaded
              ? styles.circleCheckIconCompletedStyle
              : styles.circleCheckIconDefaultStyle,
          ]"
        />
      </WizHStack>
    </div>
    <template
      v-if="(multiple && fileList.length) || (!multiple && !isUploading)"
    >
      <div
        :class="[
          styles.uploadDisplayStyle,
          isApplyFadeIn(index) ? styles.uploadDisplayFadeInStyle : '',
        ]"
        v-for="(file, index) in Array.from(fileList)"
      >
        <WizHStack align="center" gap="xs2">
          <WizIAttachFile :class="styles.attachFileIconStyle" />
          <span>{{ file.name }}</span>
        </WizHStack>
      </div>
    </template>
  </WizVStack>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/upload-display.css";
import { computed } from "vue";

import { WizLineGraph, WizHStack, WizVStack } from "@/components";
import { WizICircleCheck, WizIAttachFile } from "@/components/icons";

defineOptions({
  name: ComponentName.UploadDisplay,
});

interface Props {
  fileList: File[];
  uploadingFileCount: number;
  completedFileCount: number;
  progress: number;
  isUploaded: boolean;
  isUploading: boolean;
  multiple: boolean;
}
const props = defineProps<Props>();

const isApplyFadeIn = computed(() => {
  return function (index: number) {
    const uploadedFileCount = props.fileList.length - props.uploadingFileCount;
    if (
      (props.uploadingFileCount === 1 && index === props.fileList.length - 1) ||
      props.fileList.length === props.uploadingFileCount ||
      index >= uploadedFileCount
    ) {
      return true;
    }
    return false;
  };
});
</script>
