// packages/wiz-ui-react/src/components/base/inputs/radio/components/radio.tsx
import { SpacingKeys } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/radio-input.css";
import clsx from "clsx";
import { memo } from "react";

import { RadioOption } from "./types";

type Props = {
  options: RadioOption[];
  value: number | null;
  disabled?: boolean;
  direction?: "horizontal" | "vertical";
  gap?: SpacingKeys;
  strikeThrough?: boolean;
  onSelect?: (value: number) => void;
};

export const _Radio = ({
  options,
  value,
  disabled = false,
  direction = "horizontal",
  gap = "xl",
  strikeThrough = false,
  ...props
}: Props) => {
  const radioLabelColor = (isChecked: boolean) =>
    isChecked ? "checked" : "default";

  const radioLabelCursor = (optionDisabled?: boolean) =>
    disabled || optionDisabled ? "disabled" : "default";

  return (
    <div className={styles.radioStyle}>
      {/* WizStack <WizStack :gap="gap" :direction="direction" wrap> */}
      <div>
        {options.map((option) => (
          <div key={option.key}>
            <input
              className={styles.radioInputStyle}
              type="radio"
              name={option.key}
              id={option.key}
              value={option.value}
              disabled={disabled || option.disabled}
              onClick={() => props.onSelect?.(option.value)}
            />
            <label
              className={clsx(
                styles.radioLabelStyle,
                value === option.value && styles.radioLabelCheckedStyle,
                (disabled || option.disabled) && styles.radioLabelDisabledStyle,
                styles.radioLabelColorStyle[
                  radioLabelColor(value === option.value)
                ],
                styles.radioLabelCursorStyle[radioLabelCursor(option.disabled)],
                strikeThrough &&
                  value === option.value &&
                  styles.radioLabelStrikeThrough
              )}
              htmlFor={option.key}
            >
              {option.label}
            </label>
          </div>
        ))}
      </div>
    </div>
  );
};

export const WizRadio = memo(_Radio);

// packages/wiz-ui/src/components/base/inputs/radio/radio.vue
<template>
  <div :class="radioStyle">
    <WizStack :gap="gap" :direction="direction" wrap>
      <div v-for="(option, key) in options" :key="key">
        <input
          :class="radioInputStyle"
          type="radio"
          :name="`radio${key}`"
          :id="`radio${key}`"
          :value="option.value"
          v-model="radioValue"
          :disabled="disabled || option.disabled"
        />
        <label
          :class="[
            radioLabelStyle,
            radioValue === option.value && radioLabelCheckedStyle,
            (disabled || option.disabled) && radioLabelDisabledStyle,
            radioLabelColorStyle[radioLabelColor(radioValue === option.value)],
            radioLabelCursorStyle[radioLabelCursor(option.disabled)],
          ]"
          :for="`radio${key}`"
        >
          {{ option.label }}
        </label>
      </div>
    </WizStack>
  </div>
</template>

<script setup lang="ts">
import { SpacingKeys } from "@wizleap-inc/wiz-ui-constants";
import {
  radioStyle,
  radioInputStyle,
  radioLabelStyle,
  radioLabelCheckedStyle,
  radioLabelDisabledStyle,
  radioLabelColorStyle,
  radioLabelCursorStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/radio-input.css";
import { computed } from "vue";

import WizStack from "@/components/base/stack/stack.vue";

import { RadioOption } from "./types";

interface Props {
  options: RadioOption[];
  value: number;
  disabled?: boolean;
  direction?: "horizontal" | "vertical";
  gap?: SpacingKeys;
}

const props = withDefaults(defineProps<Props>(), {
  disabled: false,
  direction: "horizontal",
  gap: "xl",
});

interface Emit {
  (e: "input", value: number): void;
}

const emit = defineEmits<Emit>();

const radioValue = computed({
  get: () => props.value,
  set: (value) => emit("input", value),
});

const radioLabelColor = (isChecked: boolean) =>
  isChecked ? "checked" : "default";

const radioLabelCursor = (optionDisabled?: boolean) =>
  props.disabled || optionDisabled ? "disabled" : "default";
</script>
