// packages/wiz-ui-next/src/components/base/skeleton/skeleton.vue
<template>
  <div
    :class="isLoading && [skeletonStyle, normalSkeletonStyle]"
    :style="{ width, height }"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  skeletonStyle,
  normalSkeletonStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/skeleton.css";
import { PropType } from "vue";

defineOptions({
  name: ComponentName.Skeleton,
});

defineProps({
  width: {
    type: String as PropType<string>,
    default: "100%",
    required: false,
  },
  height: {
    type: String as PropType<string>,
    default: "100%",
    required: false,
  },
  isLoading: {
    type: Boolean as PropType<boolean>,
    default: true,
    required: false,
  },
});
</script>

// packages/wiz-ui-react/src/components/base/skeleton/components/skeleton.tsx
import { ComponentName, SpacingKeys } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/skeleton.css";
import clsx from "clsx";
import { ReactNode } from "react";

type Props = {
  width?: string;
  height?: string;
  borderRadius?: SpacingKeys;
  isLoading?: boolean;
  children?: ReactNode;
};

const Skeleton = ({
  width = "100%",
  height = "100%",
  borderRadius = "no",
  isLoading = true,
  children,
}: Props) => {
  const className = isLoading
    ? clsx(
        styles.skeletonStyle,
        styles.normalSkeletonStyle,
        styles.borderRadiusStyle[borderRadius]
      )
    : undefined;

  return (
    <div className={className} style={{ width, height }}>
      {children}
    </div>
  );
};

Skeleton.displayName = ComponentName.Skeleton;

export const WizSkeleton = Skeleton;
