// packages/wiz-ui-next/src/components/base/skeleton/skeleton-circle.vue
<template>
  <div
    :class="isLoading && [skeletonStyle, circleSkeletonStyle]"
    :style="{ width: size, height: size }"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  skeletonStyle,
  circleSkeletonStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/skeleton.css";
import { PropType } from "vue";

defineOptions({
  name: ComponentName.SkeletonText,
});

defineProps({
  size: {
    type: String as PropType<string>,
    default: "2.5rem",
    required: false,
  },
  isLoading: {
    type: Boolean as PropType<boolean>,
    default: true,
    required: false,
  },
});
</script>

// packages/wiz-ui-react/src/components/base/skeleton/components/skeleton-circle.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/skeleton.css";
import clsx from "clsx";
import { ReactNode } from "react";

type Props = {
  size: string;
  isLoading?: boolean;
  children?: ReactNode;
};

const SkeletonCircle = ({
  size = "2.5rem",
  isLoading = true,
  children,
}: Props) => {
  const className = isLoading
    ? clsx(styles.skeletonStyle, styles.circleSkeletonStyle)
    : undefined;

  return (
    <div className={className} style={{ width: size, height: size }}>
      {children}
    </div>
  );
};

SkeletonCircle.displayName = ComponentName.SkeletonCircle;

export const WizSkeletonCircle = SkeletonCircle;
