// packages/wiz-ui/src/components/base/skeleton/skeleton-text.vue
<template>
  <div>
    <WizVStack v-if="isLoading" :gap="gap">
      <div v-for="line in lines" :key="line">
        <div
          :class="[
            styles.skeletonStyle,
            styles.normalSkeletonStyle,
            styles.textSkeletonStyle[judgeOrder(line)],
            fontSizeAsHeightStyle[fontSize],
          ]"
        />
      </div>
    </WizVStack>
    <slot v-else />
  </div>
</template>

<script setup lang="ts">
import {
  ComponentName,
  FontSizeKeys,
  SpacingKeys,
} from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/skeleton.css";
import { fontSizeAsHeightStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { PropType } from "vue";

import { WizVStack } from "@/components";

defineOptions({
  name: ComponentName.SkeletonText,
});

const props = defineProps({
  fontSize: {
    type: String as PropType<FontSizeKeys>,
    default: "lg",
    required: false,
  },
  gap: {
    type: String as PropType<SpacingKeys>,
    default: "sm",
    required: false,
  },
  lines: {
    type: Number as PropType<number>,
    default: 1,
    required: false,
  },
  isLoading: {
    type: Boolean as PropType<boolean>,
    default: true,
    required: false,
  },
});

const judgeOrder = (line: number) => {
  if (props.lines === 1) return "noLast";
  return line === props.lines ? "last" : "noLast";
};
</script>

// packages/wiz-ui-react/src/components/base/skeleton/components/skeleton-text.tsx
import {
  ComponentName,
  FontSizeKeys,
  SpacingKeys,
} from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/skeleton.css";
import { fontSizeAsHeightStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import { ReactNode } from "react";

import { WizVStack } from "@/components";

type Props = {
  fontSize?: FontSizeKeys;
  gap?: SpacingKeys;
  lines?: number;
  isLoading?: boolean;
  children?: ReactNode;
};

const SkeletonText = ({
  fontSize = "lg",
  gap = "sm",
  lines = 1,
  isLoading = true,
  children,
}: Props) => {
  const judgeOrder = (line: number) => {
    if (lines === 1) return "noLast";
    return line === lines ? "last" : "noLast";
  };
  const loadingStyle = clsx(
    styles.skeletonStyle,
    styles.normalSkeletonStyle,
    styles.textSkeletonStyle[judgeOrder(1)],
    fontSizeAsHeightStyle[fontSize]
  );
  return (
    <>
      {!isLoading ? (
        children
      ) : (
        <WizVStack gap={gap}>
          {Array.from({ length: lines }, (_, i) => (
            <div key={i} className={loadingStyle} />
          ))}
        </WizVStack>
      )}
    </>
  );
};

SkeletonText.displayName = ComponentName.SkeletonText;

export const WizSkeletonText = SkeletonText;
