// packages/wiz-ui-react/src/components/base/inputs/date-picker/components/date-picker.tsx
import { ARIA_LABELS, ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/date-picker-input.css";
import {
  fillStyle,
  fontSizeStyle,
  inputBorderStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import { formatDateToYYMMDD } from "@wizleap-inc/wiz-ui-utils";
import clsx from "clsx";
import { FC, KeyboardEvent, useContext, useRef, useState } from "react";

import { WizCalendar, WizPopup, WizText } from "@/components";
import { WizIcon } from "@/components/base/icon";
import { WizHStack, WizVStack } from "@/components/base/stack";
import { FormControlContext } from "@/components/custom/form/components/form-control-context";
import {
  WizICalendar,
  WizICancel,
  WizIChevronLeft,
  WizIChevronRight,
} from "@/components/icons";

type Props = {
  date: Date | null;
  placeholder?: string;
  width?: string;
  disabled?: boolean;
  error?: boolean;
  isDirectionFixed?: boolean;
  onChangeDate: (selectedValue: Date | null) => void;
};

const DatePicker: FC<Props> = ({
  date,
  placeholder = "日付を選択",
  width = "10rem",
  disabled = false,
  isDirectionFixed = false,
  onChangeDate,
  error,
}: Props) => {
  const [isHover, setIsHover] = useState(false);
  const [isOpen, setIsOpen] = useState(false);
  const [isFocused, setIsFocused] = useState(false);
  const cancelButtonVisible = !disabled && !!date && (isHover || isFocused);
  const [currentMonth, setCurrentMonth] = useState(date || new Date());
  const moveCalendar = (deltaYear: number, deltaMonth: number) => {
    setCurrentMonth(
      new Date(
        currentMonth.getFullYear() + deltaYear,
        currentMonth.getMonth() + deltaMonth,
        1
      )
    );
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLButtonElement>) => {
    e.preventDefault();
    switch (e.key) {
      case "ArrowUp":
        return moveCalendar(1, 0);
      case "ArrowDown":
        return moveCalendar(-1, 0);
      case "ArrowRight":
        return moveCalendar(0, 1);
      case "ArrowLeft":
        return moveCalendar(0, -1);
      case "Enter":
        return setIsOpen((prev) => !prev);
    }
  };

  const calendar = {
    title: `${currentMonth.getMonth() + 1}月`,
    year: currentMonth.getFullYear(),
    month: currentMonth.getMonth(),
    date: currentMonth.getDate(),
  };
  const formControl = useContext(FormControlContext);
  const borderStyle = (() => {
    if (error || formControl.error) return "error";
    if (isOpen && !disabled) return "active";
    return "default";
  })();
  const variant = (() => {
    if (disabled) return "disabled";
    if (date) return "selected";
    return "default";
  })();
  const wrapperButtonRef = useRef<HTMLButtonElement | null>(null);
  return (
    <>
      <button
        ref={wrapperButtonRef}
        className={clsx(
          styles.datePickerStyle,
          styles.datePickerVariantStyle[variant],
          inputBorderStyle[borderStyle]
        )}
        style={{ width }}
        aria-label={ARIA_LABELS.DATE_PICKER_INPUT}
        disabled={disabled}
        onMouseEnter={() => setIsHover(true)}
        onMouseLeave={() => setIsHover(false)}
        onFocus={() => setIsFocused(true)}
        onBlur={() => setIsFocused(false)}
        onClick={() => setIsOpen((prev) => !prev)}
        onKeyDown={handleKeyDown}
      >
        <WizHStack gap="xs" align="center" height="100%">
          {cancelButtonVisible ? (
            <button
              className={styles.datePickerCancelButtonStyle}
              disabled={disabled}
              onClick={() => onChangeDate(null)}
              aria-label={ARIA_LABELS.DATE_PICKER_CANCEL}
            >
              <WizIcon size="xl2" color="inherit" icon={WizICancel} />
            </button>
          ) : (
            <button
              className={styles.datePickerCancelButtonStyle}
              disabled={disabled}
            >
              <WizIcon size="xl2" color="gray.500" icon={WizICalendar} />
            </button>
          )}
          <span>{(date && formatDateToYYMMDD(date)) || placeholder}</span>
        </WizHStack>
      </button>
      <WizPopup
        isOpen={!disabled && isOpen}
        onClose={() => setIsOpen(false)}
        direction="bottomLeft"
        isDirectionFixed={isDirectionFixed}
        anchorElement={wrapperButtonRef}
      >
        <div className={styles.datePickerSelectorStyle}>
          <WizHStack align="center" my="xs2" px="xs" justify="between">
            <WizHStack align="center" justify="between" gap="xs2">
              <WizText
                as="span"
                fontSize="xs"
                line-height="lg"
                color="gray.700"
              >
                {calendar.year}年
              </WizText>
              <WizVStack>
                <button
                  onClick={() => moveCalendar(1, 0)}
                  className={styles.datePickerYearSelectorItemStyle}
                  aria-label={ARIA_LABELS.YEAR_SELECTOR_NEXT}
                >
                  {/* FIXME: https://github.com/Wizleap-Inc/wiz-ui/issues/758 */}
                  {/* <WizIArrowDropUp /> */}
                  <svg
                    className={clsx(
                      fillStyle["gray.700"],
                      fontSizeStyle["xs2"],
                      styles.datePickerArrowIconStyle
                    )}
                    xmlns="http://www.w3.org/2000/svg"
                    height="1em"
                    width="1em"
                    viewBox="0 96 960 960"
                  >
                    <path d="M406.231 636q-21.616 0-29.808-19.885-8.192-19.884 6.961-35.038l74.77-74.769q5.231-5.231 10.692-7.462 5.462-2.231 11.923-2.231 6.462 0 11.923 2.231 5.462 2.231 10.693 7.462l74.769 74.769q15.154 15.154 6.962 35.038Q576.923 636 555.308 636H406.231Z" />
                  </svg>
                </button>
                <button
                  onClick={() => moveCalendar(-1, 0)}
                  className={styles.datePickerYearSelectorItemStyle}
                  aria-label={ARIA_LABELS.YEAR_SELECTOR_PREV}
                >
                  {/* FIXME: https://github.com/Wizleap-Inc/wiz-ui/issues/758 */}
                  {/* <WizIArrowDropDown /> */}
                  <svg
                    className={clsx(
                      fillStyle["gray.700"],
                      fontSizeStyle["xs2"],
                      styles.datePickerArrowIconStyle
                    )}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 96 960 960"
                    height="1em"
                    width="1em"
                  >
                    <path d="m458.154 645.692-74.77-74.769q-15.153-15.154-6.961-35.038Q384.615 516 406.231 516h149.077q21.615 0 29.808 19.885 8.192 19.884-6.962 35.038l-74.769 74.769q-5.231 5.231-10.693 7.462-5.461 2.231-11.923 2.231-6.461 0-11.923-2.231-5.461-2.231-10.692-7.462Z" />
                  </svg>
                </button>
              </WizVStack>
            </WizHStack>
            <WizText as="span" fontSize="xs" color="gray.700">
              {calendar.title}
            </WizText>
            <div className={styles.datePickerMonthSelectorStyle}>
              <button
                aria-label={ARIA_LABELS.MONTH_SELECTOR_PREV}
                onClick={() => moveCalendar(0, -1)}
                className={styles.datePickerMonthSelectorItemStyle}
              >
                <WizIcon size="md" color="inherit" icon={WizIChevronLeft} />
              </button>
              <button
                aria-label={ARIA_LABELS.MONTH_SELECTOR_NEXT}
                onClick={() => moveCalendar(0, 1)}
                className={styles.datePickerMonthSelectorItemStyle}
              >
                <WizIcon size="md" color="inherit" icon={WizIChevronRight} />
              </button>
            </div>
          </WizHStack>
          <WizCalendar
            activeDates={
              (date && [{ date: date, state: "primary" }]) || undefined
            }
            onClickDate={(date) => onChangeDate(date)}
            currentMonth={currentMonth}
            filledWeeks
          />
        </div>
      </WizPopup>
    </>
  );
};

DatePicker.displayName = ComponentName.DatePicker;

export const WizDatePicker = DatePicker;

// packages/wiz-ui-next/src/components/base/inputs/datepicker/date-picker.vue
<template>
  <WizPopupContainer>
    <button
      :class="[
        datePickerStyle,
        datePickerVariantStyle[variant],
        inputBorderStyle[borderState],
      ]"
      :style="{
        width,
      }"
      @click="toggleDatepicker"
    >
      <WizHStack gap="sm" align="center" height="100%">
        <WizIcon size="xl2" color="gray.500" :icon="WizICalendar" />
        <span>{{ parseValue(calendarValue) || placeholder }}</span>
      </WizHStack>
    </button>
    <WizPopup
      :isOpen="openDatepicker"
      @onClose="openDatepicker = false"
      gap="xs"
    >
      <div :class="datePickerSelectorStyle">
        <WizHStack align="center" my="xs2" px="xs" justify="between">
          <WizText as="span" fontSize="xs" color="gray.700">{{
            currentDateTitle
          }}</WizText>
          <div :class="datePickerMonthSelectorStyle">
            <button
              :class="datePickerMonthSelectorItemStyle"
              @click="clickToPreviousMonth"
            >
              <WizIcon size="md" :icon="WizIChevronLeft" />
            </button>
            <button
              :class="datePickerMonthSelectorItemStyle"
              @click="clickToNextMonth"
            >
              <WizIcon size="md" :icon="WizIChevronRight" />
            </button>
          </div>
        </WizHStack>
        <WizCalendar
          :activeDates="[
            {
              date: calendarValue,
              state: 'primary',
            },
          ]"
          @click="(date) => (calendarValue = date)"
          :currentMonth="currentMonth"
          filledWeeks
        />
      </div>
    </WizPopup>
  </WizPopupContainer>
</template>

<script setup lang="ts">
import {
  datePickerStyle,
  datePickerVariantStyle,
  datePickerSelectorStyle,
  datePickerMonthSelectorStyle,
  datePickerMonthSelectorItemStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/date-picker-input.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { ref, computed, inject } from "vue";

import {
  WizIcon,
  WizHStack,
  WizCalendar,
  WizText,
  WizPopup,
  WizPopupContainer,
} from "@/components";
import {
  WizICalendar,
  WizIChevronLeft,
  WizIChevronRight,
} from "@/components/icons";
import { formControlKey } from "@/hooks/use-form-control-provider";

interface Emit {
  (e: "update:modelValue", value: Date): void;
}

const props = defineProps({
  modelValue: {
    type: Date,
    required: true,
  },
  placeholder: {
    type: String,
    required: false,
    default: "日付を選択",
  },
  width: {
    type: String,
    required: false,
    default: "10rem",
  },
  disabled: {
    type: Boolean,
    required: false,
    default: false,
  },
});

const emit = defineEmits<Emit>();

const defaultCurrentMonth = new Date().setHours(0, 0, 0, 0);
const currentMonth = ref(new Date(defaultCurrentMonth));
const openDatepicker = ref(false);

const toggleDatepicker = () => {
  if (props.disabled) {
    return;
  }
  openDatepicker.value = !openDatepicker.value;
};

const clickToNextMonth = () => {
  const setDateTime = currentMonth.value.setMonth(
    currentMonth.value.getMonth() + 1
  );
  currentMonth.value = new Date(setDateTime);
};

const clickToPreviousMonth = () => {
  const setDateTime = currentMonth.value.setMonth(
    currentMonth.value.getMonth() - 1
  );
  currentMonth.value = new Date(setDateTime);
};

const parseValue = (inputValue?: Date) => {
  const value = inputValue ?? new Date();
  return `${value.getFullYear()}/${value.getMonth() + 1}/${value.getDate()}`;
};

const currentDateTitle = computed(() => {
  return `${currentMonth.value.getFullYear()}年${
    currentMonth.value.getMonth() + 1
  }月`;
});

const calendarValue = computed({
  get: () => props.modelValue,
  set: (value) => emit("update:modelValue", value),
});

// Form Control
const form = inject(formControlKey);
const isError = computed(() => (form ? form.isError.value : false));

const borderState = computed(() => {
  if (isError.value) return "error";
  if (openDatepicker.value) return "active";
  return "default";
});

const variant = computed(() => {
  if (props.disabled) return "disabled";
  if (calendarValue.value) return "selected";
  return "default";
});
</script>
