// packages/wiz-ui-react/src/components/base/inputs/selectbox/components/selectbox.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/selectbox-input.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import {
  KeyboardEventHandler,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

import {
  WizHStack,
  WizIExpandLess,
  WizIExpandMore,
  WizPopup,
  WizVStack,
} from "@/components";
import { FormControlContext } from "@/components/custom/form/components/form-control-context";
import { BaseProps } from "@/types";

type SelectBoxOption<T> = {
  label: string;
  exLabel?: string;
  value: T;
};

type Props<T> = BaseProps & {
  options: SelectBoxOption<T>[];
  value: T;
  placeholder?: string;
  width?: string;
  disabled?: boolean;
  expand?: boolean;
  error?: boolean;
  isDirectionFixed?: boolean;
  showExLabel?: boolean;
  dropdownMaxHeight?: string;
  onChange: (value: T) => void;
};

const SelectBox = <T,>({
  className,
  style,
  options,
  value,
  placeholder = "選択してください",
  width = "10rem",
  disabled = false,
  expand,
  error,
  isDirectionFixed = false,
  showExLabel = false,
  dropdownMaxHeight,
  onChange,
}: Props<T>) => {
  const [isOpen, setIsOpen] = useState(false);
  const anchorRef = useRef<HTMLDivElement>(null);
  const formControl = useContext(FormControlContext);

  useEffect(() => {
    if (disabled && isOpen) {
      setIsOpen(false);
    }
  }, [disabled, isOpen]);

  const selectedOption = useMemo(
    () => options.find((option) => option.value === value),
    [options, value]
  );

  const toggleOpen = () => {
    if (disabled) {
      return;
    }
    setIsOpen(!isOpen);
  };

  const handleClickOption = (option: SelectBoxOption<T>) => {
    setIsOpen(false);
    onChange(option.value);
  };

  const getInputBorderStyleKey = () => {
    if (error || formControl.error) return "error";
    if (isOpen) return "active";
    return "default";
  };

  const handleKeyDown: KeyboardEventHandler = (e) => {
    switch (e.key) {
      case " ":
        if (isOpen) {
          // TODO: キーボード操作で option を選択可能にする
        } else {
          setIsOpen(true);
        }
        break;
      case "Escape":
        setIsOpen(false);
        break;
    }
  };

  return (
    <>
      <div
        ref={anchorRef}
        className={clsx(
          className,
          styles.selectBoxStyle,
          inputBorderStyle[getInputBorderStyleKey()],
          disabled && styles.selectBoxDisabledStyle,
          styles.selectBoxCursorStyle[disabled ? "disabled" : "default"]
        )}
        style={{
          ...style,
          width: expand ? "100%" : width,
        }}
        onClick={toggleOpen}
        role="combobox"
        onKeyDown={handleKeyDown}
        tabIndex={disabled ? undefined : 0}
      >
        <div className={styles.selectBoxInnerBoxStyle}>
          <WizHStack align="center" justify="between" height="100%" nowrap>
            {selectedOption ? (
              <span className={styles.selectBoxInnerBoxSelectedValueStyle}>
                {selectedOption.label}
                {showExLabel &&
                  selectedOption.exLabel &&
                  " " + selectedOption.exLabel}
              </span>
            ) : (
              <span className={styles.selectBoxPlaceholderStyle}>
                {placeholder}
              </span>
            )}
            {isOpen ? (
              <div
                className={styles.selectBoxInnerBoxLessStyle}
                style={{ display: "flex" }}
              >
                <WizIExpandLess />
              </div>
            ) : (
              <div
                className={styles.selectBoxInnerBoxMoreStyle}
                style={{ display: "flex" }}
              >
                <WizIExpandMore />
              </div>
            )}
          </WizHStack>
        </div>
      </div>
      <WizPopup
        isOpen={isOpen}
        onClose={useCallback(() => setIsOpen(false), [])}
        anchorElement={anchorRef}
        isDirectionFixed={isDirectionFixed}
      >
        <div
          className={styles.selectBoxSelectorStyle}
          style={{ minWidth: width, maxHeight: dropdownMaxHeight }}
        >
          <WizVStack gap="xs2">
            {options.map((option) => (
              <div
                key={`${option.value}-${option.label}`}
                className={styles.selectBoxSelectorOptionStyle}
                onClick={() => handleClickOption(option)}
              >
                <span>{option.label}</span>
                {option.exLabel && <span>{option.exLabel}</span>}
              </div>
            ))}
          </WizVStack>
        </div>
      </WizPopup>
    </>
  );
};

SelectBox.displayName = ComponentName.SelectBox;

export const WizSelectBox = SelectBox;

// packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.vue
<template>
  <WizPopupContainer :expand="expand">
    <div
      :class="[
        selectBoxStyle,
        inputBorderStyle[state],
        disabled && selectBoxDisabledStyle,
        selectBoxCursorStyle[selectBoxCursor],
      ]"
      :style="{ width: computedWidth }"
    >
      <div :class="selectBoxInnerBoxStyle" @click="toggleSelectBox">
        <WizHStack align="center" justify="between" height="100%">
          <span v-if="!isValueMatched" :class="selectBoxPlaceholderStyle">{{
            placeholder
          }}</span>
          <span
            v-if="selectedOption"
            :class="selectBoxInnerBoxSelectedValueStyle"
          >
            {{ selectedOption.label }}
            {{
              showExLabel && selectedOption.exLabel
                ? " " + selectedOption.exLabel
                : ""
            }}
          </span>
          <WizIExpandLess
            v-if="openSelectBox"
            :class="selectBoxInnerBoxLessStyle"
          />
          <WizIExpandMore
            v-else-if="!openSelectBox"
            :class="selectBoxInnerBoxMoreStyle"
          />
        </WizHStack>
      </div>
    </div>
    <WizPopup
      :isOpen="openSelectBox"
      @onClose="openSelectBox = false"
      :isDirectionFixed="isDirectionFixed"
    >
      <div
        :class="selectBoxSelectorStyle"
        :style="{ minWidth: width, maxHeight: dropdownMaxHeight }"
      >
        <WizVStack gap="xs2">
          <div
            :class="selectBoxSelectorOptionStyle"
            v-for="(option, key) in options"
            :key="'option' + key"
            @click="onSelect(option.value)"
          >
            <span>
              {{ option.label }}
            </span>
            <span v-if="option.exLabel">
              {{ option.exLabel }}
            </span>
          </div>
        </WizVStack>
      </div>
    </WizPopup>
  </WizPopupContainer>
</template>

<script setup lang="ts" generic="T">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  selectBoxCursorStyle,
  selectBoxDisabledStyle,
  selectBoxInnerBoxLessStyle,
  selectBoxInnerBoxMoreStyle,
  selectBoxInnerBoxSelectedValueStyle,
  selectBoxInnerBoxStyle,
  selectBoxPlaceholderStyle,
  selectBoxSelectorOptionStyle,
  selectBoxSelectorStyle,
  selectBoxStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/selectbox-input.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { computed, inject, ref } from "vue";

import { WizPopup, WizPopupContainer } from "@/components";
import { WizIExpandLess, WizIExpandMore } from "@/components/icons";
import { formControlKey } from "@/hooks/use-form-control-provider";

import { WizHStack, WizVStack } from "../../stack";

import { SelectBoxOption } from "./types";

defineOptions({
  name: ComponentName.SelectBox,
});

type Props<T> = {
  options: SelectBoxOption<T>[];
  modelValue: T;
  placeholder?: string;
  width?: string;
  disabled?: boolean;
  expand?: boolean;
  isOpen?: boolean;
  isDirectionFixed?: boolean;
  showExLabel?: boolean;
  dropdownMaxHeight?: string;
};

const props = withDefaults(defineProps<Props<T>>(), {
  placeholder: "選択してください",
  width: "10rem",
  disabled: false,
  expand: false,
  isOpen: false,
  isDirectionFixed: false,
  showExLabel: false,
});

const openSelectBox = ref(props.isOpen);
const toggleSelectBox = () => {
  if (props.disabled) {
    return;
  }
  openSelectBox.value = !openSelectBox.value;
};

const emit = defineEmits<{ "update:modelValue": [value: T] }>();

const onSelect = (value: T) => {
  toggleSelectBox();
  emit("update:modelValue", value);
};

const selectBoxCursor = computed(() =>
  props.disabled ? "disabled" : "default"
);

// Form Control
const form = inject(formControlKey);
const isError = computed(() => (form ? form.isError.value : false));

const computedWidth = computed(() => (props.expand ? "100%" : props.width));

const state = computed(() => {
  if (isError.value) return "error";
  if (openSelectBox.value) return "active";
  return "default";
});

const isValueMatched = computed(() => {
  return props.options.some((option) => option.value === props.modelValue);
});

const selectedOption = computed(() => {
  return props.options.find((option) => option.value === props.modelValue);
});
</script>
