// packages/wiz-ui-react/src/components/base/inputs/radio-new/components/radio-new.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/radio-new.css";
import clsx from "clsx";
import {
  ChangeEvent,
  ChangeEventHandler,
  ComponentProps,
  ReactNode,
  forwardRef,
  useCallback,
  useEffect,
  useMemo,
  useState,
} from "react";

type InputProps = ComponentProps<"input">;

type Props = {
  checked?: boolean;
  value?: InputProps["value"];
  id?: string;
  name?: string;
  disabled?: boolean;
  strikeThrough?: boolean;
  bordered?: boolean;
  error?: boolean;
  children?: ReactNode;
  onChange?: (e: ChangeEvent<HTMLInputElement>) => void;
};

const RadioNew = forwardRef<HTMLInputElement, Props>(
  (
    { checked, strikeThrough, bordered, error, children, onChange, ...props },
    ref
  ) => {
    const isControlled = checked !== undefined;

    const [actualChecked, setActualChecked] = useState(checked);
    useEffect(() => {
      if (isControlled) {
        setActualChecked(checked);
      }
    }, [checked, isControlled]);

    const handleChange = useCallback<ChangeEventHandler<HTMLInputElement>>(
      (e) => {
        onChange?.(e);
        if (!isControlled) {
          setActualChecked(e.target.checked);
        }
      },
      [isControlled, onChange]
    );

    const labelClassName = useMemo(() => {
      const borderedState = (() => {
        if (props.disabled) {
          return "disabled";
        }
        if (error) {
          return "error";
        }
        if (actualChecked) {
          return "checked";
        }
        return "default";
      })();

      return clsx(
        styles.labelStyle[props.disabled ? "disabled" : "default"],
        strikeThrough && styles.strikeThroughStyle,
        bordered && styles.borderedStyle[borderedState]
      );
    }, [actualChecked, bordered, error, props.disabled, strikeThrough]);

    return (
      <label className={labelClassName}>
        <input
          {...props}
          ref={ref}
          type="radio"
          className={styles.inputStyle}
          checked={actualChecked}
          onChange={handleChange}
        />
        <div className={styles.markerStyle} />
        {children}
      </label>
    );
  }
);

RadioNew.displayName = ComponentName.RadioNew;

export const WizRadioNew = RadioNew;

// packages/wiz-ui-next/src/components/base/inputs/radio-new/radio-new.vue
<template>
  <label :class="labelClass">
    <input
      type="radio"
      :class="styles.inputStyle"
      :checked="actualChecked"
      :value="value"
      :id="id"
      :name="name"
      :disabled="disabled"
      @change="handleChange"
    />
    <div :class="styles.markerStyle" />
    <slot />
  </label>
</template>

<script setup lang="ts">
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/radio-new.css";
import { computed, ref, watch } from "vue";
interface Props {
  checked: boolean;
  value?: string | number | string[];
  id?: string;
  name?: string;
  disabled?: boolean;
  strikeThrough?: boolean;
  bordered?: boolean;
  error?: boolean;
}
const props = defineProps<Props>();

interface Emits {
  (e: "update:checked", checked: boolean): void;
}
const emit = defineEmits<Emits>();
const actualChecked = ref(props.checked);
watch(
  () => props.checked,
  () => {
    actualChecked.value = props.checked;
  }
);
const labelClass = computed(() => {
  const borderedState = (() => {
    if (props.disabled) {
      return "disabled";
    }
    if (props.error) {
      return "error";
    }
    if (actualChecked.value) {
      return "checked";
    }
    return "default";
  })();
  return [
    styles.labelStyle[props.disabled ? "disabled" : "default"],
    props.strikeThrough && styles.strikeThroughStyle,
    props.bordered && styles.borderedStyle[borderedState],
  ];
});
const handleChange = (e: Event) => {
  if (e.target instanceof HTMLInputElement) {
    emit("update:checked", e.target.checked);
    actualChecked.value = e.target.checked;
  }
};
</script>
