// packages/wiz-ui/src/components/base/tooltip/tooltip.vue
<template>
  <div
    :class="tooltipStyle"
    @mouseenter="isHover = true"
    @mouseleave="isHover = false"
  >
    <WizPopupContainer :expand="expand">
      <slot />
      <WizPopup
        v-if="$slots.content"
        :isOpen="isHover || hover"
        :direction="computedDirection"
        :shadow="false"
        :animation="true"
        @onTurn="turnPopup"
        gap="xs2"
        :isDirectionFixed="isDirectionFixed"
      >
        <div
          :class="[tooltipPositionStyle[actuallyDirection], tooltipPopupStyle]"
        >
          <div :class="tooltipContentStyle">
            <slot name="content" />
          </div>
          <WizIChangeHistory
            :class="[
              tooltipIconStyle,
              tooltipIconDirectionStyle[actuallyDirection],
            ]"
          />
        </div>
      </WizPopup>
    </WizPopupContainer>
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  tooltipStyle,
  tooltipContentStyle,
  tooltipIconStyle,
  tooltipIconDirectionStyle,
  tooltipPositionStyle,
  tooltipPopupStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/tooltip.css";
import { PropType, ref, computed } from "vue";

import { WizIChangeHistory, WizPopup, WizPopupContainer } from "@/components";

defineOptions({
  name: ComponentName.Tooltip,
});

const props = defineProps({
  direction: {
    type: String as PropType<"top" | "bottom" | "left" | "right">,
    required: false,
    default: "top",
  },
  hover: {
    type: Boolean,
    required: false,
    default: false,
  },
  expand: {
    type: Boolean,
    required: false,
    default: false,
  },
  isDirectionFixed: {
    type: Boolean,
    required: false,
    default: false,
  },
});

const isHover = ref(false);
const actuallyDirection = ref(props.direction);

const computedDirection = computed(() => {
  if (props.direction === "top") return "tc";
  if (props.direction === "bottom") return "bc";
  if (props.direction === "left") return "lc";
  if (props.direction === "right") return "rc";
  return "tc";
});

const turnPopup = (direction: string) => {
  if (direction[0] === "t") actuallyDirection.value = "top";
  if (direction[0] === "b") actuallyDirection.value = "bottom";
  if (direction[0] === "l") actuallyDirection.value = "left";
  if (direction[0] === "r") actuallyDirection.value = "right";
};
</script>

// packages/wiz-ui-react/src/components/base/tooltip/components/tooltip.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  tooltipContentStyle,
  tooltipIconDirectionStyle,
  tooltipIconStyle,
  tooltipPopupStyle,
  tooltipPositionStyle,
  tooltipStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/tooltip.css";
import clsx from "clsx";
import { FC, ReactNode, useCallback, useRef, useState } from "react";

import { WizIChangeHistory, WizPopup } from "@/components";

interface Props {
  direction?: "top" | "bottom" | "left" | "right";
  hover?: boolean;
  isDirectionFixed?: boolean;
  children: ReactNode;
  content: ReactNode;
}

const Tooltip: FC<Props> = ({
  direction = "top",
  hover = false,
  isDirectionFixed = false,
  children,
  content,
}) => {
  const [isHover, setIsHover] = useState(false);
  const anchor = useRef<HTMLDivElement | null>(null);

  return (
    <>
      <div
        className={clsx(tooltipStyle)}
        onMouseEnter={() => setIsHover(true)}
        onMouseLeave={() => setIsHover(false)}
        ref={anchor}
      >
        {children}
      </div>
      <WizPopup
        anchorElement={anchor}
        isOpen={isHover || hover}
        onClose={useCallback(() => setIsHover(false), [])}
        direction={direction}
        shadow={false}
        animation
        gap="xs2"
        isDirectionFixed={isDirectionFixed}
      >
        <div
          className={clsx(tooltipPositionStyle[direction], tooltipPopupStyle)}
        >
          <div className={clsx(tooltipContentStyle)}>{content}</div>
          <div
            className={clsx(
              tooltipIconStyle,
              tooltipIconDirectionStyle[direction]
            )}
          >
            <WizIChangeHistory />
          </div>
        </div>
      </WizPopup>
    </>
  );
};

Tooltip.displayName = ComponentName.Tooltip;

export const WizTooltip = Tooltip;
