// packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-input.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/search-input.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import { FC, useMemo, useRef, useState } from "react";

import { TIcon, WizHStack, WizISearch, WizPopup } from "@/components";
import { BaseProps } from "@/types";

import { SearchPopupPanel } from "./search-popup-panel";
import { SearchInputOption } from "./types";

type Props = BaseProps & {
  options: SearchInputOption[];
  values: number[];
  name?: string;
  placeholder?: string;
  disabled?: boolean;
  expand?: boolean;
  inputWidth?: string;
  popupWidth?: string;
  isDirectionFixed?: boolean;
  icon?: TIcon;
  onChangeValues: (values: number[]) => void;
};

function filterOptions(
  options: SearchInputOption[],
  text: string
): SearchInputOption[] {
  return options.flatMap((option) => {
    const isMatched = option.label.includes(text);
    if (option.children.length === 0) {
      return isMatched ? [option] : [];
    }
    if (isMatched) return [option];
    const children = filterOptions(option.children, text);
    if (children.length === 0) return [];
    return [
      {
        ...option,
        children,
      },
    ];
  });
}

const SearchInput: FC<Props> = ({
  className,
  style,
  options,
  values,
  name,
  placeholder,
  disabled,
  expand,
  inputWidth = "10rem",
  popupWidth,
  isDirectionFixed = false,
  onChangeValues,
  icon = WizISearch,
}) => {
  const [filteringText, setFilteringText] = useState("");
  const [isFocused, setIsFocused] = useState(false);
  const [isPopupOpen, setIsPopupOpen] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const filteredOptions = useMemo(
    () => filterOptions(options, filteringText),
    [filteringText, options]
  );

  const IconComponent = icon;

  return (
    <div
      className={clsx(className, styles.searchStyle)}
      style={{ ...style, width: expand ? "100%" : undefined }}
    >
      <input
        ref={inputRef}
        type="text"
        className={clsx(
          styles.searchInputStyle,
          disabled && styles.searchInputDisabledStyle,
          inputBorderStyle[isFocused ? "active" : "default"]
        )}
        style={{ width: expand ? "100%" : inputWidth }}
        value={filteringText}
        placeholder={placeholder}
        name={name}
        disabled={disabled}
        onChange={(e) => {
          setIsPopupOpen(true);
          setFilteringText(e.target.value);
        }}
        onFocus={() => setIsFocused(true)}
        onBlur={() => setIsFocused(false)}
        onClick={() => setIsPopupOpen(!isPopupOpen)}
        autoComplete="off"
      />
      <div className={styles.searchInputIconStyle}>
        <IconComponent />
      </div>
      {filteredOptions.length > 0 && (
        <WizPopup
          anchorElement={inputRef}
          isOpen={isPopupOpen}
          onClose={() => setIsPopupOpen(false)}
          isDirectionFixed={isDirectionFixed}
        >
          <WizHStack nowrap>
            <SearchPopupPanel
              options={filteredOptions}
              values={values}
              width={popupWidth}
              onChangeValues={(changed) => onChangeValues(changed)}
            />
          </WizHStack>
        </WizPopup>
      )}
    </div>
  );
};

SearchInput.displayName = ComponentName.SearchInput;

export const WizSearchInput = SearchInput;

// packages/wiz-ui/src/components/base/inputs/search-input/search-input.vue
<template>
  <WizPopupContainer :expand="expand">
    <div :class="searchStyle">
      <input
        type="text"
        :class="[
          searchInputStyle,
          disabled && searchInputDisabledStyle,
          inputBorderStyle[state],
        ]"
        :style="{ width: computedInputWidth }"
        v-model="searchValue"
        :placeholder="placeholder"
        :name="name"
        :disabled="disabled"
        @focusin="hasFocus = true"
        @focusout="hasFocus = false"
        @click="
          emit('toggle', true);
          selectedItem = [];
        "
        autocomplete="off"
      />
      <component :is="icon" :class="searchInputIconStyle" />
    </div>
    <WizPopup
      :isOpen="!disabled && openPopup"
      :isDirectionFixed="isDirectionFixed"
      @onClose="emit('toggle', false)"
    >
      <WizHStack>
        <div
          v-if="filteredOptions.length"
          :class="[
            searchBlockStyle,
            searchBlockBorderRadiusStyle,
            isBorder && searchBlockBorderStyle,
          ]"
          :style="{ width: computedPopupWidth }"
        >
          <div
            v-for="(option, key) in filteredOptions"
            :key="`${option.label}_${option.value}_${key}`"
          >
            <div v-if="option.children" :class="searchDropdownItemStyle">
              <div
                :class="[
                  searchDropdownLabelStyle,
                  selectedItem.includes(option.value) &&
                    searchDropdownSelectingItemStyle,
                ]"
                @mouseover="onMouseover(option.value)"
                @mouseout="activeItem = null"
              >
                {{ option.label }}
                <WizIcon
                  size="xl2"
                  :icon="WizIChevronRight"
                  :color="computedIconColor(option.value)"
                />
              </div>
            </div>
            <div
              v-else
              :class="searchDropdownCheckboxItemStyle"
              @mouseover="activeItem = option.value"
              @mouseout="activeItem = null"
            >
              <input
                v-model="checkValues"
                :value="option.value"
                :class="searchCheckboxInputStyle"
                type="checkbox"
                :id="`${option.label}_${option.value}`"
                :name="`${option.label}_${option.value}`"
              />
              <label
                :class="[
                  searchCheckboxLabelStyle,
                  (checkValues.includes(option.value) ||
                    activeItem === option.value) &&
                    searchCheckboxLabelCheckedStyle,
                ]"
                :for="`${option.label}_${option.value}`"
                @mouseover="
                  selectedItem = [];
                  isBorder = false;
                "
              >
                <WizICheck
                  v-if="checkValues.includes(option.value)"
                  :class="searchCheckboxIconStyle"
                />
                <span
                  :class="[
                    (checkValues.includes(option.value) ||
                      activeItem === option.value) &&
                      searchCheckboxBlockCheckedStyle,
                  ]"
                  >{{ option.label }}</span
                >
              </label>
            </div>
            <WizDivider v-if="key !== options.length - 1" color="gray.300" />
          </div>
        </div>
        <WizSearchPopup
          :values="values"
          @input="inputValues"
          :options="filteredOptions"
          :selectedItem="selectedItem"
          :popupWidth="computedPopupWidth"
          :dy="activeItemIndex || 0"
        />
      </WizHStack>
    </WizPopup>
  </WizPopupContainer>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  searchBlockBorderRadiusStyle,
  searchBlockBorderStyle,
  searchBlockStyle,
  searchCheckboxBlockCheckedStyle,
  searchCheckboxIconStyle,
  searchCheckboxInputStyle,
  searchCheckboxLabelCheckedStyle,
  searchCheckboxLabelStyle,
  searchDropdownCheckboxItemStyle,
  searchDropdownItemStyle,
  searchDropdownLabelStyle,
  searchDropdownSelectingItemStyle,
  searchInputDisabledStyle,
  searchInputIconStyle,
  searchInputStyle,
  searchStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/search-input.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { PropType, computed, onMounted, ref, watch } from "vue";

import {
  WizDivider,
  WizHStack,
  WizISearch,
  WizIcon,
  WizPopup,
  WizPopupContainer,
  WizSearchPopup,
} from "@/components";
import { WizICheck, WizIChevronRight, TIcon } from "@/components/icons";

import { SearchInputOption } from "./types";

defineOptions({
  name: ComponentName.SearchInput,
});

const props = defineProps({
  options: {
    type: Array as PropType<SearchInputOption[]>,
    required: true,
  },
  values: {
    type: Array as PropType<number[]>,
    required: true,
  },
  name: {
    type: String,
    required: true,
  },
  placeholder: {
    type: String,
    required: false,
  },
  disabled: {
    type: Boolean,
    required: false,
  },
  expand: {
    type: Boolean,
    required: false,
  },
  inputWidth: {
    type: String,
    required: false,
    default: "10rem",
  },
  popupWidth: {
    type: String,
    required: false,
  },
  openPopup: {
    type: Boolean,
    required: true,
  },
  isDirectionFixed: {
    type: Boolean,
    required: false,
    default: false,
  },
  icon: {
    type: Object as PropType<TIcon>,
    required: false,
    default: WizISearch,
  },
});

const emit = defineEmits<{
  (e: "input", value: number[]): void;
  (e: "click"): void;
  (e: "toggle", value: boolean): void;
}>();

const checkValues = computed({
  get: () => props.values,
  set: (value) => {
    emit("input", value);
  },
});

const inputValues = (value: number[]) => {
  emit("input", value);
};

const searchValue = ref("");
const filteredOptions = ref<SearchInputOption[]>([]);
const selectedItem = ref<number[]>([]);
const activeItem = ref<number | null>();
const activeItemIndex = ref<number | null>(null);
const hasFocus = ref(false);
const isBorder = ref(false);

const state = computed(() => {
  if (hasFocus.value) return "active";
  return "default";
});

const computedInputWidth = computed(() =>
  props.expand ? "100%" : props.inputWidth
);
const computedPopupWidth = computed(() => props.popupWidth);
const computedIconColor = computed(() => (value: number) => {
  if (activeItem.value === value) {
    return "green.800";
  }
  return "gray.500";
});

const onMouseover = (value: number) => {
  isBorder.value = true;
  activeItem.value = value;
  activeItemIndex.value = filteredOptions.value.findIndex(
    (option) => option.value === value
  );
  selectedItem.value = [];
  if (!selectedItem.value.includes(value)) {
    selectedItem.value.push(value);
  }
};

const filterOptions =
  (match: (label: string) => boolean) =>
  (options: SearchInputOption[]): SearchInputOption[] =>
    options.flatMap((option) => {
      if (!option.children || option.children.length === 0) {
        return match(option.label) ? [option] : [];
      }
      if (match(option.label)) return [option];
      const children = filterOptions(match)(option.children);
      if (children.length === 0) return [];
      return [
        {
          ...option,
          children: children,
        },
      ];
    });

const searchBy = (keyword: string) => (str: string) => str.includes(keyword);

watch(searchValue, () => {
  selectedItem.value = [];
  emit("toggle", true);
  if (searchValue.value.length) {
    filteredOptions.value = filterOptions(searchBy(searchValue.value))(
      props.options
    );
  } else {
    filteredOptions.value = props.options;
  }
});

onMounted(() => {
  filteredOptions.value = props.options;
});
</script>
