// packages/wiz-ui-react/src/components/base/header/components/header.tsx
import { ComponentName, SpacingKeys } from "@wizleap-inc/wiz-ui-constants";
import {
  headerStyle,
  headerStickyStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/header.css";
import clsx from "clsx";
import { Dispatch, FC, ReactNode, SetStateAction } from "react";

import { WizHStack, WizIMenu } from "@/components";

import { WizIconButton } from "../../buttons/icon";

interface Props {
  gapLeft?: SpacingKeys;
  gapRight?: SpacingKeys;
  sticky?: boolean;
  leftContent?: ReactNode;
  rightContent?: ReactNode;
  setIsMenuOpen: Dispatch<SetStateAction<boolean>>;
}

const Header: FC<Props> = ({
  gapLeft,
  gapRight,
  sticky,
  leftContent,
  rightContent,
  setIsMenuOpen,
}) => {
  return (
    <div className={clsx(headerStyle, sticky && headerStickyStyle)}>
      <WizHStack align="center" justify="between" height="100%">
        <WizHStack align="center" gap={gapLeft} pl="lg">
          <WizIconButton
            icon={WizIMenu}
            size="lg"
            variant="transparent"
            onClick={() => setIsMenuOpen((prev) => !prev)}
          />
          {leftContent}
        </WizHStack>
        <WizHStack align="center" gap={gapRight} pr="lg">
          {rightContent}
        </WizHStack>
      </WizHStack>
    </div>
  );
};

Header.displayName = ComponentName.Header;

export const WizHeader = Header;

// packages/wiz-ui/src/components/custom/header/header.vue
<template>
  <WizBox bg-color="white.500" width="100%" height="60px">
    <WizHStack align="center" justify="between" py="lg" height="100%">
      <WizHStack align="center">
        <WizIconButton
          :icon="WizIMenu"
          size="lg"
          variant="transparent"
          @click="toggleMenuOpen"
        />
        <component :is="logo" />
        <WizHeading fontSize="sm" color="gray.900" padding="0 1rem">
          {{ title }}
        </WizHeading>
      </WizHStack>
      <WizHStack align="center">
        <WizIconButton
          :icon="WizINotification"
          size="md"
          variant="transparent"
          @click="toggleNotificationOpen"
        />
        <WizAvatar :src="avatarSrc" />
      </WizHStack>
    </WizHStack>
  </WizBox>
</template>

<script setup lang="ts">
import Vue from "vue";

import {
  WizAvatar,
  WizBox,
  WizHeading,
  WizHStack,
  WizIconButton,
} from "@/components/base";
import { WizIMenu, WizINotification } from "@/components/icons";
import { ComponentName } from "@/constants/component/name";
import { globalInject, globalKey } from "@/providers";

defineOptions({
  name: ComponentName.Header,
});

interface Props {
  title: string;
  logo?: Vue;
  avatarSrc: string;
}

defineProps<Props>();

const { isMenuOpen, setIsMenuOpen } = globalInject(globalKey);

const toggleMenuOpen = () => {
  setIsMenuOpen(!isMenuOpen.value);
};
</script>

<style lang="scss" scoped></style>
