// packages/wiz-ui-react/src/components/base/panel-switch/components/panel-switch.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/panel-switch-input.css";
import clsx from "clsx";
import { FC, useId } from "react";

import { BaseProps } from "@/types";

import { PanelItems } from "./type";

type Props = BaseProps & {
  value: number | null;
  items: PanelItems[];
  width?: string;
  onChange: (value: number) => void;
};

const PanelSwitch: FC<Props> = ({
  className,
  style,
  value,
  items,
  width,
  onChange,
}) => {
  const idPrefix = useId();

  return (
    <div
      className={clsx(className, styles.panelSwitchStyle)}
      style={{ ...style, ...(width ? { width } : {}) }}
    >
      {items.map((item, index) => {
        const radioId = `${idPrefix}-${item.value}`;
        const isFirstItem = index === 0;
        const isLastItem = index === items.length - 1;
        const isActiveItem = value && value === item.value;
        return (
          <label
            key={item.value}
            className={clsx(
              styles.panelSwitchBlockStyle,
              !isLastItem && styles.panelSwitchBlockDividerStyle,
              isFirstItem && styles.panelSwitchBlockLeftStyle,
              isLastItem && styles.panelSwitchBlockRightStyle,
              isActiveItem && styles.panelSwitchBlockActiveStyle,
              styles.panelSwitchBlockColorStyle[
                isActiveItem ? "active" : "default"
              ]
            )}
            htmlFor={radioId}
            tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === "Enter" || e.key === " ") onChange?.(item.value);
            }}
          >
            {item.label}
            <input
              className={styles.panelSwitchInputStyle}
              type="radio"
              id={radioId}
              name={item.name}
              value={item.value}
              onClick={() => onChange?.(item.value)}
            />
          </label>
        );
      })}
    </div>
  );
};

PanelSwitch.displayName = ComponentName.PanelSwitch;

export const WizPanelSwitch = PanelSwitch;

// packages/wiz-ui-next/src/components/base/inputs/panel-switch/panel-switch.vue
<template>
  <div :class="panelSwitchStyle">
    <label
      v-for="(item, key) in items"
      :key="key"
      :class="[
        panelSwitchBlockStyle,
        key !== items.length - 1 && panelSwitchBlockDividerStyle,
        key === 0 && panelSwitchBlockLeftStyle,
        key === items.length - 1 && panelSwitchBlockRightStyle,
        key === switchValue - 1 && panelSwitchBlockActiveStyle,
        panelSwitchBlockColorStyle[panelSwitchBlockColor(key)],
      ]"
      :for="`panel${key}`"
    >
      {{ item.label }}
      <input
        :class="panelSwitchInputStyle"
        type="radio"
        :id="`panel${key}`"
        :name="`panel${key}`"
        :value="item.value"
        v-model="switchValue"
      />
    </label>
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  panelSwitchStyle,
  panelSwitchBlockStyle,
  panelSwitchBlockActiveStyle,
  panelSwitchBlockDividerStyle,
  panelSwitchBlockLeftStyle,
  panelSwitchBlockRightStyle,
  panelSwitchBlockColorStyle,
  panelSwitchInputStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/panel-switch-input.css";
import { computed } from "vue";

import { panelItems } from "./types";

defineOptions({
  name: ComponentName.PanelSwitch,
});

interface Props {
  modelValue: number;
  items: panelItems[];
}

const props = defineProps<Props>();

interface Emit {
  (e: "update:modelValue", value: number): void;
}

const emit = defineEmits<Emit>();

const switchValue = computed({
  get: () => props.modelValue,
  set: (value) => emit("update:modelValue", value),
});

const panelSwitchBlockColor = (key: number) =>
  key === switchValue.value - 1 ? "active" : "default";
</script>
