// packages/wiz-ui-react/src/components/base/inputs/search-selector/components/search-selector.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/search-selector.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import {
  FC,
  KeyboardEvent,
  KeyboardEventHandler,
  MouseEventHandler,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

import {
  WizHStack,
  WizIAddCircle,
  WizIClose,
  WizIExpandLess,
  WizIExpandMore,
  WizIcon,
  WizPopup,
  WizPopupButtonGroup,
} from "@/components";
import { ButtonGroupItem } from "@/components/base/popup-button-group/types";
import { FormControlContext } from "@/components/custom/form/components/form-control-context";

import { filterOptions } from "./search-selector-helper";
import { SearchSelectorOption } from "./types";

type Props = {
  options: SearchSelectorOption[];
  values: number[];
  placeholder?: string;
  width?: string;
  disabled?: boolean;
  expand?: boolean;
  multiSelectable?: boolean;
  addable?: boolean;
  error?: boolean;
  isDirectionFixed?: boolean;
  showExLabel?: boolean;
  onChangeValues: (values: number[]) => void;
  onCreate?: (label: string) => void;
  onInputSearchText?: (text: string) => void;
};

const SearchSelector: FC<Props> = ({
  options,
  values,
  placeholder = "選択してください",
  width = "10rem",
  disabled = false,
  expand,
  multiSelectable = false,
  addable = false,
  error,
  isDirectionFixed = false,
  showExLabel = false,
  onChangeValues,
  onCreate,
  onInputSearchText,
}) => {
  const [searchText, setSearchText] = useState("");
  const [isPopupOpen, setIsPopupOpen] = useState(false);
  const [isFocused, setIsFocused] = useState(false);
  const wrapperRef = useRef<HTMLDivElement>(null);
  const searchTextboxRef = useRef<HTMLInputElement>(null);
  const clearButtonsRef = useRef<Array<HTMLButtonElement | null>>([]);
  const popupRef = useRef<HTMLDivElement>(null);
  const formControl = useContext(FormControlContext);

  const isError = error || formControl.error;

  const selectedOptions = useMemo(
    () => options.filter((option) => values.includes(option.value)),
    [options, values]
  );

  useEffect(() => {
    // 選択解除ボタンの ref の数を補正
    clearButtonsRef.current = clearButtonsRef.current.slice(
      0,
      selectedOptions.length
    );
  }, [selectedOptions.length]);

  const buttonGroupOptions: ButtonGroupItem[] = useMemo(() => {
    const filteredOptions = filterOptions(options, searchText).filter(
      (matchedOption) => {
        return !values.some((value) => matchedOption.value === value);
      }
    );
    const buttonGroupOptions: ButtonGroupItem[] = filteredOptions.map(
      (option) => {
        return {
          kind: "button",
          option: {
            label: option.label,
            value: option.value,
            exLabel: option.exLabel,
            onClick: () => {
              setSearchText("");
              if (multiSelectable) {
                onChangeValues([...values, option.value]);
                searchTextboxRef.current?.focus();
              } else {
                onChangeValues([option.value]);
                setIsPopupOpen(false);
              }
            },
          },
        };
      }
    );
    const shouldShowAddButton =
      addable &&
      searchText !== "" &&
      options.every((option) => option.label !== searchText);
    return shouldShowAddButton
      ? [
          {
            kind: "button",
            option: {
              label: searchText,
              icon: WizIAddCircle,
              iconDefaultColor: "green.800",
              value: -1,
              onClick: () => onCreate?.(searchText),
            },
          },
          ...buttonGroupOptions,
        ]
      : buttonGroupOptions;
  }, [
    addable,
    multiSelectable,
    onChangeValues,
    onCreate,
    options,
    searchText,
    values,
  ]);

  const unselectOption = (option: SearchSelectorOption) => {
    onChangeValues(values.filter((value) => value !== option.value));
    setTimeout(() => {
      // input 要素が描画されるのを待ってフォーカス
      searchTextboxRef.current?.focus();
    });
  };

  const handleClickClearButton = (
    option: SearchSelectorOption
  ): MouseEventHandler => {
    return (e) => {
      e.stopPropagation();
      unselectOption(option);
      setIsPopupOpen(true);
    };
  };

  const handleClickWrapper = () => {
    if (disabled) {
      return;
    }
    if (searchTextboxRef.current) {
      searchTextboxRef.current.focus();
    } else {
      setIsFocused(true);
      setIsPopupOpen(true);
    }
  };

  const keyDownHandlers = {
    clearButton: (option: SearchSelectorOption): KeyboardEventHandler => {
      return (e) => {
        if (e.key === "Backspace") {
          unselectOption(option);
        }
      };
    },
    input: (e: KeyboardEvent) => {
      if (
        e.key === "Backspace" &&
        searchText === "" &&
        clearButtonsRef.current.length > 0
      ) {
        clearButtonsRef.current.at(-1)?.focus();
      }
    },
  };

  useEffect(() => {
    const handleEscape = (e: globalThis.KeyboardEvent) => {
      if (e.key === "Escape" || e.key === "Esc") {
        setIsPopupOpen(false);
      }
    };
    document.addEventListener("keydown", handleEscape);
    return () => {
      document.removeEventListener("keydown", handleEscape);
    };
  }, []);

  const inputBorderStyleKey = () => {
    if (isError) return "error";
    if (isPopupOpen || isFocused) return "active";
    return "default";
  };

  const cursorStyleKey = () => {
    if (disabled) return "disabled";
    if (!multiSelectable && values.length > 0) return "singleSelected";
    return "default";
  };

  return (
    <>
      <div
        ref={wrapperRef}
        className={clsx(
          styles.selectBoxStyle,
          inputBorderStyle[inputBorderStyleKey()],
          disabled && styles.selectBoxDisabledStyle,
          styles.selectBoxCursorStyle[cursorStyleKey()]
        )}
        style={{ width: expand ? "100%" : width }}
        role="group"
        onClick={handleClickWrapper}
        onFocus={() => {
          setIsFocused(true);
          setIsPopupOpen(true);
        }}
        onBlur={() => setIsFocused(false)}
      >
        <div className={styles.selectBoxInnerBoxStyle}>
          <WizHStack align="center" height="100%" gap="xs" pr="xl">
            {selectedOptions.map((selectedOption, i) => (
              <span
                key={`${selectedOption.label}-${selectedOption.value}`}
                className={styles.selectBoxInnerBoxSelectedItemStyle}
              >
                <span className={styles.selectBoxInnerBoxSelectedLabelStyle}>
                  {selectedOption.label}
                  {showExLabel &&
                    selectedOption.exLabel &&
                    ` (${selectedOption.exLabel})`}
                </span>
                <button
                  type="button"
                  ref={(ref) => (clearButtonsRef.current[i] = ref)}
                  className={styles.selectBoxInnerBoxCloseButtonStyle}
                  disabled={disabled}
                  onClick={handleClickClearButton(selectedOption)}
                  onKeyDown={keyDownHandlers.clearButton(selectedOption)}
                >
                  <span className={styles.selectBoxInnerBoxCloseStyle}>
                    <WizIcon icon={WizIClose} size="xs" color="gray.500" />
                  </span>
                </button>
              </span>
            ))}
            {(multiSelectable || values.length === 0) && (
              <input
                ref={searchTextboxRef}
                className={styles.selectBoxSearchInputStyle}
                value={searchText}
                placeholder={
                  selectedOptions.length === 0 ? placeholder : undefined
                }
                disabled={disabled}
                onChange={(e) => {
                  setSearchText(e.target.value);
                  if (onInputSearchText) onInputSearchText(e.target.value);
                  setIsPopupOpen(true);
                }}
                onKeyDown={keyDownHandlers.input}
              />
            )}
          </WizHStack>
        </div>
        <div className={styles.selectBoxExpandIconStyle}>
          {isPopupOpen ? (
            <div className={styles.selectBoxInnerBoxLessStyle}>
              <WizIcon icon={WizIExpandLess} color="green.800" />
            </div>
          ) : (
            <div className={styles.selectBoxInnerBoxMoreStyle}>
              <WizIcon icon={WizIExpandMore} />
            </div>
          )}
        </div>
      </div>
      {buttonGroupOptions.length > 0 && (
        <WizPopup
          anchorElement={wrapperRef}
          isOpen={isPopupOpen}
          layer="popover"
          isDirectionFixed={isDirectionFixed}
          onClose={() => {
            setIsFocused(false);
            setIsPopupOpen(false);
          }}
        >
          <div
            ref={popupRef}
            className={styles.selectBoxSelectorStyle}
            style={{ minWidth: width }}
          >
            <WizPopupButtonGroup
              showExLabel={showExLabel}
              options={buttonGroupOptions}
            />
          </div>
        </WizPopup>
      )}
    </>
  );
};

SearchSelector.displayName = ComponentName.SearchSelector;

export const WizSearchSelector = SearchSelector;

// packages/wiz-ui/src/components/base/inputs/search-selector/search-selector.vue
<template>
  <WizPopupContainer :expand="expand">
    <div
      :class="[
        selectBoxStyle,
        inputBorderStyle[state],
        disabled && selectBoxDisabledStyle,
        selectBoxCursorStyle[selectBoxCursor],
      ]"
      :style="{ width: computedWidth }"
    >
      <div :class="selectBoxInnerBoxStyle" @click="toggleDropdown">
        <WizHStack align="center" height="100%" gap="xs" pr="xl" :wrap="true">
          <span
            v-for="(item, i) in selectedItem"
            :key="`${item.label}-${item.value}`"
            :class="selectBoxInnerBoxSelectedItemStyle"
          >
            <span :class="selectBoxInnerBoxSelectedLabelStyle">
              {{ item.label
              }}{{ showExLabel && item.exLabel ? " " + item.exLabel : "" }}
            </span>
            <button
              type="button"
              @click="onClear(item.value)"
              @keypress.enter="onClear(item.value)"
              @keydown="(e) => onKeydownBackspace.unselect(item.value, e)"
              :class="selectBoxInnerBoxCloseButtonStyle"
              :ref="setUnselectableRef(i)"
              :aria-label="ARIA_LABELS.SEARCH_SELECTOR.UNSELECT"
            >
              <WizIcon
                :icon="WizIClose"
                :class="selectBoxInnerBoxCloseStyle"
                :size="'xs'"
                :color="'gray.500'"
              />
            </button>
          </span>
          <input
            v-if="multiSelectable || !isValueMatched"
            :class="selectBoxSearchInputStyle"
            :value="searchValue"
            @input="onSetSearchValue"
            :placeholder="selectedItem.length === 0 ? placeholder : ''"
            ref="inputRef"
            :disabled="disabled"
            @keydown="onKeydownBackspace.focus"
          />
        </WizHStack>
      </div>
      <button
        type="button"
        :class="selectBoxExpandIconStyle"
        @click="toggleSelectBox"
        :disabled="disabled"
        :aria-label="ARIA_LABELS.SEARCH_SELECTOR.EXPAND"
      >
        <WizIcon
          v-if="isOpen"
          :icon="WizIExpandLess"
          :class="selectBoxInnerBoxLessStyle"
          :color="!isOpen ? 'white.800' : 'green.800'"
        />

        <WizIcon
          v-else-if="!isOpen"
          :icon="WizIExpandMore"
          :class="selectBoxInnerBoxMoreStyle"
        />
      </button>
    </div>
    <WizPopup
      layer="popover"
      :isOpen="isOpen"
      :isDirectionFixed="isDirectionFixed"
      @onClose="emit('toggle', false)"
    >
      <div
        :class="selectBoxSelectorStyle"
        :style="{
          minWidth: width,
        }"
        v-if="
          filteredOptions.length > 0 ||
          (searchValue !== '' && !options.some((v) => v.label === searchValue))
        "
      >
        <WizVStack gap="xs2">
          <WizPopupButtonGroup
            :showExLabel="showExLabel"
            :options="
              addButtonEnabled ? [addButton, ...selectButtons] : selectButtons
            "
          />
        </WizVStack>
      </div>
    </WizPopup>
  </WizPopupContainer>
</template>

<script setup lang="ts">
import { ARIA_LABELS, ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  selectBoxCursorStyle,
  selectBoxDisabledStyle,
  selectBoxExpandIconStyle,
  selectBoxInnerBoxCloseButtonStyle,
  selectBoxInnerBoxCloseStyle,
  selectBoxInnerBoxLessStyle,
  selectBoxInnerBoxMoreStyle,
  selectBoxInnerBoxSelectedItemStyle,
  selectBoxInnerBoxSelectedLabelStyle,
  selectBoxInnerBoxStyle,
  selectBoxSearchInputStyle,
  selectBoxSelectorStyle,
  selectBoxStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/search-selector.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { ComponentPublicInstance, PropType, computed, inject, ref } from "vue";

import {
  WizIcon,
  WizPopup,
  WizPopupButtonGroup,
  WizPopupContainer,
} from "@/components";
import {
  WizIAddCircle,
  WizIClose,
  WizIExpandLess,
  WizIExpandMore,
} from "@/components/icons";
import { formControlKey } from "@/hooks/use-form-control-provider";

import { ButtonGroupItem } from "../../popup-button-group/types";
import { WizHStack, WizVStack } from "../../stack";

import { levenshteinDistance } from "./levenshtein-distance";
import { SelectBoxOption } from "./types";

defineOptions({
  name: ComponentName.SearchSelector,
});

interface Emit {
  (e: "input", value: number): void;
  (e: "unselect", value: number): void;
  (e: "add", label: string): void;
  (e: "toggle", value: boolean): void;
  (e: "setSearchValue", value: string): void;
}

const props = defineProps({
  options: {
    type: Array as PropType<SelectBoxOption[]>,
    required: true,
  },
  value: {
    type: Array as PropType<number[]>,
    required: true,
  },
  searchValue: {
    type: String,
    required: true,
  },
  placeholder: {
    type: String,
    required: false,
    default: "選択してください",
  },
  width: {
    type: String,
    required: false,
    default: "10rem",
  },
  disabled: {
    type: Boolean,
    required: false,
    default: false,
  },
  expand: {
    type: Boolean,
    required: false,
  },
  multiSelectable: {
    type: Boolean,
    required: false,
    default: false,
  },
  addable: {
    type: Boolean,
    required: false,
    default: false,
  },
  isOpen: {
    type: Boolean,
    required: true,
  },
  isDirectionFixed: {
    type: Boolean,
    required: false,
    default: false,
  },
  showExLabel: {
    type: Boolean,
    required: false,
    default: false,
  },
});

const emit = defineEmits<Emit>();

const inputRef = ref<HTMLElement | undefined>();
const backspaceUnselectableRef = ref();

const toggleDropdown = () => {
  if (props.disabled) return;
  if (!props.multiSelectable && props.value.length > 0 && props.isOpen) {
    return emit("toggle", false);
  }
  emit("toggle", true);
  inputRef.value?.focus();
};

const deepCopy = <T>(ary: T): T => JSON.parse(JSON.stringify(ary));

const selectByLevenshteinAndPartialMatch = (
  options: SelectBoxOption[],
  target: string
) => {
  const dist = options.reduce((acc, str) => {
    acc[str.label] = levenshteinDistance(str.label, target);
    return acc;
  }, {} as { [key: string]: number });
  const minLength = Math.min(...Object.values(dist));
  const closestWords = options.filter(
    (option) => dist[option.label] === minLength
  );

  const exactMatch = options.filter((option) => {
    const isIncluded = option.label.indexOf(target) !== -1;
    return isIncluded && !closestWords.includes(option);
  });
  return closestWords.concat(exactMatch);
};

const valueToOption = computed(() =>
  props.options.reduce((acc, item) => {
    acc[item.value] = item;
    return acc;
  }, {} as { [value: number]: SelectBoxOption })
);

const selectedItem = computed(() => {
  return props.value.map((v) => valueToOption.value[v]);
});

const setUnselectableRef =
  (index: number) => (el: ComponentPublicInstance | Element | null) => {
    if (el && index === selectedItem.value.length - 1)
      backspaceUnselectableRef.value = el;
  };

const filteredOptions = computed(() => {
  const sortedOptions =
    props.searchValue.length !== 0
      ? selectByLevenshteinAndPartialMatch(
          deepCopy(props.options),
          props.searchValue
        )
      : props.options;
  const removeSelectedOptions = (options: SelectBoxOption[]) => {
    return options.filter((v) => {
      return !selectedItem.value.some((item) => item.value === v.value);
    });
  };
  return removeSelectedOptions(sortedOptions);
});

const toggleSelectBox = () => {
  if (!props.disabled) emit("toggle", !props.isOpen);
};

const onClear = (n: number) => {
  emit("unselect", n);
  inputRef.value?.focus();
};

const onSetSearchValue = (e: Event) => {
  const text = (e.target as HTMLInputElement).value;
  emit("setSearchValue", text);
};

const onKeydownBackspace = {
  focus: (event: KeyboardEvent) => {
    if (
      event.key === "Backspace" &&
      props.searchValue === "" &&
      props.value.length > 0
    ) {
      backspaceUnselectableRef.value?.focus();
    }
  },
  unselect: (n: number, event: KeyboardEvent) => {
    if (event.key === "Backspace") {
      onClear(n);
    }
  },
};

const onSelect = (value: number) => {
  if (!props.multiSelectable) {
    toggleSelectBox();
    props.value.forEach((v) => {
      onClear(v);
    });
  }
  emit("setSearchValue", "");
  emit("input", value);
  toggleDropdown();
};
const onCreate = (label: string) => {
  emit("add", label);
  emit("setSearchValue", "");
};

const selectBoxCursor = computed(() => {
  if (props.disabled) return "disabled";
  if (!props.multiSelectable && props.value.length > 0) return "singleSelected";
  return "default";
});

// Form Control
const form = inject(formControlKey);
const isError = computed(() => (form ? form.isError.value : false));

const computedWidth = computed(() => (props.expand ? "100%" : props.width));

const state = computed(() => {
  if (isError.value) return "error";
  if (props.isOpen) return "active";
  return "default";
});

const isValueMatched = computed(() => {
  return props.value.length > 0;
});

const addButtonEnabled = computed(
  () =>
    props.addable &&
    props.searchValue !== "" &&
    !props.options.some((v) => v.label === props.searchValue)
);

const addButton = computed(() => {
  const option: ButtonGroupItem = {
    kind: "button",
    option: {
      label: props.searchValue,
      icon: addButtonEnabled.value ? WizIAddCircle : undefined,
      iconDefaultColor: "green.800",
      value: -1,
      onClick: () => {
        onCreate(props.searchValue);
      },
    },
  };
  return option;
});

const selectButtons = computed(() => {
  return filteredOptions.value.map((opt) => {
    const option: ButtonGroupItem = {
      kind: "button",
      option: {
        label: opt.label,
        value: opt.value,
        exLabel: opt.exLabel,
        onClick: () => onSelect(opt.value),
      },
    };
    return option;
  });
});
</script>
