// packages/wiz-ui-react/src/components/base/inputs/base/components/base.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/base-input.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { clsx } from "clsx";
import {
  ComponentProps,
  ForwardedRef,
  forwardRef,
  memo,
  useState,
} from "react";

type Props = {
  id?: string;
  value?: string;
  placeholder?: string;
  disabled?: boolean;
  expand?: boolean;
  type?: "text" | "password";
  width?: string;
  error?: boolean;
  spaceType?: "left" | "right" | "both" | "none";
} & ComponentProps<"input">;

const _PrivateBaseInput = forwardRef(
  (
    {
      id,
      value,
      placeholder,
      disabled,
      expand,
      type,
      width = "10rem",
      error,
      spaceType = "none",
      ...props
    }: Props,
    ref: ForwardedRef<HTMLInputElement>
  ) => {
    const [hasFocus, setHasFocus] = useState(false);

    const state = (() => {
      if (error) return "error";
      if (hasFocus) return "active";
      return "default";
    })();

    return (
      <input
        ref={ref}
        {...props}
        className={clsx(
          styles.baseInputStyle,
          styles.baseInputPaddingStyle[spaceType],
          disabled && styles.baseInputDisabledStyle,
          inputBorderStyle[state]
        )}
        style={{ width: expand ? "100%" : width }}
        placeholder={placeholder}
        disabled={disabled}
        type={type}
        id={id}
        onFocus={(e) => {
          setHasFocus(true);
          props.onFocus?.(e);
        }}
        onBlur={(e) => {
          setHasFocus(false);
          props.onBlur?.(e);
        }}
        onChange={props.onChange}
        value={value}
      />
    );
  }
);

_PrivateBaseInput.displayName = ComponentName.BaseInput;

export const PrivateBaseInput = memo(_PrivateBaseInput);

// packages/wiz-ui-next/src/components/base/inputs/base/base.vue
<template>
  <input
    :class="[
      baseInputStyle,
      baseInputPaddingStyle[spaceType],
      disabled && baseInputDisabledStyle,
      inputBorderStyle[state],
    ]"
    :style="{ width: computedWidth }"
    :placeholder="placeholder"
    :name="name"
    :disabled="disabled"
    :type="type"
    @focusin="hasFocus = true"
    @focusout="hasFocus = false"
    v-model="value"
  />
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  baseInputStyle,
  baseInputDisabledStyle,
  baseInputPaddingStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/base-input.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import { computed, ref, PropType } from "vue";

defineOptions({
  name: ComponentName.BaseInput,
});

const props = defineProps({
  modelValue: {
    type: String,
    required: true,
  },
  name: {
    type: String,
    required: true,
  },
  placeholder: {
    type: String,
    required: false,
  },
  disabled: {
    type: Boolean,
    required: false,
  },
  expand: {
    type: Boolean,
    required: false,
  },
  type: {
    type: String as PropType<"text" | "password">,
    required: false,
  },
  width: {
    type: String,
    required: false,
    default: "10rem",
  },
  error: {
    type: Boolean,
    required: false,
  },
  spaceType: {
    type: String as PropType<"left" | "right" | "both" | "none">,
    required: false,
    default: "none",
  },
});

interface Emit {
  (e: "update:modelValue", value: string): void;
}

const emit = defineEmits<Emit>();

const value = computed({
  get: () => props.modelValue,
  set: (value) => emit("update:modelValue", value),
});

const hasFocus = ref(false);

const computedWidth = computed(() => (props.expand ? "100%" : props.width));

const state = computed(() => {
  if (props.error) return "error";
  if (hasFocus.value) return "active";
  return "default";
});
</script>
