// packages/wiz-ui-react/src/components/base/tab/components/tab-pane.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/tab.css";
import clsx from "clsx";
import { FC } from "react";

type Props = {
  label: string;
  name: string;
  active?: boolean;
  disabled?: boolean;
  notificationCount?: number;
  width?: string;
  onClick: (name: string) => void;
};

const TabPane: FC<Props> = ({
  label,
  name,
  active,
  disabled,
  notificationCount,
  width = "100%",
  onClick,
}: Props) => {
  const variant = (() => {
    if (active) return "active";
    if (disabled) return "disabled";
    return "default";
  })();

  return (
    <div
      className={clsx(styles.tabPaneStyle, styles.tabPaneVariantStyle[variant])}
      style={{ width }}
      onClick={() => disabled || onClick(name)}
    >
      <span className={styles.tabPaneLabelStyle}>{label}</span>
      {notificationCount !== 0 && (
        <span className={styles.tabPaneNotificationStyle}>
          {notificationCount}
        </span>
      )}
    </div>
  );
};

TabPane.displayName = ComponentName.TabPane;

export const WizTabPane = TabPane;

// packages/wiz-ui/src/components/base/tab/tab-pane.vue
<template>
  <div
    :class="[tabPaneStyle, tabPaneVariantStyle[variant]]"
    :style="{ width }"
    @click="onClick"
  >
    <span :class="tabPaneLabelStyle">{{ label }}</span>
    <span v-if="notificationCount" :class="tabPaneNotificationStyle">{{
      notificationCount
    }}</span>
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  tabPaneStyle,
  tabPaneVariantStyle,
  tabPaneLabelStyle,
  tabPaneNotificationStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/tab.css";
import { computed } from "vue";

defineOptions({
  name: ComponentName.TabPane,
});

const props = defineProps({
  label: {
    type: String,
    required: true,
  },
  active: {
    type: Boolean,
    required: false,
  },
  disabled: {
    type: Boolean,
    required: false,
  },
  notificationCount: {
    type: Number,
    required: false,
  },
  width: {
    type: String,
    required: false,
    default: "100%",
  },
});

interface Emits {
  (event: "click"): void;
}

const emit = defineEmits<Emits>();

const onClick = () => props.disabled || emit("click");
const variant = computed(() => {
  if (props.disabled) return "disabled";
  if (props.active) return "active";
  return "default";
});
</script>
