// packages/wiz-ui/src/components/base/inputs/checkbox/checkbox.vue
<template>
  <div :class="styles.checkboxStyle">
    <WizStack :gap="gap" :direction="direction" wrap>
      <div v-for="option in options" :key="option.key">
        <input
          :class="styles.checkboxInputStyle"
          type="checkbox"
          :id="option.key"
          :name="option.key"
          :value="option.value"
          v-model="checkboxValue"
          :disabled="disabled || option.disabled"
        />
        <label
          :class="[
            styles.checkboxLabelStyle,
            checkboxValue.includes(option.value) &&
              styles.checkboxLabelCheckedStyle,
            (disabled || option.disabled) && styles.checkboxLabelDisabledStyle,
            styles.checkboxLabelCursorStyle[labelPointer(option.disabled)],
          ]"
          :for="option.key"
        >
          <WizICheck
            v-if="checkboxValue.includes(option.value)"
            :class="styles.checkboxIconStyle"
          />
          <span
            :class="[
              checkboxValue.includes(option.value) &&
                styles.checkboxBlockCheckedStyle,
              strikeThrough &&
                checkboxValue.includes(option.value) &&
                styles.checkboxLabelStrikeThrough,
            ]"
            >{{ option.label }}</span
          >
        </label>
      </div>
    </WizStack>
  </div>
</template>

<script setup lang="ts">
import { SpacingKeys } from "@wizleap-inc/wiz-ui-constants/styles/spacing";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/checkbox-input.css";
import { computed, PropType } from "vue";

import WizStack from "@/components/base/stack/stack.vue";
import { WizICheck } from "@/components/icons";

import { CheckBoxOption } from "./types";

const props = defineProps({
  options: {
    type: Array as PropType<CheckBoxOption[]>,
    required: true,
  },
  value: {
    type: Array as PropType<number[]>,
    required: true,
  },
  disabled: {
    type: Boolean,
    required: false,
  },
  direction: {
    type: String as PropType<"horizontal" | "vertical">,
    required: false,
    default: "horizontal",
  },
  gap: {
    type: String as PropType<SpacingKeys>,
    required: false,
    default: "xl",
  },
  strikeThrough: {
    type: Boolean,
    required: false,
    default: false,
  },
});

interface Emit {
  (e: "input", value: number[]): void;
}
const emit = defineEmits<Emit>();

const checkboxValue = computed({
  get: () => props.value,
  set: (value) => emit("input", value),
});

const labelPointer = (optionDisabled?: boolean) =>
  props.disabled || optionDisabled ? "disabled" : "default";
</script>

// packages/wiz-ui-react/src/components/base/inputs/checkbox/components/checkbox.tsx
import { SpacingKeys } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/checkbox-input.css";
import clsx from "clsx";
import { memo } from "react";

import { WizICheck } from "@/components/icons";

import { CheckBoxOption } from "./types";

type Props = {
  options: CheckBoxOption[];
  value: number[];
  disabled?: boolean;
  direction?: "horizontal" | "vertical";
  gap?: SpacingKeys;
  strikeThrough?: boolean;
  onChange?: (value: number, checked: boolean) => void;
};

const _CheckBox = ({
  options,
  value,
  disabled,
  direction = "horizontal",
  gap = "xl",
  strikeThrough = false,
  ...props
}: Props) => {
  const labelPointer = (optionDisabled?: boolean) =>
    disabled || optionDisabled ? "disabled" : "default";
  return (
    <div className={styles.checkboxStyle}>
      {/* <WizWtack gap={gap} direction={direction} wrap> */}
      <div>
        {options?.map((option) => {
          return (
            <div key={option.key}>
              <input
                className={styles.checkboxInputStyle}
                type="checkbox"
                id={option.key}
                name={option.key}
                value={option.value}
                disabled={disabled || option.disabled}
                onChange={(e) => {
                  props.onChange?.(option.value, e.target.checked);
                }}
              />
              <label
                className={clsx(
                  styles.checkboxLabelStyle,
                  value.includes(option.value) &&
                    styles.checkboxLabelCheckedStyle,
                  (disabled || option.disabled) &&
                    styles.checkboxLabelDisabledStyle,
                  styles.checkboxLabelCursorStyle[labelPointer(option.disabled)]
                )}
                htmlFor={option.key}
              >
                {value.includes(option.value) && (
                  <div className={styles.checkboxIconStyle}>
                    <WizICheck />
                  </div>
                )}
                <span
                  className={clsx(
                    value.includes(option.value) &&
                      styles.checkboxBlockCheckedStyle,
                    strikeThrough &&
                      value.includes(option.value) &&
                      styles.checkboxLabelStrikeThrough
                  )}
                >
                  {option.label}
                </span>
              </label>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export const WizCheckBox = memo(_CheckBox);
