// packages/wiz-ui-next/src/components/base/inputs/checkbox/checkbox.vue
<template>
  <div :class="checkboxStyle">
    <WizStack :gap="gap" :direction="direction" wrap>
      <div v-for="(option, key) in options" :key="key">
        <input
          :class="checkboxInputStyle"
          type="checkbox"
          :id="`checkbox${key}`"
          :name="`checkbox${key}`"
          :value="option.value"
          v-model="checkboxValue"
          :disabled="disabled || disabledKey === key"
        />
        <label
          :class="[
            checkboxLabelStyle,
            checkboxValue.includes(option.value) && checkboxLabelCheckedStyle,
            (disabled || disabledKey === key) && checkboxLabelDisabledStyle,
            checkboxLabelCursorStyle[labelPointer(key)],
          ]"
          :for="`checkbox${key}`"
        >
          <span
            :class="[
              checkboxBlockStyle,
              checkboxValue.includes(option.value) && checkboxBlockCheckedStyle,
            ]"
            >{{ option.label }}</span
          >
        </label>
      </div>
    </WizStack>
  </div>
</template>

<script setup lang="ts">
import { SpacingKeys } from "@wizleap-inc/wiz-ui-constants/styles/spacing";
import {
  checkboxStyle,
  checkboxInputStyle,
  checkboxLabelStyle,
  checkboxLabelCheckedStyle,
  checkboxLabelDisabledStyle,
  checkboxLabelCursorStyle,
  checkboxBlockStyle,
  checkboxBlockCheckedStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/checkbox-input.css";
import { computed } from "vue";

import WizStack from "@/components/base/stack/stack.vue";

import { CheckBoxOption } from "./types";

interface Props {
  options: CheckBoxOption[];
  modelValue: number[];
  disabled?: boolean;
  disabledKey?: number;
  direction?: "horizontal" | "vertical";
  gap?: SpacingKeys;
}

const props = withDefaults(defineProps<Props>(), {
  disabled: false,
  direction: "horizontal",
  gap: "xl",
});

interface Emit {
  (e: "update:modelValue", value: number[]): void;
}
const emit = defineEmits<Emit>();

const checkboxValue = computed({
  get: () => props.modelValue,
  set: (value) => emit("update:modelValue", value),
});

const labelPointer = (key: number) =>
  props.disabled || props.disabledKey === key ? "disabled" : "default";
</script>

// packages/wiz-ui-react/src/components/base/inputs/checkbox/components/checkbox.tsx
import { ComponentName, SpacingKeys } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/checkbox-input.css";
import clsx from "clsx";
import { FC } from "react";

import { WizICheck, WizStack } from "@/components";

import { CheckBoxOption } from "./types";

type Props = {
  options: CheckBoxOption[];
  value: number[];
  disabled?: boolean;
  direction?: "horizontal" | "vertical";
  gap?: SpacingKeys;
  strikeThrough?: boolean;
  onChange?: (value: number[]) => void;
};

const CheckBox: FC<Props> = ({
  options,
  value,
  disabled,
  direction = "horizontal",
  gap = "xl",
  strikeThrough = false,
  onChange,
}) => {
  return (
    <div className={styles.checkboxStyle}>
      <WizStack gap={gap} direction={direction} wrap>
        {options.map((option) => {
          const isChecked = value.includes(option.value);
          const isDisabled = disabled || option.disabled;
          return (
            <div key={option.key}>
              <input
                className={styles.checkboxInputStyle}
                type="checkbox"
                id={option.key}
                name={option.key}
                value={option.value}
                checked={isChecked}
                disabled={isDisabled}
                onChange={() => {
                  if (!onChange) {
                    return;
                  }
                  if (isChecked) {
                    onChange(value.filter((v) => v !== option.value));
                  } else {
                    onChange([...value, option.value]);
                  }
                }}
              />
              <label
                className={clsx(
                  styles.checkboxLabelStyle,
                  isChecked && styles.checkboxLabelCheckedStyle,
                  isDisabled && styles.checkboxLabelDisabledStyle,
                  styles.checkboxLabelCursorStyle[
                    isDisabled ? "disabled" : "default"
                  ]
                )}
                htmlFor={option.key}
              >
                {isChecked && (
                  <div className={styles.checkboxIconStyle}>
                    <WizICheck />
                  </div>
                )}
                <span
                  className={clsx(
                    isChecked && styles.checkboxBlockCheckedStyle,
                    strikeThrough &&
                      isChecked &&
                      styles.checkboxLabelStrikeThrough
                  )}
                >
                  {option.label}
                </span>
              </label>
            </div>
          );
        })}
      </WizStack>
    </div>
  );
};

CheckBox.displayName = ComponentName.CheckBox;

export const WizCheckBox = CheckBox;
