// packages/wiz-ui/src/components/base/snackbar/snackbar.vue
<template>
  <div
    :class="[
      snackbarStyle,
      !isStatic && snackbarFixedStyle,
      isHidden && snackbarHiddenStyle,
    ]"
    :style="{
      bottom: `${bottom}`,
      left: `${left}`,
    }"
    ref="snackbarRef"
  >
    <div :class="snackbarContainerStyle">
      <WizIcon color="white.800" :icon="WizICircleCheck" />
      <div :class="snackbarMessageStyle">
        <WizText color="white.800" fontSize="sm">{{ message }}</WizText>
      </div>
      <button :class="snackbarCloseButtonStyle" @click="onDelete">
        <WizIcon color="white.800" :icon="WizIClose" />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  snackbarStyle,
  snackbarFixedStyle,
  snackbarContainerStyle,
  snackbarHiddenStyle,
  snackbarMessageStyle,
  snackbarCloseButtonStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/snackbar.css";
import { ref, onMounted } from "vue";

import { WizText, WizIcon, WizICircleCheck, WizIClose } from "@/components";

interface Emits {
  (event: "delete"): void;
}

defineOptions({
  name: ComponentName.PopupContainer,
});

const props = defineProps({
  message: {
    type: String,
    required: true,
  },
  bottom: {
    type: String,
    required: false,
    default: "0",
  },
  left: {
    type: String,
    required: false,
    default: "0",
  },
  isStatic: {
    type: Boolean,
    required: false,
    default: false,
  },
});

const emits = defineEmits<Emits>();

const snackbarRef = ref<HTMLElement | undefined>();
const isHidden = ref(props.isStatic ? false : true);

const onDelete = () => {
  isHidden.value = true;
  setTimeout(() => emits("delete"), 200);
};

if (!props.isStatic) {
  setTimeout(onDelete, 3000);
}

onMounted(() => {
  if (snackbarRef.value?.clientWidth) {
    isHidden.value = false;
  }
});
</script>

// packages/wiz-ui-react/src/components/base/snackbar/components/snackbar.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/snackbar.css";
import clsx from "clsx";
import { FC, useCallback, useEffect, useState } from "react";

import { WizICircleCheck, WizIClose, WizIcon, WizText } from "@/components";

const ANIMATION_DURATION = 200;
const DISPLAY_DURATION = 3000;

type Props = {
  message: string;
  enableAnimation?: boolean;
  autoClose?: boolean;
  onClose: () => void;
};

const Snackbar: FC<Props> = ({
  message,
  enableAnimation = false,
  autoClose = false,
  onClose,
}) => {
  const [isHidden, setIsHidden] = useState(enableAnimation ? true : false);

  useEffect(() => {
    setIsHidden(false);
  }, [enableAnimation]);

  const handleClose = useCallback(() => {
    if (!enableAnimation) {
      onClose();
      return;
    }
    setIsHidden(true);
    setTimeout(() => {
      onClose();
    }, ANIMATION_DURATION);
  }, [enableAnimation, onClose]);

  useEffect(() => {
    if (!autoClose) {
      return;
    }
    setTimeout(() => {
      handleClose();
    }, DISPLAY_DURATION);
    // 初回のみ autoClose を設定し、以後 Props の変化で発火させないようにする
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div
      className={clsx(
        styles.snackbarStyle,
        isHidden && styles.snackbarHiddenStyle
      )}
    >
      <div className={styles.snackbarContainerStyle}>
        <WizIcon icon={WizICircleCheck} color="white.800" />
        <div className={styles.snackbarMessageStyle}>
          <WizText color="white.800" fontSize="sm">
            {message}
          </WizText>
        </div>
        <button
          className={styles.snackbarCloseButtonStyle}
          onClick={handleClose}
        >
          <WizIcon icon={WizIClose} color="white.800" />
        </button>
      </div>
    </div>
  );
};

Snackbar.displayName = ComponentName.SnackBar;

export const WizSnackbar = Snackbar;
