// examples/vue2/src/components/layout/navigation/index.vue
<template>
  <WizNavContainer sticky>
    <WizNavItem
      v-for="(item, i) in navigationItems"
      :key="i"
      :icon="item.icon"
      :label="item.label"
      :to="item.to"
      :active="item.active"
    />
    <template #footer>
      <FooterInfo />
    </template>
  </WizNavContainer>
</template>

<script setup lang="ts">
import {
  WizNavContainer,
  WizNavItem,
  WizIDashboard,
  WizIAssignment,
  WizIBusinessCenter,
  WizIHelp,
  WizIInfo,
} from "@wizleap-inc/wiz-ui";
import { computed } from "vue";
import { useRoute } from "vue-router/composables";

import FooterInfo from "./footer-info.vue";

const route = useRoute();
const currentPath = computed(() => route.path);

const navigationItems = computed(() => [
  {
    icon: WizIDashboard,
    label: "Home",
    to: "/",
    active: currentPath.value === "/",
  },
  {
    icon: WizIAssignment,
    label: "About",
    to: "/about",
    active: currentPath.value === "/about",
  },
  {
    icon: WizIBusinessCenter,
    label: "Contact",
    to: "/contact",
    active: currentPath.value === "/contact",
  },
  {
    icon: WizIHelp,
    label: "Help",
    to: "/help",
    active: currentPath.value === "/help",
  },
  {
    icon: WizIInfo,
    label: "Breakpoint",
    to: "/breakpoint",
    active: currentPath.value === "/breakpoint",
  },
]);
</script>

// examples/react/src/components/layout/navigation/index.tsx
import {
  WizAnchor,
  WizIAssignment,
  WizIBusinessCenter,
  WizIChat,
  WizIDashboard,
  WizIHelp,
  WizIOpenInNew,
  WizNavigationContainer,
  WizNavigationItem,
  WizVStack,
} from "@wizleap-inc/wiz-ui-react";

const navItems = [
  {
    icon: WizIDashboard,
    label: "Home",
    href: "/",
  },
  {
    icon: WizIAssignment,
    label: "About",
    href: "/about",
  },
  {
    icon: WizIBusinessCenter,
    label: "Contact",
    href: "/contact",
  },
  {
    icon: WizIChat,
    label: "Chat",
    href: "/chat",
  },
  {
    icon: WizIHelp,
    label: "Help",
    href: "https://wizleap.co.jp",
  },
];

const Footer = () => (
  <WizVStack>
    <WizAnchor
      href="https://wizleap.co.jp"
      icon={WizIOpenInNew}
      iconPosition="right"
      color="gray.700"
      fontSize="sm"
      openInNewTab
      nowrap
    >
      会社概要
    </WizAnchor>
    <WizAnchor
      href="https://wizleap.co.jp/services/"
      icon={WizIOpenInNew}
      iconPosition="right"
      color="gray.700"
      fontSize="sm"
      openInNewTab
      nowrap
    >
      サービス
    </WizAnchor>
    <WizAnchor
      href="https://wizleap.co.jp/news/"
      icon={WizIOpenInNew}
      iconPosition="right"
      color="gray.700"
      fontSize="sm"
      openInNewTab
      nowrap
    >
      ニュース
    </WizAnchor>
  </WizVStack>
);

type NavigationProps = {
  isOpen: boolean;
};

export const Navigation = ({ isOpen }: NavigationProps) => {
  return (
    <WizNavigationContainer
      style={{ display: "flex", height: "90vh" }}
      isOpen={isOpen}
      footer={<Footer />}
    >
      {navItems.map((path) => (
        <WizNavigationItem
          key={`path-${path.label}`}
          icon={path.icon}
          label={path.label}
          href="/"
          active={false}
        />
      ))}
    </WizNavigationContainer>
  );
};
