// packages/wiz-ui-react/src/components/base/dropdown/components/dropdown-item.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/dropdown.css";
import { FC, MouseEventHandler, ReactNode, useState } from "react";

import { WizHStack, WizIcon } from "@/components";
import { TIcon } from "@/components/icons";

type Props = {
  icon?: TIcon;
  disabled?: boolean;
  onClick?: MouseEventHandler<HTMLButtonElement>;
  children: ReactNode;
};

const DropdownItem: FC<Props> = ({
  icon,
  disabled = false,
  onClick,
  children,
}) => {
  const [isHover, setIsHover] = useState(false);
  const [isPressed, setIsPressed] = useState(false);

  function getIconColor() {
    if (isPressed) {
      return "white.800";
    }
    if (isHover) {
      return "green.800";
    }
    return undefined;
  }

  return (
    <button
      className={styles.dropdownItemStyle}
      disabled={disabled}
      onClick={onClick}
      onMouseOver={() => setIsHover(true)}
      onMouseOut={() => setIsHover(false)}
      onMouseDown={() => setIsPressed(true)}
      onMouseUp={() => setIsPressed(false)}
    >
      <WizHStack align="center">
        {children}
        {icon && <WizIcon icon={icon} size="md" color={getIconColor()} />}
      </WizHStack>
    </button>
  );
};

DropdownItem.displayName = ComponentName.DropdownItem;

export const WizDropdownItem = DropdownItem;

// packages/wiz-ui/src/components/base/dropdown/dropdown-item.vue
<template>
  <button
    type="button"
    :class="dropdownItemStyle"
    :disabled="disabled"
    @click="onClick"
    @mouseover="onMouseover"
    @mouseout="onMouseout"
    @mousedown="onMousedown"
    @mouseup="onMouseup"
  >
    <WizHStack align="center">
      <slot />
      <WizIcon v-if="icon" size="md" :icon="icon" :color="computedColor" />
    </WizHStack>
  </button>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import { dropdownItemStyle } from "@wizleap-inc/wiz-ui-styles/bases/dropdown.css";
import { PropType, computed, ref } from "vue";

import { WizHStack, WizIcon } from "@/components";
import type { TIcon } from "@/components/icons";

defineOptions({
  name: ComponentName.DropdownItem,
});

defineProps({
  icon: {
    type: Object as PropType<TIcon>,
  },
  disabled: {
    type: Boolean,
    required: false,
    default: false,
  },
});
interface Emit {
  (event: "click"): void;
}

const emit = defineEmits<Emit>();

const onClick = () => emit("click");

const isHover = ref(false);
const onMouseover = () => (isHover.value = true);
const onMouseout = () => (isHover.value = false);

const isPressed = ref(false);
const onMousedown = () => (isPressed.value = true);
const onMouseup = () => (isPressed.value = false);

const computedColor = computed(() => {
  if (isPressed.value) {
    return "white.800";
  }
  if (isHover.value) {
    return "green.800";
  }
  return undefined;
});
</script>
