// src/components/atoms/anchor/anchor.vue
<template>
  <a class="wiz-anchor" :href="href" :target="target" :rel="rel">
    <component v-if="icon" :is="icon" />
    <slot />
  </a>
</template>

<script setup lang="ts">
import Vue, { computed, withDefaults } from "vue";

import { FONT_SIZE_MAP } from "@/constants/styles/fontSize";
import { ColorKeys } from "@/types/styles/color";
import { FontSizeKeys } from "@/types/styles/fontSize";
import { getColorCss } from "@/utils/styles/color";

interface Props {
  href: string;
  color?: ColorKeys;
  fontSize?: FontSizeKeys;
  fontWeight?: "normal" | "bold";
  target?: "_blank" | "_self";
  icon?: Vue;
}

const props = withDefaults(defineProps<Props>(), {
  href: "#",
  color: "blue.800",
  fontSize: "md",
  fontWeight: "normal",
  target: "_self",
});

const rel = computed(() => {
  if (props.target === "_blank") {
    return "noopener noreferrer";
  }
  return undefined;
});

const computedColor = computed(() => {
  return getColorCss(props.color);
});

const computedFontSize = computed(() => {
  return FONT_SIZE_MAP[props.fontSize];
});

const computedFontWeight = computed(() => props.fontWeight);
</script>

<style lang="scss" scoped>
.wiz-anchor {
  line-height: 1.5;
  margin: 0;
  color: v-bind(computedColor);
  font-size: v-bind(computedFontSize);
  font-weight: v-bind(computedFontWeight);
  text-decoration: none;

  &:hover {
    // 未定
  }

  &:active {
    // 未定
  }

  & > svg {
    fill: v-bind(computedColor);
    vertical-align: top;
  }
}
</style>

// packages/wiz-ui-react/src/components/base/anchor/components/anchor.tsx
import {
  ColorKeys,
  ComponentName,
  FontSizeKeys,
  FontWeightKeys,
  getRelativeFontSize,
} from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/anchor.css";
import {
  colorStyle,
  fontSizeStyle,
  fontWeightStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import { ForwardedRef, ReactNode, forwardRef } from "react";

import { TIcon, WizIcon } from "@/components";

type Props = {
  to: string;
  color?: ColorKeys;
  fontSize?: FontSizeKeys;
  fontWeight?: FontWeightKeys;
  icon?: TIcon;
  iconPosition?: "left" | "right";
  openInNewTab?: boolean;
  nowrap?: boolean;
  children: ReactNode;
};

const Anchor = forwardRef(
  (
    {
      to,
      color = "blue.800",
      fontSize = "md",
      fontWeight = "normal",
      icon,
      iconPosition = "left",
      openInNewTab = false,
      nowrap = false,
      children,
    }: Props,
    ref: ForwardedRef<HTMLAnchorElement>
  ) => {
    const anchorStyle = clsx([
      styles.anchorStyle,
      colorStyle[color],
      fontSizeStyle[fontSize],
      fontWeightStyle[fontWeight],
      nowrap && styles.anchorNoWrapStyle,
    ]);

    const iconContent = icon && (
      <WizIcon
        icon={icon}
        size={getRelativeFontSize(fontSize, 3)}
        color={color}
      />
    );

    return (
      <a
        ref={ref}
        className={anchorStyle}
        href={to}
        target={openInNewTab ? "_blank" : undefined}
        rel={openInNewTab ? "noopener noreferrer" : undefined}
      >
        {iconPosition === "left" && iconContent}
        {children}
        {iconPosition === "right" && iconContent}
      </a>
    );
  }
);

Anchor.displayName = ComponentName.Anchor;

export const WizAnchor = Anchor;
