// src/components/atoms/stack/h-stack.vue
<template>
  <WizStack
    direction="horizontal"
    :gap="gap"
    :p="p"
    :pt="pt"
    :pr="pr"
    :pb="pb"
    :pl="pl"
    :px="px"
    :py="py"
    :m="m"
    :mt="mt"
    :mr="mr"
    :mb="mb"
    :ml="ml"
    :mx="mx"
    :my="my"
  >
    <slot />
  </WizStack>
</template>

<script setup lang="ts">
import { SpacingKeys } from "@/types/styles/spacing";

import { WizStack } from ".";

export interface Props {
  gap?: SpacingKeys;
  p?: SpacingKeys;
  pt?: SpacingKeys;
  pr?: SpacingKeys;
  pb?: SpacingKeys;
  pl?: SpacingKeys;
  px?: SpacingKeys;
  py?: SpacingKeys;
  m?: SpacingKeys;
  mt?: SpacingKeys;
  mr?: SpacingKeys;
  mb?: SpacingKeys;
  ml?: SpacingKeys;
  mx?: SpacingKeys;
  my?: SpacingKeys;
}

defineProps<Props>();
</script>

// packages/wiz-ui-react/src/components/base/stack/components/h-stack.tsx
import { memo } from "react";

import { WizStack } from "./stack";
import { StackProps } from "./types";

type Props = Omit<StackProps, "direction">;

const _HStack = ({ ...props }: Props) => {
  return (
    <WizStack direction="horizontal" {...props}>
      {props.children}
    </WizStack>
  );
};

export const WizHStack = memo(_HStack);
