// packages/wiz-ui-react/src/components/base/stack/components/h-stack.tsx
import { SpacingKeys } from "@wizleap-inc/wiz-ui-constants";
import { ReactNode, memo } from "react";

import { WizStack } from "./stack";

type Props = {
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around" | "evenly";
  wrap?: boolean;
  gap?: SpacingKeys;
  gx?: SpacingKeys;
  gy?: SpacingKeys;
  p?: SpacingKeys;
  pt?: SpacingKeys;
  pr?: SpacingKeys;
  pb?: SpacingKeys;
  pl?: SpacingKeys;
  px?: SpacingKeys;
  py?: SpacingKeys;
  m?: SpacingKeys;
  mt?: SpacingKeys;
  mr?: SpacingKeys;
  mb?: SpacingKeys;
  ml?: SpacingKeys;
  mx?: SpacingKeys;
  my?: SpacingKeys;
  width?: string;
  height?: string;
  overflow?: string;
  reverse?: string;
  position?: "relative" | "absolute" | "fixed" | "sticky" | "static";
  children?: ReactNode;
};

const _HStack = ({ ...props }: Props) => {
  return (
    <WizStack direction="horizontal" {...props}>
      {props.children}
    </WizStack>
  );
};

export const WizHStack = memo(_HStack);

// packages/wiz-ui/src/components/atoms/stack/h-stack.vue
<template>
  <WizStack
    direction="horizontal"
    :align="align"
    :justify="justify"
    :wrap="wrap"
    :gap="gap"
    :gx="gx"
    :gy="gy"
    :p="p"
    :pt="pt"
    :pr="pr"
    :pb="pb"
    :pl="pl"
    :px="px"
    :py="py"
    :m="m"
    :mt="mt"
    :mr="mr"
    :mb="mb"
    :ml="ml"
    :mx="mx"
    :my="my"
    :width="width"
    :overflow="overflow"
  >
    <slot />
  </WizStack>
</template>

<script setup lang="ts">
import { SpacingKeys } from "@/types/styles/spacing";

import { WizStack } from ".";

export interface Props {
  align?: "start" | "center" | "end" | "stretch";
  justify?: "start" | "center" | "end" | "between" | "around" | "evenly";
  wrap?: boolean;
  gap?: SpacingKeys;
  gx?: SpacingKeys;
  gy?: SpacingKeys;
  p?: SpacingKeys;
  pt?: SpacingKeys;
  pr?: SpacingKeys;
  pb?: SpacingKeys;
  pl?: SpacingKeys;
  px?: SpacingKeys;
  py?: SpacingKeys;
  m?: SpacingKeys;
  mt?: SpacingKeys;
  mr?: SpacingKeys;
  mb?: SpacingKeys;
  ml?: SpacingKeys;
  mx?: SpacingKeys;
  my?: SpacingKeys;
  width?: string;
  overflow?: string;
}

defineProps<Props>();
</script>
