// packages/wiz-ui/src/components/base/inputs/panel-switch/panel-switch.vue
<template>
  <div :class="styles.panelSwitchStyle">
    <label
      v-for="(item, key) in items"
      :key="key"
      :class="[
        styles.panelSwitchBlockStyle,
        key !== items.length - 1 && styles.panelSwitchBlockDividerStyle,
        key === 0 && styles.panelSwitchBlockLeftStyle,
        key === items.length - 1 && styles.panelSwitchBlockRightStyle,
        key === switchValue - 1 && styles.panelSwitchBlockActiveStyle,
        styles.panelSwitchBlockColorStyle[panelSwitchBlockColor(key)],
      ]"
      :for="`panel${key}`"
    >
      {{ item.label }}
      <input
        :class="styles.panelSwitchInputStyle"
        type="radio"
        :id="`panel${key}`"
        :name="`panel${key}`"
        :value="item.value"
        v-model="switchValue"
      />
    </label>
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/panel-switch-input.css";
import { computed, PropType } from "vue";

import { panelItems } from "./types";

defineOptions({
  name: ComponentName.PanelSwitch,
});

const props = defineProps({
  value: {
    type: Number,
    required: true,
  },
  items: {
    type: Array as PropType<panelItems[]>,
    required: true,
  },
});

interface Emit {
  (e: "input", value: number): void;
}

const emit = defineEmits<Emit>();

const switchValue = computed({
  get: () => props.value,
  set: (value) => emit("input", value),
});

const panelSwitchBlockColor = (key: number) =>
  key === switchValue.value - 1 ? "active" : "default";
</script>

// packages/wiz-ui-react/src/components/base/inputs/panel-switch/components/panel-switch.tsx
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/panel-switch-input.css";
import clsx from "clsx";
import { memo } from "react";

import { PanelItems } from "./type";

type Props = {
  value: number | null;
  items: PanelItems[];
  onClick?: (value: number) => void;
};
const _PanelSwitch = ({ value, items, ...props }: Props) => {
  const panelSwitchBlockColor = (key: number) =>
    value && key === value - 1 ? "active" : "default";
  return (
    <div className={styles.panelSwitchStyle}>
      {items.map((item, index) => (
        <label
          key={item.value}
          className={clsx(
            styles.panelSwitchBlockStyle,
            index !== items.length - 1 && styles.panelSwitchBlockDividerStyle,
            index === 0 && styles.panelSwitchBlockLeftStyle,
            index === items.length - 1 && styles.panelSwitchBlockRightStyle,
            value && index === value - 1 && styles.panelSwitchBlockActiveStyle,
            styles.panelSwitchBlockColorStyle[panelSwitchBlockColor(index)]
          )}
          htmlFor={`panel${item.value}`}
        >
          {item.label}
          <input
            className={styles.panelSwitchInputStyle}
            type="radio"
            id={`panel${item.value}`}
            name={`panel${item.value}`}
            value={item.value}
            onClick={() => props.onClick?.(item.value)}
          />
        </label>
      ))}
    </div>
  );
};

export const WizPanelSwitch = memo(_PanelSwitch);
