// packages/wiz-ui/src/components/base/progress-bar/progress-point.vue
<template>
  <span
    :class="[
      progressPointStyle,
      status !== 'none' && progressPointVariantStyle[status],
    ]"
  >
    <span
      :class="[
        progressPointValueStyle,
        progressPointValueColorStyle[
          status === 'active' ? 'active' : 'inactive'
        ],
      ]"
    >
      {{ value }}
    </span>
  </span>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  progressPointStyle,
  progressPointValueColorStyle,
  progressPointValueStyle,
  progressPointVariantStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/progress-bar.css";

import type { ProgressStatus } from "./types";

defineOptions({
  name: ComponentName.ProgressPoint,
});

interface Props {
  status: ProgressStatus;
  value?: number;
}

defineProps<Props>();
</script>

// packages/wiz-ui-react/src/components/base/progress-bar/components/progress-point.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/progress-bar.css";
import clsx from "clsx";
import { FC } from "react";

import type { ProgressStatus } from "../types";

type Props = {
  status: ProgressStatus;
  value?: number;
};

const ProgressPoint: FC<Props> = ({ status, value }) => {
  return (
    <span
      className={clsx([
        [
          styles.progressPointStyle,
          status !== "none" && styles.progressPointVariantStyle[status],
        ],
      ])}
    >
      <span
        className={clsx([
          styles.progressPointValueStyle,
          styles.progressPointValueColorStyle[
            status === "active" ? "active" : "inactive"
          ],
        ])}
      >
        {value}
      </span>
    </span>
  );
};

ProgressPoint.displayName = ComponentName.ProgressPoint;

export const WizProgressPoint = ProgressPoint;
