// packages/wiz-ui-next/src/components/base/progress-bar/progress-bar.vue
<template>
  <div :class="styles.progressBarStyle">
    <div
      v-for="(content, i) in contents"
      :key="i"
      :class="styles.progressBarItemStyle[i === 0 ? 'first' : 'default']"
    >
      <WizTooltip>
        <template #content v-if="content.tooltip">
          {{ content.status === "none" ? undefined : content.tooltip }}
        </template>
        <div :class="styles.progressBarPointWrapperStyle">
          <span :class="styles.progressBarItemAnnotationStyle">
            <WizText fontSize="xs2" color="red.800" whiteSpace="nowrap">
              {{ content.annotation }}
            </WizText>
          </span>
          <WizProgressPoint :status="content.status" :value="content.value" />
          <span :class="styles.progressBarItemLabelStyle">
            <WizText fontSize="xs2" color="gray.600" whiteSpace="nowrap">
              {{ content.label }}
            </WizText>
          </span>
        </div>
      </WizTooltip>
      <WizProgressLine :active="content.progress" :isFirst="i === 0" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/progress-bar.css";
import { PropType } from "vue";

import { WizText } from "@/components/base/text";
import { WizTooltip } from "@/components/base/tooltip";

import { WizProgressPoint, WizProgressLine } from ".";

import type { ProgressItem } from "./types";

defineOptions({
  name: ComponentName.ProgressBar,
});

defineProps({
  contents: {
    type: Array as PropType<ProgressItem[]>,
    required: true,
  },
});
</script>

// packages/wiz-ui-react/src/components/base/progress-bar/components/progress-bar.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/progress-bar.css";
import { ReactNode } from "react";

import { WizText, WizTooltip } from "@/components";

import { ProgressItem } from "../types";

import { WizProgressPoint } from "./progress-point";

import { WizProgressLine } from ".";

type Props = {
  contents: ProgressItem[];
  children?: ReactNode;
};

const Progress = (content: ProgressItem) => (
  <div className={styles.progressBarPointWrapperStyle}>
    <span className={styles.progressBarItemAnnotationStyle}>
      <WizText fontSize="xs2" color="red.800" whiteSpace="nowrap">
        {content.annotation}
      </WizText>
    </span>
    <WizProgressPoint status={content.status} value={content.value} />
    <span className={styles.progressBarItemLabelStyle}>
      <WizText fontSize="xs2" color="gray.600" whiteSpace="nowrap">
        {content.label}
      </WizText>
    </span>
  </div>
);

const ProgressBar = ({ ...props }: Props) => {
  return (
    <div className={styles.progressBarStyle}>
      {props.contents.map((content, index) => (
        <div
          className={
            styles.progressBarItemStyle[index === 0 ? "first" : "default"]
          }
          key={content.id}
        >
          {content.tooltip ? (
            <WizTooltip content={<>{content.tooltip}</>}>
              {Progress(content)}
            </WizTooltip>
          ) : (
            Progress(content)
          )}
          <WizProgressLine active={content.progress} isFirst={index === 0} />
        </div>
      ))}
    </div>
  );
};

ProgressBar.displayName = ComponentName.ProgressBar;

export const WizProgressBar = ProgressBar;
