// packages/wiz-ui-next/src/components/base/progress-bar/progress-line.vue
<template>
  <span
    class="wiz-progress-line"
    :class="[
      progressLineStyle,
      progressLineBackgroundStyle[active ? 'active' : 'inactive'],
      progressLineWidthStyle[isFirst ? 'first' : 'default'],
    ]"
  />
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  progressLineStyle,
  progressLineBackgroundStyle,
  progressLineWidthStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/progress-bar.css";

defineOptions({
  name: ComponentName.ProgressLine,
});
interface Props {
  active?: boolean;
  isFirst: boolean;
}

defineProps<Props>();
</script>

// packages/wiz-ui-react/src/components/base/progress-bar/components/progress-line.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/progress-bar.css";
import clsx from "clsx";

type Props = {
  active?: boolean;
  isFirst: boolean;
};

const ProgressLine = ({ active, isFirst }: Props) => {
  return (
    <span
      className={clsx(
        styles.progressLineStyle,
        styles.progressLineBackgroundStyle[active ? "active" : "inactive"],
        styles.progressLineWidthStyle[isFirst ? "first" : "default"]
      )}
    />
  );
};

ProgressLine.displayName = ComponentName.ProgressLine;

export const WizProgressLine = ProgressLine;
