// packages/wiz-ui/src/components/base/show-more-less/show-more-less.vue
<template>
  <WizVStack
    :class="[showMoreLessDetailsStyle]"
    :style="{ width }"
    :open="isOpen || isAnimating"
  >
    <div
      ref="contentRef"
      :class="[showMoreLessContentStyle]"
      :style="{
        maxHeight: isOpen ? toggleHeight : 0,
      }"
    >
      <slot />
    </div>
    <div :class="showMoreLessSummaryStyle" @click="onClick">
      <WizHStack
        align="center"
        justify="between"
        gap="xs2"
        :height="variant === 'mobile' ? '2.75rem' : '1.375rem'"
        :class="[showMoreLessMessageStyle]"
      >
        <div>
          {{ isOpen ? closeMessage : openMessage }}
        </div>
        <WizIcon
          size="xl2"
          :icon="WizIExpandMore"
          color="inherit"
          :class="[
            showMoreLessExpandIconStyle,
            isOpen && showMoreLessRotateIconStyle,
          ]"
        />
      </WizHStack>
    </div>
  </WizVStack>
</template>

<script setup lang="ts">
import {
  showMoreLessContentStyle,
  showMoreLessDetailsStyle,
  showMoreLessExpandIconStyle,
  showMoreLessMessageStyle,
  showMoreLessRotateIconStyle,
  showMoreLessSummaryStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/show-more-less.css";
import { PropType, computed, ref } from "vue";

import { WizHStack, WizIcon, WizVStack } from "@/components";
import { WizIExpandMore } from "@/components/icons";

defineProps({
  variant: {
    type: String as PropType<"pc" | "mobile">,
    required: false,
    default: "pc",
  },
  isOpen: {
    type: Boolean,
    required: true,
  },
  openMessage: {
    type: String,
    required: false,
    default: "もっと見る",
  },
  closeMessage: {
    type: String,
    required: false,
    default: "閉じる",
  },
  width: {
    type: String,
    required: false,
    default: "20rem",
  },
});

interface Emit {
  (e: "toggle"): void;
}
const emit = defineEmits<Emit>();

const contentRef = ref<HTMLElement | undefined>();
const isAnimating = ref(false);

const toggleHeight = computed(() => {
  const content = contentRef.value;
  return content?.scrollHeight + "px";
});

const onClick = (event: MouseEvent) => {
  emit("toggle");
  event.preventDefault();
};
</script>

// packages/wiz-ui-react/src/components/base/show-more-less/components/show-more-less.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  showMoreLessContentStyle,
  showMoreLessDetailsStyle,
  showMoreLessExpandIconStyle,
  showMoreLessMessageStyle,
  showMoreLessRotateIconStyle,
  showMoreLessSummaryStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/show-more-less.css";
import clsx from "clsx";
import {
  FC,
  MouseEventHandler,
  ReactNode,
  useEffect,
  useRef,
  useState,
} from "react";

import { WizHStack, WizIExpandMore, WizIcon, WizVStack } from "@/components";

interface Props {
  isOpen: boolean;
  openMessage?: string;
  closeMessage?: string;
  width?: string;
  variant?: "pc" | "mobile";
  onToggle: () => void;
  children: ReactNode;
}

const ShowMoreLess: FC<Props> = ({
  isOpen,
  openMessage = "もっと見る",
  closeMessage = "閉じる",
  width = "20rem",
  variant = "pc",
  onToggle,
  children,
}) => {
  const contentRef = useRef<HTMLDivElement>(null);
  const [height, setHeight] = useState<string>("0px");

  const handleClick: MouseEventHandler = (event) => {
    event.preventDefault();
    onToggle();
  };

  useEffect(() => {
    if (!contentRef.current) return;

    setHeight(contentRef.current.scrollHeight + "px");
  }, [contentRef]);

  return (
    <div className={clsx(showMoreLessDetailsStyle)} style={{ width: width }}>
      <WizVStack>
        <div
          ref={contentRef}
          className={showMoreLessContentStyle}
          style={{ maxHeight: isOpen ? height : 0 }}
        >
          {children}
        </div>
        <div className={showMoreLessSummaryStyle} onClick={handleClick}>
          <div className={clsx(showMoreLessMessageStyle)}>
            <WizHStack
              align="center"
              justify="between"
              gap="xs2"
              height={variant === "mobile" ? "2.75rem" : "1.375rem"}
            >
              <div>{isOpen ? closeMessage : openMessage}</div>
              <div
                className={clsx(
                  showMoreLessExpandIconStyle,
                  isOpen && showMoreLessRotateIconStyle
                )}
              >
                <WizIcon size="xl2" icon={WizIExpandMore} color={"inherit"} />
              </div>
            </WizHStack>
          </div>
        </div>
      </WizVStack>
    </div>
  );
};

ShowMoreLess.displayName = ComponentName.ShowMoreLess;

export const WizShowMoreLess = ShowMoreLess;
