// packages/wiz-ui-next/src/components/base/graphs/compare/bar.vue
<template>
  <div :class="graphBarStyle" ref="graphRef">
    <span :class="graphBarLabelStyle" ref="labelRef">{{ label }}</span>
    <div
      v-for="bar in bars"
      :key="bar.id"
      :class="[graphBarItemStyle, bar.bgColorStyle]"
      ref="barRefs"
      :style="{
        height: `${bar.y * 100}%`,
        width: `${barWidth * (1 - barGap) * 100}%`,
        left: `${(bar.x - barGroupWidth / 2) * 200}%`,
      }"
    >
      <span
        :class="[graphBarNumberStyle, bar.numberColorStyle]"
        v-if="bar.y !== 0"
        ref="barFrequencyRefs"
      >
        {{ bar.frequency }}
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  graphBarItemStyle,
  graphBarLabelStyle,
  graphBarStyle,
  graphBarNumberStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/compare-graph.css";
import {
  backgroundStyle,
  colorStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import {
  PropType,
  computed,
  onBeforeUnmount,
  onMounted,
  ref,
  watch,
} from "vue";

import { CompareGraphData } from "./types";
const props = defineProps({
  label: {
    type: String,
    required: true,
  },
  data: {
    type: Object as PropType<CompareGraphData>,
    required: true,
  },
  maxFrequency: {
    type: Number,
    required: true,
  },
  /** バーの間隔に影響します。0~1の値を指定してください。 */
  barGap: {
    type: Number,
    required: false,
    default: 0.1,
  },
  /** バーの太さに影響します。0~1の値を指定してください。 */
  barGroupWidth: {
    type: Number,
    required: false,
    default: 0.8,
  },
  /** バーの傾き(rad)を指定します。*/
  theta: {
    type: Number,
    required: false,
    default: 0,
  },
});

const barRefs = ref<HTMLElement[]>();
const barFrequencyRefs = ref<HTMLElement[]>();
const labelRef = ref<HTMLElement>();
const graphRef = ref<HTMLElement>();

const updateLabelTransformStyle = () => {
  if (!labelRef.value || !graphRef.value) return;
  const d = labelRef.value.clientWidth / 2;
  const cx = Math.cos(props.theta) * d;
  const gx = (graphRef.value.clientWidth * props.barGroupWidth) / 2;
  const dx = (() => {
    if (props.theta === 0) return 0;
    return gx < cx ? gx - cx : 0;
  })();
  labelRef.value.style.transform = `
    translateX(${dx}px)
    translate(-50%, ${d * Math.abs(Math.sin(props.theta))}px)
    rotate(-${props.theta}rad)`;
};

const updateBarItemCurrentHeight = () => {
  const barElms = barRefs.value;
  const barFrequencyElms = barFrequencyRefs.value;

  if (!barElms || !barFrequencyElms) return;
  Array.from({ length: barFrequencyElms.length }).forEach((_, i) => {
    const barFrequencyElm = barFrequencyElms[i];
    const barElm = barElms[i];
    if (barFrequencyElm.offsetHeight + 16 < barElm.offsetHeight) {
      barFrequencyElm.style.padding = "8px 0";
      return;
    }
    barFrequencyElm.style.padding = "0";
    if (barFrequencyElm.offsetHeight < barElm.offsetHeight) {
      barFrequencyElm.style.top =
        (barElm.offsetHeight - barFrequencyElm.offsetHeight) / 2 + "px";
      return;
    }
    barFrequencyElm.style.top = barFrequencyElm.offsetHeight * -1 + "px";
    barFrequencyElm.style.color = "#606166";
  });
};

const barItemCurrentResizeObserver = new ResizeObserver(
  updateBarItemCurrentHeight
);

const graphResizeObserver = new ResizeObserver(updateLabelTransformStyle);

watch(() => props.theta, updateLabelTransformStyle);

onMounted(() => {
  if (barRefs.value)
    barRefs.value.forEach((barItemCurrentRef) => {
      barItemCurrentResizeObserver.observe(barItemCurrentRef);
    });
  if (graphRef.value) graphResizeObserver.observe(graphRef.value);
});

onBeforeUnmount(() => {
  barItemCurrentResizeObserver.disconnect();
  graphResizeObserver.disconnect();
});

const barWidth = computed(() => props.barGroupWidth / props.data.data.length);
const bars = computed(() =>
  props.data.data.map((data, i) => {
    return {
      id: data.id,
      x: barWidth.value * (i + 0.5),
      y: data.frequency / props.maxFrequency,
      bgColorStyle: backgroundStyle[data.barColor ?? "green.800"],
      numberColorStyle: colorStyle[data.numberColor ?? "white.800"],
      frequency: data.frequency,
    };
  })
);
</script>

// packages/wiz-ui-react/src/components/base/graphs/compare/components/bar.tsx
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/compare-graph.css";
import {
  backgroundStyle,
  colorStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import { FC, useEffect, useMemo, useRef } from "react";

import { CompareGraphData } from "./types";

type Props = {
  data: CompareGraphData;
  maxFrequency: number;
  barGap: number;
  barGroupWidth: number;
  /** バーの傾き(rad)を指定します。*/
  theta: number;
};

export const Bar: FC<Props> = ({
  data,
  maxFrequency,
  barGap,
  barGroupWidth,
  theta,
}) => {
  const wrapperRef = useRef<HTMLDivElement>(null);
  const labelRef = useRef<HTMLSpanElement>(null);
  const barsRef = useRef<Array<HTMLDivElement | null>>([]);
  const barFrequenciesRef = useRef<Array<HTMLSpanElement | null>>([]);

  const barDisplayData = useMemo(() => {
    const groupData = data.data;
    const barWidthRatio = barGroupWidth / groupData.length;

    return groupData.map((data, i) => {
      return {
        id: data.id,
        frequency: data.frequency,
        bgColorStyle: backgroundStyle[data.barColor ?? "green.800"],
        numberColorStyle: colorStyle[data.numberColor ?? "white.800"],
        elementStyle: {
          height: `${(data.frequency / maxFrequency) * 100}%`,
          width: `${barWidthRatio * (1 - barGap) * 100}%`,
          left: `${(barWidthRatio * (i * 2 + 1) - barGroupWidth) * 100}%`,
        },
      };
    });
  }, [barGap, barGroupWidth, data.data, maxFrequency]);

  useEffect(() => {
    // 配列の ref の数を是正
    barsRef.current = barsRef.current.slice(0, barDisplayData.length);
    barFrequenciesRef.current = barFrequenciesRef.current.slice(
      0,
      barDisplayData.length
    );
  }, [barDisplayData.length]);

  useEffect(() => {
    // ラベルの回転による位置調整を行う
    const labelElm = labelRef.current;
    const wrapperElm = wrapperRef.current;
    if (!labelElm || !wrapperElm) return;

    if (theta === 0) {
      // theta = 0 のときは中央寄せのみ
      labelElm.style.transform = "translateX(-50%)";
      return;
    }

    const updateLabelTransformStyle = () => {
      const labelHalfWidth = labelElm.clientWidth / 2;
      const rotatedLabelHalfWidth = Math.cos(theta) * labelHalfWidth;
      const groupHalfWidth = (wrapperElm.clientWidth * barGroupWidth) / 2;
      const translateX = Math.min(groupHalfWidth - rotatedLabelHalfWidth, 0);
      const translateY = labelHalfWidth * Math.abs(Math.sin(theta));
      labelElm.style.transform = `
        translateX(-50%)
        translate(${translateX}px, ${translateY}px)
        rotate(-${theta}rad)
      `;
    };

    const graphResizeObserver = new ResizeObserver(updateLabelTransformStyle);
    graphResizeObserver.observe(wrapperElm);

    return () => {
      graphResizeObserver.disconnect();
    };
  }, [barGroupWidth, theta]);

  useEffect(() => {
    const barElms = barsRef.current;
    const barFrequencyElms = barFrequenciesRef.current;
    if (!barElms || !barFrequencyElms) return;

    const updateBarItemCurrentHeight = () => {
      barElms.forEach((barElm, i) => {
        const barFrequencyElm = barFrequencyElms[i];
        if (!barFrequencyElm || !barElm) return;
        const verticalPadding = 8;
        if (
          barFrequencyElm.offsetHeight + verticalPadding * 2 <
          barElm.offsetHeight
        ) {
          // バー内部にラベルを表示
          barFrequencyElm.style.padding = `${verticalPadding}px 0`;
          return;
        }
        barFrequencyElm.style.padding = "0";
        if (barFrequencyElm.offsetHeight < barElm.offsetHeight) {
          // padding 調整してバー内部にラベルを表示
          barFrequencyElm.style.top =
            (barElm.offsetHeight - barFrequencyElm.offsetHeight) / 2 + "px";
          return;
        }
        // バー上部にラベルを表示
        barFrequencyElm.style.top = barFrequencyElm.offsetHeight * -1 + "px";
        barFrequencyElm.style.color = "#606166";
      });
    };

    const barItemCurrentResizeObserver = new ResizeObserver(
      updateBarItemCurrentHeight
    );
    barElms.forEach((elem) => {
      if (elem) barItemCurrentResizeObserver.observe(elem);
    });

    return () => {
      barItemCurrentResizeObserver.disconnect();
    };
  }, []);

  return (
    <div className={styles.graphBarStyle} ref={wrapperRef}>
      <span className={styles.graphBarLabelStyle} ref={labelRef}>
        {data.label}
      </span>
      {barDisplayData.map((item, i) => (
        <div
          key={item.id}
          className={clsx(styles.graphBarItemStyle, item.bgColorStyle)}
          style={item.elementStyle}
          ref={(ref) => {
            barsRef.current[i] = ref;
          }}
        >
          {item.frequency !== 0 && (
            <span
              className={clsx(
                styles.graphBarNumberStyle,
                item.numberColorStyle
              )}
              ref={(ref) => {
                barFrequenciesRef.current[i] = ref;
              }}
            >
              {item.frequency}
            </span>
          )}
        </div>
      ))}
    </div>
  );
};
