// packages/wiz-ui-next/src/components/base/card/card.vue
<template>
  <div
    :class="[
      cardStyle,
      fit && cardFitStyle,
      hexpand && cardHexpandStyle,
      shadow && cardShadowStyle,
      border && cardBorderStyle,
      px && paddingXStyle[px],
      py && paddingYStyle[py],
      !px && !py && paddingStyle[p],
      backgroundStyle[backgroundColor],
    ]"
    :style="{
      maxWidth,
      borderColor: border ? getColorCss(borderColor) : undefined,
    }"
  >
    <WizVStack :gap="gap" :align="align" :height="hexpand ? '100%' : 'auto'">
      <div
        v-if="$slots.mainHeaderArea || $slots.subHeaderArea"
        :class="cardHeaderStyle"
      >
        <div>
          <slot name="mainHeaderArea" />
        </div>
        <div>
          <slot name="subHeaderArea" />
        </div>
      </div>
      <div v-if="$slots.default" :class="cardBodyStyle">
        <slot />
      </div>
      <div v-if="$slots.footer">
        <slot name="footer" />
      </div>
    </WizVStack>
  </div>
</template>

<script setup lang="ts">
import {
  ColorKeys,
  ComponentName,
  SpacingKeys,
  getColorCss,
} from "@wizleap-inc/wiz-ui-constants";
import {
  cardBodyStyle,
  cardBorderStyle,
  cardFitStyle,
  cardHexpandStyle,
  cardHeaderStyle,
  cardShadowStyle,
  cardStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/card.css";
import {
  backgroundStyle,
  paddingStyle,
  paddingXStyle,
  paddingYStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import { PropType } from "vue";

import { WizVStack } from "@/components";

defineOptions({
  name: ComponentName.Card,
});

defineProps({
  p: {
    type: String as PropType<SpacingKeys>,
    required: false,
    default: "md",
  },
  px: {
    type: String as PropType<SpacingKeys>,
    required: false,
  },
  py: {
    type: String as PropType<SpacingKeys>,
    required: false,
  },
  backgroundColor: {
    type: String as PropType<ColorKeys>,
    required: false,
    default: "white.800",
  },
  shadow: {
    type: Boolean,
    required: false,
  },
  border: {
    type: Boolean,
    required: false,
  },
  borderColor: {
    type: String as PropType<ColorKeys>,
    required: false,
    default: "gray.400",
  },
  align: {
    type: String as PropType<"start" | "center" | "end" | "stretch">,
    required: false,
    default: "end",
  },
  fit: {
    type: Boolean,
    required: false,
  },
  hexpand: {
    type: Boolean,
    required: false,
  },
  maxWidth: {
    type: String,
    required: false,
  },
  gap: {
    type: String as PropType<SpacingKeys>,
    required: false,
    default: "md",
  },
});
</script>

// packages/wiz-ui-react/src/components/base/card/components/card.tsx
import {
  ColorKeys,
  ComponentName,
  getColorCss,
  SpacingKeys,
} from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/card.css";
import {
  backgroundStyle,
  paddingStyle,
  paddingXStyle,
  paddingYStyle,
} from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import { ComponentProps, ReactNode } from "react";

import { WizVStack } from "@/components";
import { BaseProps } from "@/types";
type Props = BaseProps & {
  p?: SpacingKeys;
  px?: SpacingKeys;
  py?: SpacingKeys;
  backgroundColor?: ColorKeys;
  shadow?: boolean;
  border?: boolean;
  borderColor?: ColorKeys;
  align?: "start" | "center" | "end" | "stretch";
  fit?: boolean;
  hexpand?: boolean;
  maxWidth?: string;
  gap?: SpacingKeys;
  children?: ReactNode;
  mainHeaderArea?: ReactNode;
  subHeaderArea?: ReactNode;
  footerArea?: ReactNode;
} & ComponentProps<"div">;

const Card = ({
  className,
  style,
  p = "md",
  px,
  py,
  backgroundColor = "white.800",
  shadow,
  border,
  align = "end",
  fit,
  hexpand,
  maxWidth,
  gap = "md",
  children,
  mainHeaderArea,
  subHeaderArea,
  footerArea,
  borderColor = "gray.400",
  ...props
}: Props) => {
  return (
    <div
      {...props}
      className={clsx([
        className,
        styles.cardStyle,
        fit && styles.cardFitStyle,
        hexpand && styles.cardHexpandStyle,
        shadow && styles.cardShadowStyle,
        border && styles.cardBorderStyle,
        px && paddingXStyle[px],
        py && paddingYStyle[py],
        !px && !py && paddingStyle[p],
        backgroundStyle[backgroundColor],
      ])}
      style={{
        ...style,
        maxWidth,
        borderColor: border ? getColorCss(borderColor) : undefined,
      }}
    >
      <WizVStack
        gap={gap}
        align={align}
        nowrap={true}
        height={hexpand ? "100%" : "auto"}
      >
        {(mainHeaderArea || subHeaderArea) && (
          <div className={styles.cardHeaderStyle}>
            <div>{mainHeaderArea}</div>
            <div>{subHeaderArea}</div>
          </div>
        )}
        {children && <div className={styles.cardBodyStyle}>{children}</div>}
        {footerArea && <div>{footerArea}</div>}
      </WizVStack>
    </div>
  );
};

Card.displayName = ComponentName.Card;
export const WizCard = Card;
