// packages/wiz-ui-next/src/components/base/loading-overlay/loading-overlay.vue
<template>
  <div
    :class="[styles.LoadingOverlay, !isLoading && styles.LoadingOverlayHidden]"
  >
    <div :class="styles.LoadingOverlayBar">
      <div :class="styles.LoadingOverlayBarInner" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/loading-overlay.css";

defineOptions({
  name: ComponentName.LoadingOverlay,
});

defineProps({
  isLoading: {
    type: Boolean,
    required: true,
  },
});
</script>

// packages/wiz-ui-react/src/components/base/loading-overlay/components/loading-overlay.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/loading-overlay.css";
import { clsx } from "clsx";
import { FC } from "react";

interface Props {
  isLoading: boolean;
}

const LoadingOverlay: FC<Props> = ({ isLoading }) => {
  return (
    <div
      className={clsx(
        styles.LoadingOverlay,
        !isLoading && styles.LoadingOverlayHidden
      )}
    >
      <div className={styles.LoadingOverlayBar}>
        <div className={styles.LoadingOverlayBarInner} />
      </div>
    </div>
  );
};

LoadingOverlay.displayName = ComponentName.LoadingOverlay;

export const WizLoadingOverlay = LoadingOverlay;
