// packages/wiz-ui-react/src/components/base/dropdown/components/dropdown-item.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/dropdown.css";
import clsx from "clsx";
import { ComponentPropsWithoutRef, FC, ReactNode, useState } from "react";

import { WizHStack, WizIcon } from "@/components";
import { TIcon } from "@/components/icons";

type Props = ComponentPropsWithoutRef<"button"> & {
  icon?: TIcon;
  children: ReactNode;
};

const DropdownItem: FC<Props> = ({
  className,
  icon,
  onClick,
  children,
  ...props
}) => {
  const [isHover, setIsHover] = useState(false);
  const [isPressed, setIsPressed] = useState(false);

  function getIconColor() {
    if (isPressed) {
      return "white.800";
    }
    if (isHover) {
      return "green.800";
    }
    return undefined;
  }

  return (
    <button
      {...props}
      type="button"
      className={clsx(className, styles.dropdownItemStyle)}
      onClick={onClick}
      onMouseOver={() => setIsHover(true)}
      onMouseOut={() => setIsHover(false)}
      onMouseDown={() => setIsPressed(true)}
      onMouseUp={() => setIsPressed(false)}
    >
      <WizHStack align="center">
        {children}
        {icon && <WizIcon icon={icon} size="md" color={getIconColor()} />}
      </WizHStack>
    </button>
  );
};

DropdownItem.displayName = ComponentName.DropdownItem;

export const WizDropdownItem = DropdownItem;

// packages/wiz-ui-next/src/components/base/dropdown/dropdown-item.vue
<template>
  <div
    :class="dropdownItemStyle"
    @click="onClick"
    @mouseover="onMouseover"
    @mouseout="onMouseout"
    @mousedown="onMousedown"
    @mouseup="onMouseup"
  >
    <WizHStack align="center">
      <slot />
      <WizIcon v-if="icon" size="md" :icon="icon" :color="computedColor" />
    </WizHStack>
  </div>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import { dropdownItemStyle } from "@wizleap-inc/wiz-ui-styles/bases/dropdown.css";
import { computed, ref } from "vue";

import { WizIcon, WizHStack } from "@/components";
import type { TIcon } from "@/components/icons";

defineOptions({
  name: ComponentName.DropdownItem,
});

interface Props {
  icon?: TIcon;
}

defineProps<Props>();

interface Emit {
  (event: "click"): void;
}

const emit = defineEmits<Emit>();

const onClick = () => emit("click");

const isHover = ref(false);
const onMouseover = () => (isHover.value = true);
const onMouseout = () => (isHover.value = false);

const isPressed = ref(false);
const onMousedown = () => (isPressed.value = true);
const onMouseup = () => (isPressed.value = false);

const computedColor = computed(() => {
  if (isPressed.value) {
    return "white.800";
  }
  if (isHover.value) {
    return "green.800";
  }
  return undefined;
});
</script>
