// packages/wiz-ui-next/src/components/base/navigation/container.vue
<template>
  <div
    :class="navigationContainerStyle"
    :style="{
      ...computedStickyStyle,
      width: computedWidth,
    }"
  >
    <div :class="navigationContainerItemsStyle">
      <slot />
    </div>
    <div v-if="isOpen && slots.footer" :class="navigationContainerFooterStyle">
      <slot name="footer" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { THEME, ComponentName } from "@wizleap-inc/wiz-ui-constants";
import {
  navigationContainerStyle,
  navigationContainerItemsStyle,
  navigationContainerFooterStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/navigation.css";
import { computed, StyleValue, useSlots } from "vue";

defineOptions({
  name: ComponentName.NavigationContainer,
});

const slots = useSlots();

const props = defineProps({
  width: {
    type: String,
    required: false,
  },
  sticky: {
    type: Boolean,
    required: false,
  },
  isOpen: {
    type: Boolean,
    required: false,
    default: true,
  },
});

const computedWidth = computed(() => {
  if (!props.isOpen)
    return `calc(${THEME.spacing.xl} * 2 + ${THEME.spacing.sm})`;
  if (props.width) return props.width;
  return "180px";
});

const computedStickyStyle = computed(() => {
  const styles: StyleValue = {};
  if (props.sticky) styles.position = "sticky";
  if (props.sticky) styles.top = `calc(${THEME.share.HEADER_HEIGHT} + 1px)`; // +1px for border of header
  if (props.sticky) styles.left = 0;
  if (props.sticky) styles.borderRight = `1px solid ${THEME.color.gray[400]}`;
  if (props.sticky)
    styles.height = `calc(100vh - ${THEME.share.HEADER_HEIGHT} - 1px)`;
  return styles;
});
</script>

// packages/wiz-ui-react/src/components/base/navigation/components/container.tsx
import { ComponentName, THEME } from "@wizleap-inc/wiz-ui-constants";
import {
  navigationContainerFooterStyle,
  navigationContainerItemsStyle,
  navigationContainerStyle,
} from "@wizleap-inc/wiz-ui-styles/bases/navigation.css";
import { CSSProperties, FC, ReactNode } from "react";

interface Props {
  isOpen: boolean;
  width?: string;
  sticky?: boolean;
  children: ReactNode;
  footer?: ReactNode;
}

const Container: FC<Props> = ({
  isOpen = true,
  width,
  sticky = false,
  children,
  footer,
}) => {
  const widthStyle = () => {
    if (width) return width;
    if (isOpen) return "180px";
    return `calc(${THEME.spacing.xl} * 2 + ${THEME.spacing.sm})`;
  };

  const stickyStyle = () => {
    const styles: CSSProperties = {};
    if (sticky) styles.position = "sticky";
    if (sticky) styles.top = `calc(${THEME.share.HEADER_HEIGHT} + 1px)`; // +1px for border of header
    if (sticky) styles.left = 0;
    if (sticky) styles.borderRight = `1px solid ${THEME.color.gray[400]}`;
    if (sticky)
      styles.height = `calc(100vh - ${THEME.share.HEADER_HEIGHT} - 1px)`;
    return styles;
  };

  return (
    <div
      className={navigationContainerStyle}
      style={{ ...stickyStyle(), width: widthStyle() }}
    >
      <div className={navigationContainerItemsStyle}>{children}</div>
      {isOpen && footer && (
        <div className={navigationContainerFooterStyle}>{footer}</div>
      )}
    </div>
  );
};
Container.displayName = ComponentName.NavigationContainer;

export const WizNavigationContainer = Container;
