// packages/wiz-ui-react/src/components/base/graphs/circle/components/bar.tsx
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/circle-graph.css";
import { FC, ReactNode, useMemo } from "react";

type Props = {
  percentages: number[];
  children?: ReactNode;
};

export const Bar: FC<Props> = ({ percentages, children }) => {
  const barDisplayData = useMemo(() => {
    let currentRotatedPercentage = 0;
    return percentages
      .map((percentage) => {
        const startPercentage = currentRotatedPercentage;
        currentRotatedPercentage += percentage;
        return {
          width: percentage - styles.STROKE_WIDTH,
          startPercentage,
        };
      })
      .filter((data) => data.width > 0);
  }, [percentages]);

  const pathD = `M${styles.HALF_VIEW_BOX_SIZE} ${styles.MARGIN_OF_CIRCLE}
                 a ${styles.RADIUS} ${styles.RADIUS} 0 0 1 0 ${styles.DIAMETER}
                 a ${styles.RADIUS} ${styles.RADIUS} 0 0 1 0 ${
    -1 * styles.DIAMETER
  }`;

  return (
    <div className={styles.CircleBarContainerStyle}>
      <svg
        className={styles.CircleBarSVGStyle}
        viewBox={`0 0 ${styles.VIEW_BOX_SIZE} ${styles.VIEW_BOX_SIZE}`}
      >
        <path
          className={styles.CircleBarBgStyle}
          strokeWidth={styles.STROKE_WIDTH}
          d={pathD}
        />
        {barDisplayData.map((item, i) => (
          <path
            key={i}
            className={styles.CircleBarStyle}
            style={{
              stroke:
                styles.GRAPH_COLORS[i] ||
                styles.GRAPH_COLORS[styles.GRAPH_COLORS.length - 1],
            }}
            strokeDasharray={`${item.width}, 100`}
            strokeWidth={styles.STROKE_WIDTH}
            d={pathD}
            transform={`rotate(${
              ((item.startPercentage + styles.STROKE_WIDTH / 2) * 360) / 100
            }, ${styles.HALF_VIEW_BOX_SIZE}, ${styles.HALF_VIEW_BOX_SIZE})`}
          />
        ))}
      </svg>
      <div className={styles.CircleBarPercentageStyle}>{children}</div>
    </div>
  );
};

// packages/wiz-ui/src/components/base/graphs/circle/bar.vue
<template>
  <div :class="styles.CircleBarContainerStyle">
    <svg
      :class="styles.CircleBarSVGStyle"
      :viewBox="`0 0 ${styles.VIEW_BOX_SIZE} ${styles.VIEW_BOX_SIZE}`"
    >
      <path
        :class="styles.CircleBarBgStyle"
        :stroke-width="styles.STROKE_WIDTH"
        :d="`M${styles.HALF_VIEW_BOX_SIZE} ${styles.MARGIN_OF_CIRCLE}
            a ${styles.RADIUS} ${styles.RADIUS} 0 0 1 0 ${styles.DIAMETER}
            a ${styles.RADIUS} ${styles.RADIUS} 0 0 1 0 ${
          -1 * styles.DIAMETER
        }`"
      />
      <template v-for="(data, i) in percentagesForDisplay">
        <path
          v-if="data.percentage > 0"
          :class="styles.CircleBarStyle"
          :style="{
            stroke:
              styles.GRAPH_COLORS[i] ||
              styles.GRAPH_COLORS[styles.GRAPH_COLORS.length - 1],
          }"
          :stroke-dasharray="`${data.percentage}, 100`"
          :stroke-width="styles.STROKE_WIDTH"
          :d="`M${styles.HALF_VIEW_BOX_SIZE} ${styles.MARGIN_OF_CIRCLE}
              a ${styles.RADIUS} ${styles.RADIUS} 0 0 1 0 ${styles.DIAMETER}
              a ${styles.RADIUS} ${styles.RADIUS} 0 0 1 0 ${
            -1 * styles.DIAMETER
          }`"
          :transform="`rotate(${
            ((data.start + styles.STROKE_WIDTH / 2) * 360) / 100
          }, ${styles.HALF_VIEW_BOX_SIZE}, ${styles.HALF_VIEW_BOX_SIZE})`"
        />
      </template>
    </svg>
    <div :class="styles.CircleBarPercentageStyle">
      <slot />
    </div>
  </div>
</template>
<script setup lang="ts">
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/circle-graph.css";
import { computed, PropType } from "vue";

const props = defineProps({
  percentages: {
    type: Array as PropType<number[]>,
    required: true,
  },
});

const percentagesForDisplay = computed(() => {
  let startRotatedPercentage = 0;
  return props.percentages.map((percentage) => {
    const displayPercentageDegree = percentage;
    const before = startRotatedPercentage;
    startRotatedPercentage += displayPercentageDegree;
    return {
      percentage:
        displayPercentageDegree -
        (percentage < styles.STROKE_WIDTH ? percentage : styles.STROKE_WIDTH),
      start: before,
    };
  });
});
</script>
