// packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.vue
<template>
  <WizPopupContainer :expand="expand">
    <div
      :class="[
        styles.selectBoxStyle,
        commonStyles.inputBorderStyle[state],
        disabled && styles.selectBoxDisabledStyle,
        styles.selectBoxCursorStyle[selectBoxCursor],
      ]"
      :style="{ width: computedWidth }"
    >
      <div :class="styles.selectBoxInnerBoxStyle" @click="toggleSelectBox">
        <WizHStack align="center" justify="between" height="100%">
          <span
            v-if="!isValueMatched"
            :class="styles.selectBoxPlaceholderStyle"
            >{{ placeholder }}</span
          >
          <span
            v-for="(option, key) in options"
            v-show="option.value === value"
            :key="'selected' + key"
            :class="styles.selectBoxInnerBoxSelectedValueStyle"
          >
            {{ option.label }}
          </span>
          <WizIExpandLess
            v-if="openSelectBox"
            :class="styles.selectBoxInnerBoxLessStyle"
          />
          <WizIExpandMore
            v-else-if="!openSelectBox"
            :class="styles.selectBoxInnerBoxMoreStyle"
          />
        </WizHStack>
      </div>
    </div>
    <WizPopup :isOpen="openSelectBox" @onClose="openSelectBox = false">
      <div :class="styles.selectBoxSelectorStyle" :style="{ minWidth: width }">
        <WizVStack gap="xs2">
          <div
            :class="styles.selectBoxSelectorOptionStyle"
            v-for="(option, key) in options"
            :key="'option' + key"
            @click="onSelect(option.value)"
          >
            <span>
              {{ option.label }}
            </span>
            <span v-if="option.exLabel">
              {{ option.exLabel }}
            </span>
          </div>
        </WizVStack>
      </div>
    </WizPopup>
  </WizPopupContainer>
</template>

<script setup lang="ts">
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/selectbox-input.css";
import * as commonStyles from "@wizleap-inc/wiz-ui-styles/commons";
import { ref, computed, inject, PropType } from "vue";

import { WizPopupContainer, WizPopup } from "@/components";
import { WizIExpandLess, WizIExpandMore } from "@/components/icons";
import { formControlKey } from "@/hooks/use-form-control-provider";

import { WizHStack, WizVStack } from "../../stack";

import { SelectBoxOption } from "./types";

defineOptions({
  name: ComponentName.SelectBox,
});

const props = defineProps({
  options: {
    type: Array as PropType<SelectBoxOption[]>,
    required: true,
  },
  value: {
    type: Number,
    required: true,
  },
  placeholder: {
    type: String,
    required: false,
    default: "選択してください",
  },
  width: {
    type: String,
    required: false,
    default: "10rem",
  },
  disabled: {
    type: Boolean,
    required: false,
    default: false,
  },
  expand: {
    type: Boolean,
    required: false,
  },
  isOpen: {
    type: Boolean,
    required: false,
    default: false,
  },
});

const openSelectBox = ref(props.isOpen);
const toggleSelectBox = () => {
  if (props.disabled) {
    return;
  }
  openSelectBox.value = !openSelectBox.value;
};

interface Emit {
  (e: "input", value: number): void;
}
const emit = defineEmits<Emit>();

const onSelect = (value: number) => {
  toggleSelectBox();
  emit("input", value);
};

const selectBoxCursor = computed(() =>
  props.disabled ? "disabled" : "default"
);

// Form Control
const form = inject(formControlKey);
const isError = computed(() => (form ? form.isError.value : false));

const computedWidth = computed(() => (props.expand ? "100%" : props.width));

const state = computed(() => {
  if (isError.value) return "error";
  if (openSelectBox.value) return "active";
  return "default";
});

const isValueMatched = computed(() => {
  return props.options.some((option) => option.value === props.value);
});
</script>

// packages/wiz-ui-react/src/components/base/inputs/selectbox/components/selectbox.tsx
import { ComponentName } from "@wizleap-inc/wiz-ui-constants";
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/selectbox-input.css";
import { inputBorderStyle } from "@wizleap-inc/wiz-ui-styles/commons";
import clsx from "clsx";
import {
  FC,
  KeyboardEventHandler,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

import {
  WizHStack,
  WizIExpandLess,
  WizIExpandMore,
  WizPopup,
  WizVStack,
} from "@/components";
import { FormControlContext } from "@/components/custom/form/form-control-context";

type SelectBoxOption = {
  label: string;
  exLabel?: string;
  value: number;
};

type Props = {
  options: SelectBoxOption[];
  value: number | null;
  placeholder?: string;
  width?: string;
  disabled?: boolean;
  expand?: boolean;
  error?: boolean;
  isDirectionFixed?: boolean;
  onChange: (value: number | null) => void;
};

const SelectBox: FC<Props> = ({
  options,
  value,
  placeholder = "選択してください",
  width = "10rem",
  disabled = false,
  expand,
  error,
  isDirectionFixed = false,
  onChange,
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const anchorRef = useRef<HTMLDivElement>(null);
  const formControl = useContext(FormControlContext);

  useEffect(() => {
    if (disabled && isOpen) {
      setIsOpen(false);
    }
  }, [disabled, isOpen]);

  const selectedOption = useMemo(
    () => options.find((option) => option.value === value),
    [options, value]
  );

  const toggleOpen = () => {
    if (disabled) {
      return;
    }
    setIsOpen(!isOpen);
  };

  const handleClickOption = (option: SelectBoxOption) => {
    setIsOpen(false);
    onChange(option.value);
  };

  const getInputBorderStyleKey = () => {
    if (error || formControl.error) return "error";
    if (isOpen) return "active";
    return "default";
  };

  const handleKeyDown: KeyboardEventHandler = (e) => {
    switch (e.key) {
      case " ":
        if (isOpen) {
          // TODO: キーボード操作で option を選択可能にする
        } else {
          setIsOpen(true);
        }
        break;
      case "Escape":
        setIsOpen(false);
        break;
    }
  };

  return (
    <>
      <div
        ref={anchorRef}
        className={clsx(
          styles.selectBoxStyle,
          inputBorderStyle[getInputBorderStyleKey()],
          disabled && styles.selectBoxDisabledStyle,
          styles.selectBoxCursorStyle[disabled ? "disabled" : "default"]
        )}
        style={{
          width: expand ? "100%" : width,
        }}
        onClick={toggleOpen}
        role="combobox"
        onKeyDown={handleKeyDown}
        tabIndex={disabled ? undefined : 0}
      >
        <div className={styles.selectBoxInnerBoxStyle}>
          <WizHStack align="center" justify="between" height="100%">
            {selectedOption ? (
              <span className={styles.selectBoxInnerBoxSelectedValueStyle}>
                {selectedOption.label}
              </span>
            ) : (
              <span className={styles.selectBoxPlaceholderStyle}>
                {placeholder}
              </span>
            )}
            {isOpen ? (
              <div
                className={styles.selectBoxInnerBoxLessStyle}
                style={{ display: "flex" }}
              >
                <WizIExpandLess />
              </div>
            ) : (
              <div
                className={styles.selectBoxInnerBoxMoreStyle}
                style={{ display: "flex" }}
              >
                <WizIExpandMore />
              </div>
            )}
          </WizHStack>
        </div>
      </div>
      <WizPopup
        isOpen={isOpen}
        onClose={useCallback(() => setIsOpen(false), [])}
        anchorElement={anchorRef}
        isDirectionFixed={isDirectionFixed}
      >
        <div
          className={styles.selectBoxSelectorStyle}
          style={{ minWidth: width }}
        >
          <WizVStack gap="xs2">
            {options.map((option) => (
              <div
                key={`${option.value}-${option.label}`}
                className={styles.selectBoxSelectorOptionStyle}
                onClick={() => handleClickOption(option)}
              >
                <span>{option.label}</span>
                {option.exLabel && <span>{option.exLabel}</span>}
              </div>
            ))}
          </WizVStack>
        </div>
      </WizPopup>
    </>
  );
};

SelectBox.displayName = ComponentName.SelectBox;

export const WizSelectBox = SelectBox;
