// packages/wiz-ui-react/src/components/base/graphs/poll/components/row.tsx
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/poll-graph.css";
import { FC } from "react";

import { Bar } from "./bar";

type Props = {
  percentage?: number;
  label?: string;
  innerLabel?: string;
  labelWidth: string;
  isColorFixed?: boolean;
};

export const Row: FC<Props> = ({
  percentage,
  label,
  innerLabel,
  labelWidth,
  isColorFixed,
}) => {
  return (
    <div className={styles.PollRowStyle}>
      <span className={styles.PollLabelStyle} style={{ width: labelWidth }}>
        {label}
      </span>
      <div className={styles.PollStyle}>
        {percentage !== undefined && (
          <Bar
            percentage={percentage}
            label={innerLabel}
            isColorFixed={isColorFixed}
          />
        )}
      </div>
    </div>
  );
};

// packages/wiz-ui-next/src/components/base/graphs/poll/row.vue
<template>
  <div :class="styles.PollRowStyle">
    <span :class="styles.PollLabelStyle" :style="{ width: labelWidth }">{{
      label
    }}</span>
    <div :class="styles.PollStyle">
      <Bar
        v-if="barPercentage !== undefined"
        :isColorFixed="isColorFixed"
        :barPercentage="barPercentage"
        :innerLabel="innerLabel"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import * as styles from "@wizleap-inc/wiz-ui-styles/bases/poll-graph.css";
import { PropType } from "vue";

import Bar from "./bar.vue";

defineProps({
  isColorFixed: {
    type: Boolean as PropType<boolean>,
    required: false,
  },
  barPercentage: {
    type: Number as PropType<number>,
    required: false,
  },
  label: {
    type: String as PropType<string>,
    required: false,
  },
  innerLabel: {
    type: String as PropType<string>,
    required: false,
  },
  labelWidth: {
    type: String,
    required: true,
  },
});
</script>
